messari/subgraphs

schema-common.graphql
schema-dex-amm.graphql
schema-lending.graphql
schema-yield.graphql
subgraphs/yearn-v2/schema.graphql

This PR introduces two changes to the schema:
- Added a subgraph `version` to the `Protocol` interface/entities. This makes it easier on the client side to identify the version of the subgraphs and handle cases accordingly.
- Changed token amount from `BigDecimal` to `BigInt`, also preserve full token precision (i.e. no need to handle decimals in the subgraph implementation). Here are the reasoning:
1. Performance boost. BigInt is faster to process and index.
2. Easier to implement. No need for convert from native EVM types.
3. Preserves precision.

Updates to the schema: token amount and subgraph versioning

---

schema-common.graphql
schema-dex-amm.graphql
schema-lending.graphql
schema-yield.graphql
subgraphs/yearn-v2/schema.graphql

- Added `fees` to `LiquidityPool` to track fees per pool, which can be different for each pool (e.g. on Uni v3 or on Curve)
- Adding `totalUniqueUsers` and `totalValueLockedUSD` to the `Protocol` entity to make calculation/aggregation easier.
- Note that there is a bug in the existing implementation of `totalUniqueUsers` in `UsageMetricsDailySnapshot` as that value accumulates from 0 for every new day. You can either fix it yourself or I will have a reference implementation.

Updates to schema: add aggregate metrics to Protocol. Added liquidity pool fees

---

schema-common.graphql
schema-dex-amm.graphql
subgraphs/_reference_/schema.graphql
subgraphs/_reference_/src/common/constants.ts
subgraphs/uniswap-v2/schema.graphql
subgraphs/uniswap-v2/src/common/constants.ts
subgraphs/uniswap-v2/src/common/helpers.ts

TRADING_FEE actually means FIXED_TRADING_FEE, while TIERED_FEE and DYNAMIC_FEE actually mean TIERED_TRADING_FEE and DYNAMIC_TRADING_FEE
PROTOCOL_FEE is different from X_TRADING_FEE since it is paid to the protocol
Rename should make it more clearer

rename enum values of LiquidityPoolFeeType

---

subgraphs/compound-v2/src/common/utils/constants.ts
subgraphs/compound-v2/src/mappings/helpers.ts

Fix APY rate calcs and removed unnecessary totalDepositUSD/totalBorrowUSD calcs
See APY math here: https://compound.finance/docs#protocol-math

compound - fix apy calcs

---

subgraphs/belt/schema.graphql
subgraphs/belt/src/entities/Protocol.ts
subgraphs/belt/src/entities/Vault.ts
subgraphs/belt/src/handlers/common.ts
subgraphs/belt/tests/vault.test.ts

- Fixed belt finance issue with protocol metrics.
- The `derivedFrom` field is not directly accessible, so added extra field that stores the ids `_vaultIds`

fixed protocol metrics, vault ids added

---

subgraphs/compound-forks/bastion-protocol/src/mapping.ts
subgraphs/compound-forks/benqi/src/mapping.ts
subgraphs/compound-forks/benqi/subgraph.yaml
subgraphs/compound-forks/iron-bank/src/mapping.ts
subgraphs/compound-forks/moonwell/src/mapping.ts
subgraphs/compound-forks/src/mapping.ts

> Using a derivedFrom field in the graph code gives no compile time issues but fails when the graph syncs with error unexpected null wasm
https://github.com/messari/subgraphs/blob/master/docs/Mapping.md#subgraph-issues
made this mistake again :(

fix handleNewLiquidationIncentive

---

subgraphs/inverse-finance/README.md
subgraphs/inverse-finance/src/common/helpers.ts

Commit f930dc474ad938888653e364db6409b7312694d3 fixed bugs in `MarketHourlySnapshot` and `MarketDailySnapshot` for item `cumulativeDepositUSD`, `cumulativeBorrowUSD`, and `cumulativeLiquidateUSD`. Values of the Market entity should be used but those of the protocol were used.
README.md was updated to bring information from the earlier specification at https://github.com/messari/subgraphs/blob/f96689a5db62de1238be0ef5a42b5a19d18eb315/subgraphs/inverse-finance/README.md#total-revenue-usd  & reflect the fact that fees from the Stablizer are included in protocol revenue.

Fixed bugs in market metrics; Updated README

---

subgraphs/compound-forks/aurigami/src/mapping.ts
subgraphs/compound-forks/banker-joe/src/mapping.ts
subgraphs/compound-forks/bastion-protocol/src/mapping.ts
subgraphs/compound-forks/benqi/src/mapping.ts
subgraphs/compound-forks/cream-finance/src/mapping.ts
subgraphs/compound-forks/iron-bank/src/mapping.ts
subgraphs/compound-forks/moonwell/src/mapping.ts
subgraphs/compound-forks/scream/src/mapping.ts
subgraphs/compound-forks/venus/src/mapping.ts

A number of compound-fork subgraphs have their cTokenAddr and underlyingTokenAddr swapped when creating MarketListedData. This PR fixes the bug.

fixed bug when creating MarketListedData for compound-forks

---

subgraphs/compound-forks/aurigami/src/mapping.ts
subgraphs/compound-forks/banker-joe/src/mapping.ts
subgraphs/compound-forks/bastion-protocol/src/mapping.ts
subgraphs/compound-forks/benqi/src/mapping.ts
subgraphs/compound-forks/cream-finance/src/mapping.ts
subgraphs/compound-forks/iron-bank/src/mapping.ts
subgraphs/compound-forks/moonwell/src/mapping.ts
subgraphs/compound-forks/scream/src/mapping.ts
subgraphs/compound-forks/src/mapping.ts
subgraphs/compound-forks/venus/src/mapping.ts

This PR refactors src/mapping.ts for compound-forks to make the handlers more generic (accepting necessary information as arguments to handler functions instead of from a particular Event object), following the discussion at https://github.com/messari/subgraphs/pull/263#issuecomment-1145430732 .
Two test runs are ongoing: https://thegraph.com/hosted-service/subgraph/tnkrxyz/aurigami and https://thegraph.com/hosted-service/subgraph/tnkrxyz/venus-subgraph (no errors so far).

Refactored to make compound-forks handlers more generic

---

subgraphs/abracadabra/src/mapping.ts

double deposit no withdraw
Proof: https://thegraph.com/hosted-service/subgraph/messari/abracadabra-money-ethereum?selected=playground
has no withdraws

Abracadabra Subgraph: Fix no withdraw bug

---

schema-lending-extended.graphql

- Having the type of the postion in the id is beneficial as it allows for quickly finding the latest open position of each type example code:
```
// Finds the open lending position or opens a new one 
export function getOrCreateLendingOpenPosition(marketId: string, accountId: string, event: ethereum.Event): Position {
let positionIdPrefix = `${accountId}-${marketId}-LENDER`;
let account = getOrCreateAccount(accountId, event);
for (let curr = 0; curr < account.openPositionCount; curr += 1) {
let op = account.openPositions.at(curr);
if (op.startsWith(positionIdPrefix)) {
return Position.load(op)!;
}
}
let count = 0;
for (let curr = 0; curr < account.closedPositionCount; curr += 1) {
let cp = account.closedPositions.at(curr);
if (cp.startsWith(positionIdPrefix)) {
count += 1;
}
}
let …
```

Schema Proposal: Add Side to Position ID, use BigInt for nonce;

---

dashboard/src/common/chartComponents/TableEvents.tsx

1.3.0 has `liquidatee` field typed as String, not Account

Fix Liquidation event table for Lending 1.3.0 schema

---

subgraphs/_reference_/src/common/tokens.ts
subgraphs/aave-v2-forks-ext/src/token.ts
subgraphs/aave-v2-forks/src/token.ts
subgraphs/abracadabra-ext/src/common/tokens.ts
subgraphs/abracadabra/src/common/tokens.ts
subgraphs/arrakis-finance/src/common/tokens.ts
subgraphs/compound-forks-ext/protocols/compound-v2/src/token.ts
subgraphs/compound-forks/protocols/compound-v2/src/token.ts
subgraphs/curve-finance/src/common/tokens.ts
subgraphs/ellipsis-finance/src/common/tokens.ts
subgraphs/gamma-strategies/src/common/tokens.ts
subgraphs/makerdao/src/common/tokens.ts
subgraphs/platypus-finance/src/common/tokens.ts

Fix: change unkown token decimals to 0. This prevents an out of bounds error when trying to convert a BigInt value to BigDecimal.
Note: Turn off deployments on this merge

Change unknown token decimals

---

deployment/deployment.json
subgraphs/compound-forks-ext/README.md
subgraphs/compound-forks-ext/protocols/compound-v2/src/mapping.ts
subgraphs/compound-forks-ext/protocols/rari-fuse/src/mappings.ts
subgraphs/compound-forks-ext/src/mapping.ts
subgraphs/compound-forks/README.md
subgraphs/compound-forks/protocols/compound-v2/src/mapping.ts
subgraphs/compound-forks/protocols/rari-fuse/src/mappings.ts
subgraphs/compound-forks/src/mapping.ts

Error: Sometimes the market hourly snapshot is not created where it is expected, so it does not populate with the correct data to prevent a null field error.
```
A non-deterministic fatal error occured at block 13380834: failed to process trigger: block #13380834 (0x8580…d7fe), transaction d754eb9700435134f365158b1c1e69a8846745ecd0edee3db8e6b0930491cb88: Entity MarketHourlySnapshot[0xfd3300a9a74b3250f1b2abc12b47611171910b07-453814]: missing value for non-nullable field `protocol` wasm backtrace: 0: 0x766c - <unknown>!generated/schema/MarketHourlySnapshot#save 1: 0x7b9e - <unknown>!src/mapping/updateMarketSnapshots 2: 0x88cf - <unknown>!src/mapping/_handleMint 3: 0x8952 - <unknown>!protocols/rari-fuse/src/mappings/handleMint
```
Fix: populate all of the non nullable fields in …

Rari Fuse: Prevent Hourly Snapshot error

---

subgraphs/openzeppelin-governor/protocols/angle-governance/src/governor.ts
subgraphs/openzeppelin-governor/protocols/code4rena-governance/config/templates/code4rena-governance.template.yaml
subgraphs/openzeppelin-governor/protocols/code4rena-governance/src/arena-governor.ts
subgraphs/openzeppelin-governor/protocols/ens-governance/src/ens-governor.ts
subgraphs/openzeppelin-governor/protocols/euler-governance/src/governance.ts
subgraphs/openzeppelin-governor/protocols/fei-governance/src/fei-dao.ts
subgraphs/openzeppelin-governor/protocols/hop-governance/src/hop-governor.ts
subgraphs/openzeppelin-governor/protocols/silo-governance/src/silo-governor.ts
subgraphs/openzeppelin-governor/protocols/truefi-governance/src/dao-governor.ts
subgraphs/openzeppelin-governor/protocols/unlock-governance/src/unlock-protocol-governor.ts
subgraphs/openzeppelin-governor/schema.graphql
subgraphs/openzeppelin-governor/src/handlers.ts

This PR aims to address several bugs / inconsistencies with the OZGovernor entities/subgraphs
**1. Handle ProposalExtended event** 
- Part of OZGovernor LateQuorumVoteExtensionSet extension
**2. Mix up of Timelock and Token address in governanceFramework creation [GOV-59]**(https://linear.app/messari/issue/GOV-59/fix-token-and-timelock-address-mix-up-in-subgraphs)
**3. Euler subgraph was failing due to a missing handler for `ProposalThresholdSet`**
**4. Unlock subgraph was failing due to not setting `proposalThreshold` which is required.**
- If no proposal threshold set, default it to 0?
**5. Capture both weighted and unweighted votes**
**6. Capture quorum, tokenHolder, delegate snapshot at proposal level on first vote**
```typescript
// On first vote, set state and quorum values
if …
```

[Gov] Fix issues with OZGovernor entities and subgraphs

---

subgraphs/platypus-finance/src/common/getters.ts
subgraphs/platypus-finance/src/common/metrics.ts

usageMetricsDailySnapshots: totalPoolCount.
Fixed: Total Pool Count is now updated for daily usage snapshots.
There are 26 pools in the protocol, including 3 which are now shifted to withdraw pools. Withdraw pool’s TVL is not counted towards protocol’s TVL.

fix: total pool count

---

deployment/deployment.json
subgraphs/aave-v2-forks/protocols/aave-v2/config/networks/avalanche/avalanche.json
subgraphs/aave-v2-forks/protocols/aave-v2/config/networks/ethereum/ethereum.json
subgraphs/aave-v2-forks/protocols/aave-v2/config/networks/polygon/polygon.json
subgraphs/aave-v2-forks/src/mapping.ts
subgraphs/aave-v2-forks/src/token.ts

I accidentally left grafting turned on for aave v2 `ethereum`, `polygon`, and `avalanche`...
So the `market.cumulativeLiquidateUSD` fix is not accurate for those deployments.
The fix is to redeploy only the mentioned subgraphs with grafting turned off. I made a few aesthetic changes in the main `/src` folder in order to trigger the deployments.

Aave V2: Fix Deployments

---

subgraphs/uniswap-forks/src/common/updateMetrics.ts

This PR aims to fix 2 issues:
Hourly and daily cumulative revenue values are only updated on Swap events, but snapshots might be created too on Mint/Burn.
It might happen that at during hour/day there are no swaps, but there are lp mints or burns. If this happens, we initialize a snapshot with a 0 cumulativeRevenue value (it would be updated on swap). Since there are no swaps during that hour it stays at 0.
We seem to be using protocol cumulative metrics for pool snaphots? I would assume we want pool cumulative metrics instead, since protocol cumulatives are tracked on the financials snapshots.

fix: uniswap-forks; pool snapshots cumulative values

---

subgraphs/uniswap-forks/protocols/apeswap/src/common/handlers/handleReward.ts
subgraphs/uniswap-forks/protocols/apeswap/src/common/handlers/handleRewardMini.ts
subgraphs/uniswap-forks/protocols/solarbeam/src/common/handlers/handleReward.ts
subgraphs/uniswap-forks/protocols/spookyswap/src/common/handlers/handleReward.ts
subgraphs/uniswap-forks/protocols/spookyswap/src/common/handlers/handleRewardV2.ts
subgraphs/uniswap-forks/protocols/sushiswap/src/common/handlers/handleReward.ts
subgraphs/uniswap-forks/protocols/sushiswap/src/common/handlers/handleRewardMini.ts
subgraphs/uniswap-forks/protocols/sushiswap/src/common/handlers/handleRewardV2.ts
subgraphs/uniswap-forks/protocols/trader-joe/src/common/handlers/handleRewardV2.ts
subgraphs/uniswap-forks/protocols/trader-joe/src/common/handlers/handleRewardV3.ts
subgraphs/uniswap-forks/protocols/vvs-finance/src/common/handlers/handleReward.ts

The assignment of the regular token analogue for the reward token field on the pool is incorrect as this field wants to RewardToken entity id. The reward token id has an additional suffix which makes it different.

Uniswap Forks - Used reward token getter in Masterchef handlers 

---

subgraphs/uniswap-forks/src/price/price.ts

`getTrackedVolumeUSD()` returns `[token0VolumeUSD, token1VolumeUSD, token01Average]`. As of now, if either token is not whitelisted, its volumeUSD will be 0. 
Pools made of a `non-whitelisted/whitelisted` input token pair get their `dailyVolumeByTokenUSD` and `hourlyVolumeByTokenUSD` values zeroed for the non-whitelisted token.
This is because we return a 0 volumeUSD if the token is not whitelisted.
In those cases we can default to the whitelisted token volumeUSD, since they should be really close in value in practice. 
An alternative, in case we prefer to keep the this out of the price module, and to make it explicit that the 0 volume means the token is not whitelisted, we could move this logic to [here](https://github.com/messari/subgraphs/blob/master/subgraphs/uniswap-forks/src/common/u …

Use whitelisted token volumeUSD for non-whitelisted token instead of 0

---

.husky/pre-commit

It seems we didn't need to get too smart with the pre-commit hook running the prettier.
`npx pretty-quick --staged` is smart enough to know which of the staged files it modifies, and stages them again after prettying.

fix: husky pre-commit hook

---

subgraphs/uniswap-v3/.gitignore
subgraphs/uniswap-v3/src/common/creators.ts

**Context**
There are some fields related to rewards emissions, and the price of the output token which are not applicable to Uniswap V3. There are no rewards emission for Uniswap V3, and because the protocol mints NFTs that represent positions, we do not price the OutputTokens (NFTs).
I am not sure why this happened, but when I force pushed in PR #778 I accidentally push no commits and then it just merged in. This is a redo of that PR.

fix(#minor); Uniswap V3; Removed unused fields from the liquidity pool entity - RE: PR 778

---

subgraphs/makerdao/protocols/makerdao/config/templates/makerdao.template.yaml
subgraphs/makerdao/src/mapping.ts
subgraphs/makerdao/subgraph.yaml

Makerdao deployment failed because improper upcasting of ethereum.Event to BuyGem/SellGem (to avoid having two separate handlers for the two events); refactored to use a function instead.
Added grafting to resume from failed block - 1

Fix (#minor); makerdao; fixed PSM deployment fail

---

subgraphs/convex-finance/src/Prices/index.ts
subgraphs/convex-finance/src/mappings/rewardMappings.ts
subgraphs/convex-finance/src/modules/Deposit.ts
subgraphs/convex-finance/src/modules/Rewards.ts
subgraphs/convex-finance/src/modules/Withdraw.ts

Disable `yearnLens` and `curveCalculation` in price lib for [crvTriCrypto](https://etherscan.io/address/0xca3d75ac011bf5ad07a98d02f18225f9bd9a6bdf) Token

Convex Finance: Fix spike in TVL

---

subgraphs/uniswap-forks/protocols/sushiswap/config/networks/bsc/bsc.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/networks/polygon/polygon.ts
subgraphs/uniswap-forks/protocols/sushiswap/src/common/constants.ts

Issue #612 
- The final things left from this issue are with Sushiswap BSC and Polygon. 
- The pricing was way off because the reference token was getting priced poorly on both. 
- Updated reference token and or stable oracle pools to improve pricing. 
- Polygon was using the wrong oracle pools, and BSC needed to use BNB as its reference token since Eth was low volume.

fix(#minor); uniswap forks; updated reference tokens and stable pools for Sushiswap BSC and Polygon - Issue #612

---

subgraphs/compound-forks/protocols/iron-bank/src/mapping.ts

Syncing deployment: https://okgraph.xyz/?q=0xbe1%2Firon-bank-subgraph-mainnet
See comments in code. This should fix both the totalBorrows as well as the TVL.
QA spec mentions a few other issues:
- latest events are months old: I don't think that's right, since events from subgraphs are very up-to-date, e.g. https://api.thegraph.com/subgraphs/id/QmR5xWsyobfRGoWUr5YJqm1mtuuHQ3egEgK1cnWodUgEoL/graphql?query=%7B%0A++borrows%28orderBy%3Atimestamp%2CorderDirection%3Adesc%29%7B%0A++++id%0A++++timestamp%0A++%7D%0A%7D
- totalPoolCount (40) more than ironbank dashboard (24): I believe ironbank simply picks certain pools to render :) we can hardcode the 24 pools in subgraphs and only index those markets, but I am not sure if we want to do that. Thoughts? @this-username-is-taken

fix(#patch); iron bank; skip bad ctoken

---

subgraphs/bancor-v3/src/constants.ts
subgraphs/bancor-v3/src/mapping.ts

Synced deployment https://okgraph.xyz/?q=0xbe1%2Fbancor-v3-mainnet is verified against my bancor-v3 script https://github.com/0xbe1/tvl.sh/tree/master/bancor-v3 which gives similar results as https://analytics.bancor.network/
---
BancorNetworkInfo offers a `tradeOutputBySourceAmount` method that I leverage to derive token price. If `tradeOutputBySourceAmount(ETH, DAI, 10000) == 5` then i can tell ETH price = $2000.
However, if `tradeOutputBySourceAmount(ETH, DAI, 10,000,000) = 10,000` we shouldn't assume ETH price = $1000, because a large swap causes large slippage.
Therefore, I fix the code s.t. when calling `tradeOutputBySourceAmount` I always pass in just 1 unit of token. For example, 10^18 for ETH, 10^6 for USDC.

fix(#patch); bancor v3; fix tvl calculation

---

subgraphs/balancer-forks/.gitignore
subgraphs/balancer-forks/README.md
subgraphs/balancer-forks/abis/balancer-v2/BalancerTokenAdmin.json
subgraphs/balancer-forks/protocols/balancer-v2/config/networks/arbitrum/arbitrum.json
subgraphs/balancer-forks/protocols/balancer-v2/config/networks/ethereum/ethereum.json
subgraphs/balancer-forks/protocols/balancer-v2/config/networks/polygon/polygon.json
subgraphs/balancer-forks/protocols/balancer-v2/config/templates/balancer.v2.template.yaml
subgraphs/balancer-forks/protocols/beethoven-x/config/networks/fantom/fantom.json
subgraphs/balancer-forks/protocols/beethoven-x/config/networks/optimism/optimism.json
subgraphs/balancer-forks/schema.graphql
subgraphs/balancer-forks/src/common/constants.mustache
subgraphs/balancer-forks/src/common/constants.ts
subgraphs/balancer-forks/src/common/initializers.ts
subgraphs/balancer-forks/src/common/masterchef/helpers.ts
subgraphs/balancer-forks/src/common/utils.ts
subgraphs/balancer-forks/src/mappings/balancerTokenAdminMappings.ts
subgraphs/balancer-forks/src/mappings/gaugeMappings.ts
subgraphs/balancer-forks/src/mappings/vaultMappings.ts
subgraphs/balancer-forks/src/modules/Rewards.ts
subgraphs/balancer-forks/src/modules/masterChefV2Rewards.ts
subgraphs/balancer-forks/subgraph.yaml

**Beethoven X Fantom is set to deploy on merging this PR. We should consider re-deploying all of Balancer V2 as well since the stakedOutputTokenAmount and rewardEmissions will be off.**
**Bug Fixes:**
- The calculation of the LiquidityPool stakedOutputTokenAmount field needed to be done in the updateFactoryRewards function. This way the staked token amount will be calculated properly for all gauges on all networks. Before it was only working for Balancer V2 on Ethereum.
- Needed to add an exception here as per Phoenix's request for registering tokens in vault mappings -> https://github.com/harsh9200/subgraphs/blob/Balancer-v2--Polygon-and-Arbitrium-support/subgraphs/balancer-forks/src/mappings/vaultMappings.ts#L47-L48
- Balancer emissions from the gauge controller were assumed to be …

fix/refactor(#major); Balancer Forks; Fix bugs with rewards fields, vault mappings, and Balancer Emissions.

---

subgraphs/uniswap-forks/src/common/creators.ts

**Context:** 
Cumulative revenues were missing in pool instantiation, so I set them to zero when the pool gets instantiated. I am not sure why this was not throwing any errors before (And did not recently - maybe its the graph node version), but now it is - as it should.

fix(#minor); Uniswap Forks; Added cumulative revenues to pool instantiation

---

subgraphs/uniswap-forks/configurations/configure.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/networks/bsc/bsc.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/networks/polygon/polygon.ts
subgraphs/uniswap-forks/src/common/constants.ts
subgraphs/uniswap-forks/subgraph.yaml

**Context**
Updated minimum liquidity for Sushiswap on polygon due to TVL errors, and updated stable oracle pools for Sushiswap on BSC for TVL issues as well. 
**Results:**
Issue #612 - Passed!
Sushiswap BSC and Polygon have already been re-deployed and validated.

fix(#minor); Sushiswap; Fixed reference token for BSC and stable pools for polygon

---

deployment/deployment.json
subgraphs/euler/src/common/constants.ts
subgraphs/euler/src/mappings/helpers.ts

It seems we were calculating the `depositToken<>outputToken` exchangeRate the other way around.
If `exchangeRate` is the amount of input tokens a full share of output tokens is worth, then it should be `total deposited input tokens / output token supply`. We were calculating the inverse instead. 
This was causing syncing errors becuase of eventually dividing by 0, when a pool is left empty.
I checked other protocols to see if it was our own particular way of calculating it, but no, it is wrong 😅 
Maple finance, for example, [does it right.](https://github.com/messari/subgraphs/blob/master/subgraphs/maple-finance/src/common/mappingHelpers/update/intervalUpdate.ts#L84)

fix(#patch): euler finance; fix market rate calculation & divide by 0

---

subgraphs/makerdao/protocols/makerdao/config/templates/makerdao.template.yaml
subgraphs/makerdao/src/common/constants.ts
subgraphs/makerdao/src/common/getters.ts
subgraphs/makerdao/src/common/helpers.ts
subgraphs/makerdao/src/mapping.ts

- fixed interest rates for snapshots. In current implementation, daily/hourly snapshots also point to the latest entry of the InterestRate entity. This PR fix this.
- updated subgraphVersion
- update grafting to QmXH7PVEVxKxGhnoJsafP3Mm5eBzRMuTxXJ5dCUuhr5qwF (https://api.thegraph.com/subgraphs/name/tnkrxyz/makerdao-ethereum)

Fix (#patch); makerdao; fixed interest rates for snapshots; updated grafting and subgraphVersion

---

subgraphs/uniswap-forks/protocols/sushiswap/config/networks/ethereum/ethereum.ts

**Context:** 
Sushiswap Ethereum had failed in deployment. It is unclear why this occurred since it booted itself back up with a TVL error. I blacklisted the token causing the error and re-deployed the subgraph with a graft.

fix (#minor); Sushiswap Ethereum; Blacklisted MIS token

---

subgraphs/uniswap-forks/protocols/solarbeam/config/networks/moonriver/moonriver.ts

**Context:**
Response to issue #547. The reward token emissions were much lower than expected. This was because the reward interval was set to block and not timestamp.

fix(#minor); Solarbeam; Updated reward interval

---

README.md
subgraphs/erc721-metadata/src/mappings/token.ts
subgraphs/erc721-metadata/subgraph.yaml

subgraph status (grafting from block `12715763`): https://okgraph.xyz/?q=messari%2Ferc721-metadata
- fixes stalled deployment at block `12715764`
- removed `nonFatalErrors` flag in `subgraph.yaml`
- added JSON object check for non-standard NFT attribute metadata
- faulty txn: https://etherscan.io/tx/0x14b62b53d227b2d5fd4c5e0fa0cefc0a8582d0662e2fe409657cddf549b44595
- faulty token uri: https://gateway.pinata.cloud/ipfs/QmTYvhY2B36MVRtFC6EtSmKQ5tLY7mKwxHcocEixDPmhPK/001%20-%20%E5%89%AF%E6%9C%AC%20%281%29.json
- reason: `attributes` array contained a `JSONValueKind.STRING` instead of an `JSONValueKind.OBJECT` of `trait_type` and `value`

fix(#patch) ERC721 Metadata; add JSON object check for non-standard NFT attribute metadata

---

subgraphs/uniswap-forks/protocols/sushiswap/config/networks/harmony/harmony.ts

**Context:**
Sushiswap TVL was lower than sushi analytics. I copied the stable pools from sushiswap subgraph, but they were named incorrectly, so I thought the reference token was ETH.

fix (#minor); Sushiswap Harmony; Updated Reference Token

---

subgraphs/openzeppelin-governor/protocols/angle-governance/src/angle.ts
subgraphs/openzeppelin-governor/protocols/angle-governance/src/governor.ts
subgraphs/openzeppelin-governor/protocols/code4rena-governance/src/arena-governor.ts
subgraphs/openzeppelin-governor/protocols/code4rena-governance/src/arena-token.ts
subgraphs/openzeppelin-governor/protocols/ens-governance/src/ens-governor.ts
subgraphs/openzeppelin-governor/protocols/ens-governance/src/ens-token.ts
subgraphs/openzeppelin-governor/protocols/euler-governance/src/eul.ts
subgraphs/openzeppelin-governor/protocols/euler-governance/src/governance.ts
subgraphs/openzeppelin-governor/protocols/fei-governance/src/fei-dao.ts
subgraphs/openzeppelin-governor/protocols/fei-governance/src/tribe.ts
subgraphs/openzeppelin-governor/protocols/hop-governance/src/hop-governor.ts
subgraphs/openzeppelin-governor/protocols/hop-governance/src/hop-token.ts
subgraphs/openzeppelin-governor/protocols/silo-governance/src/silo-governance-token.ts
subgraphs/openzeppelin-governor/protocols/silo-governance/src/silo-governor.ts
subgraphs/openzeppelin-governor/protocols/truefi-governance/src/dao-governor.ts
subgraphs/openzeppelin-governor/protocols/truefi-governance/src/stk-tru-token.ts
subgraphs/openzeppelin-governor/protocols/unlock-governance/src/unlock-discount-token-v-3.ts
subgraphs/openzeppelin-governor/protocols/unlock-governance/src/unlock-protocol-governor.ts
subgraphs/openzeppelin-governor/schema.graphql
subgraphs/openzeppelin-governor/src/handlers.ts
subgraphs/openzeppelin-governor/src/tokenHandlers.ts

Extends the OpenZeppelin Governance subgraphs to index daily snapshots of totalSupply, tokenHolders, totalDelegates and votes. 
Largely adapted from the `TokenDailySnapshot` entities used in the erc20 subgraph.
See this subgraph for an example of the output
https://thegraph.com/hosted-service/subgraph/danielkhoo/truefi-governance

[Gov] Daily snapshots of tokenHolders and votes, track totalTokenSupply

---

subgraphs/uniswap-forks/protocols/sushiswap/config/networks/harmony/harmony.ts
subgraphs/uniswap-forks/protocols/vvs-finance/config/networks/cronos/cronos.ts
subgraphs/uniswap-forks/src/common/rewards.ts

**Context:** 
The reward interval VVS Finance was set to NONE, but the reward interval is by block. This change does not actually impact the rewards emissions for VVS finance due to the way the rewards calculator was configured. Sushiswap Harmony was also incorrect - updated reward interval from NONE to TIMESTAMP. This will require a re-deployment.
**Fix:**

fix (#minor); VVS Finance; Changed reward interval from NONE to BLOCK

---

subgraphs/openzeppelin-governor/schema.graphql
subgraphs/openzeppelin-governor/src/tokenHandlers.ts

##Description
Our OZ daily snapshots mistakenly capture `totalDelegates` i.e. the all time count of delegates instead of the `currentDelegates` at time of snapshot

[GOV] fix(#patch); Capture current delegates instead of total delegates in OZ snapshot

---

README.md
deployment/deployment.dev.json
subgraphs/compound-forks/protocols/dforce/src/mapping.ts
subgraphs/compound-forks/protocols/rari-fuse/README.md
subgraphs/compound-forks/protocols/rari-fuse/config/networks/ethereum/ethereum.json
subgraphs/compound-forks/protocols/rari-fuse/src/constants.ts
subgraphs/compound-forks/protocols/rari-fuse/src/mappings.ts

$FLOAT price oracle was exploited at this transaction https://etherscan.io/tx/0x40db7bd89d2a3f7df2793ba4f5be9a2ca93463d6bb6af024e5cd1b73ff827248 and to fix this we use our own price oracle to get the price at that block. Increment the version to `1.1.4`
Testing: https://okgraph.xyz/?q=dmelotik%2Ffuse-mainnet

fix(#patch); rari fuse; FLOAT exploit

---

subgraphs/uniswap-v3/protocols/uniswap-v3/src/common/constants.ts
subgraphs/uniswap-v3/src/common/price/price.ts
subgraphs/uniswap-v3/src/mappings/core.ts

**Context:**
Usage metrics are pretty inconsistent with defillama. This is because the usage on the swaps are being recorded incorrectly. This PR fixes that by updating the user for usage metrics. Also, there is the remove of an unnecessary log in this PR.

patch(#minor); Uniswap V3; Updated usage metrics for swaps, and removed unnecessary log

---

deployment/deployment.dev.json
subgraphs/uniswap-forks/protocols/trader-joe/src/common/constants.ts
subgraphs/uniswap-forks/protocols/trader-joe/src/common/handlers/rewarderRate/rewardRateCalculator.ts
subgraphs/uniswap-forks/schema.graphql
subgraphs/uniswap-forks/src/common/masterchef/helpers.ts

I recently introduced a breaking change by adding a required field to MasterChef entity in the schema. This field was not being set before and makes grafting from a previous version impossible:
I've made the field optional, and when fetching the entity, if it is not set, it will be set and saved. This way we can still ensure it will always be present while making the schema compatible.
I've also updated the trader-joe version (the one I was trying to graft :D )

fix(#patch): uniswap-forks; fixed breaking change preventing grafts

---

.github/workflows/build-checker.yaml

**Actions:**
**Context:**
There had been some instances of the build checker workflow failing, because the Ubuntu VM used to execute the Github actions is case sensitive - Linux's file system is case sensitive. There are developers, like myself, developing on Mac OS which has a case insensitive file system (Windows is as well). Unfortunately, it is not feasible to just turn case sensitivity on or off since it is a property of the file system. 
Ideally, this type of check would be supported by Typescript Eslint libraries, but I have not found any libraries that support this sort of linting for case sensitivity. They do have it for javascript within `eslint-config-dependencies`. 
Another potential route was typescript compiler options. However, since subgraphs are written in AssemblyScript, …

fix (#minor); Build Checker Workflow Runner; Swap Ubuntu for Mac OS

---

docs/Mapping.md

Context:
Relate to PR https://github.com/messari/subgraphs/pull/1003 and https://github.com/messari/subgraphs/pull/1004
The protocol entity gets created at the beginning of indexing, and when you graft on top, even though you change the version, the protocol entity still displays the older version. This will happen unless the versions get reset in the protocol getters. This fix sets the version after each get.

docs(); Updated README to include comments on best practices for protocol version updates. 

---

deployment/deployment.json
subgraphs/uniswap-v3/protocols/uniswap-v3/src/common/constants.ts
subgraphs/uniswap-v3/src/common/getters.ts

Context:
Relate to PR #1003 
The protocol entity gets created at the beginning of indexing, and when you graft on top, even though you change the version, the protocol entity still displays the older version. This will happen unless the versions get reset in the protocol getters. This fix sets the version after each get.

patch(#minor); Uniswap V3; Updated protocol getter to update versions on get.

---

deployment/deployment.json
subgraphs/uniswap-forks/configurations/configure.ts
subgraphs/uniswap-forks/protocols/solarbeam/config/deployments/solarbeam-moonriver/configurations.ts
subgraphs/uniswap-forks/protocols/solarbeam/src/common/constants.ts

**Context:**
Response to issue #547.
Outputting 0 TVL
- Solarbeam Wrapped liquid staked KSM/xcKSM - 0x5568872bc43bae3757f697c0e1b241b62eddcc17
Needed to add xcKSM to the token whitelist.

fix (#minor); Solarbeam; Added xcksm to whitelist

---

deployment/deployment.json

Fix format issue for veledrome finance in `deployment.json` that is preventing usage of the deployment scripts

fix(); deployment; format fix

---

subgraphs/maple-finance/package.json
subgraphs/maple-finance/src/common/utils.ts

Maple finance build seems to be broken because of some mismatch between the graph-ts versions during build and defined in the project itself. This should fix it for now

fix(): updated maple-finance dependencies to fix build

---

subgraphs/maple-finance/README.md

Removed staking from `Total value locked` to just `Total Deposit Balance USD`. This is to make it more consistent with other lending protocols.

Updates to maple finance readme.md, correct total value locked calculation

---

subgraphs/.folderslintrc

A few subgraphs have been added since I opened #1035 which didn't follow the directory structure enforced by folderslint. I didn't rebase to last master before merge so I didn't catch it. This is currently making all CI to fail on all new branches.
To make the CI pipelines to pass while the issue at hand is resolved I've temporarily whitelisted these new dir structures. As soon as they are fixed I'll revert this change :)

fix(): temporarily whitelisted non-standard subgraph dir structures

---

deployment/deployment.json

The deployment.json structure was slightly changed during the time #976 was open, which broke the deployment scripts 😅

fix(): fixed radiant-capital deployment.json since it had the old structure

---

deployment/validation/validateDeploymentJson.js

**Context:**
Added tests on the deployment.json so that arguments that are not standard will trigger an error. It requirs a certain number of fields for the protocol, deployment, and version level data.

feat/fix (#minor); deployment; Added tests for valid fields

---

subgraphs/compound-forks/protocols/dforce/src/constants.ts

This PR fixes #939 by changing two constants ARBITRUM_BLOCKS_PER_YEAR and ARBITRUM_BLOCKS_PER_DAY to be equal to ETHEREUM_BLOCKS_PER_YEAR and ETHEREUM_BLOCKS_PER_YEAR. More details in https://github.com/messari/subgraphs/issues/939#issuecomment-1257291939

fix (#patch); dforce-arbitrum; fixed interest rates and rewardAPY

---

deployment/deployment.json

**Context:**
Venus and Radiant had their slugs and query ids mismatch the location on the hosted service. This PR fixes those. Additionally, Tornado Cash was nested inside LooksRare, so I fixed that as well.

fix(#minor); deployment.json; Fixed miscellaneous issues in the deployment.json file

---

deployment/deployment.json

**Context:**
Network for TC in deployment.json is `mainnet` and not `ethereum`

fix (#minor); Fix network for TC in deployment.json

---

deployment/deployment.json

**Context:**
Venus Protocol's query-id had 2 dashes when it should have had 1 between `venus` and `protocol`. This PR fixes that.

fix (#minor); Deployment Json; Fix venus query ID

---

deployment/deployment.json
subgraphs/truefi/src/entities/market.ts
subgraphs/truefi/src/utils/constants.ts

- Fixed inputTokenBalance to just use the value from `value()` contract call
- used the new value and outputTokenSupply to get exchangeRate "properly"
- used tvl for totalDepositBalanceUSD
- updated to 1.0.2
testing: https://okgraph.xyz/?q=dmelotik%2Ftruefi-ethereum

fix(#patch); truefi; decimals for input token balance

---

subgraphs/.eslintrc.json

**Context:**
Handling potentially null variables without assertions proved to be more difficult than expected for cases where the fields are optional. Requires the creation of another variable to bypass the assertion as seen below - otherwise it will still recognize the data type as { some-type | null}. While this is a rule we would ideally keep, @jaimehgb, @nemani, and I decided it's better to remove this rule and handle as we have been. There has been some discussion on improving the assertion functionality in this issue --> https://github.com/graphprotocol/graph-ts/pull/248

fix (#minor); subgraphs eslint; Turn off non-null assertion rule.

---

deployment/deployment.json
subgraphs/compound-forks/protocols/bastion-protocol/src/mapping.ts

Reward token reverting and causing incorrect output.
To override since we know the name and decimals of the token we hardcode it.
Testing: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmXoLTGo3w6f1EWShayjCka7aP8n6jV11jpBw2JHTrXJcA&tab=protocol

fix(#patch); bastion; reward token reverting

---

package.json
subgraphs/.eslintignore
subgraphs/.eslintrc.js

**Context:**
Added a .eslintignore to the subgraphs linter so that the build and generated files do not get linted. Because they are types generated by the codegen and build commands, we do not want to lint them according to our standards. 
Additionally, eslint was not using the tsconfig file from the same location as the eslintrc. This does not make linting with our standards as flexible as we want it to be. Updated the `eslintrc.json` to `eslintrs.js` so that we could use `__dirname` within the configurations to always use the tsconfig withing the subgraphs/ folder.

(#patch); Eslint; Added eslint ignore and updated eslintrc to apply tsconfig same directly

---

messari-cli/src/command-helpers/build/scriptGenerator.ts

**Context:**
I think it fits better to put in the src folder, also, having it out causes linting errors, because I am putting a typescript file in the main body of the project.

(#patch); CLI; Move the creation of the deployment.json context class to inside src.

---

deployment/deployment.json

**Context:**
Deployment.json updates.
The decentralized network for Sushiswap Arbitrum was supposed to be for Sushiswap Ethereum. Also, Gamma Strategies Optimism and Arbitrum were labeled as production subgraphs, however, we do not have deployments for them, so I have switched them to `dev`.

(#patch); Deployment.json; Fixed sushiswap ethereum, and gamma optimism/arbitrum

---

deployment/deployment.json
subgraphs/euler-finance/protocols/euler-finance/config/deployments/euler-finance-ethereum/configurations.json
subgraphs/euler-finance/src/common/constants.ts
subgraphs/euler-finance/src/common/getters.ts
subgraphs/euler-finance/src/mappings/handlers.ts
subgraphs/euler-finance/src/mappings/helpers.ts

Fix for euler "oneshot cancelled error" with minimal changes to current implementation.
The loop ` for (let i = 0; i < eulerViewMarkets.length; i += 1)` in `syncWithEulerGeneralView()` of src/mappings/helper.ts is where the error occurs, and my tests found that [these two lines](https://github.com/messari/subgraphs/blob/fe78e431045dd61c4524fc308b80864f0786852c/subgraphs/euler-finance/src/mappings/helpers.ts#L440-L441) are the last straw 
```
updateMarketDailyMetrics(block, market.id, BIGDECIMAL_ZERO);
updateMarketHourlyMetrics(block, market.id, BIGDECIMAL_ZERO);
```
I removed these two lines in the function by swtiching the order of function calls in handler functions. My test deployment of the fix is working: https://thegraph.com/hosted-service/subgraph/tnkrxyz/euler?version=pending&selec …

fix (#patch); euler-finance; fix for euler oneshot cancelled error

---

deployment/deployment.json

~As part of our governance subgraph ingestion we want to pull subgraph subgraph deployment info from a central location instead of hardcoding it. Adding a new section to the `dashboard/public/deployments.json` enables that.~
@this-username-is-taken does the additional section to this json break anything on subgraphs.messari.io? As far as I can tell it will just be ignored. I could also move it into a separate json if it make more sense
EDIT: After discussion with @this-username-is-taken and @steegecs, standardising reading of data from `https://github.com/messari/subgraphs/blob/master/deployment/deployment.json` instead.

[GOV] Add gov subgraphs to public deployments json

---

deployment/deployment.json
subgraphs/openzeppelin-governor/abis/ousd-governance/Governance.json
subgraphs/openzeppelin-governor/abis/ousd-governance/OgvStaking.json
subgraphs/openzeppelin-governor/abis/rarible-governance/RariGovernor.json
subgraphs/openzeppelin-governor/abis/rarible-governance/Staking.json
subgraphs/openzeppelin-governor/protocols/ousd-governance/config/deployments/ousd-governance-ethereum/configurations.json
subgraphs/openzeppelin-governor/protocols/ousd-governance/config/templates/ousd-governance.template.yaml
subgraphs/openzeppelin-governor/protocols/ousd-governance/src/Governance.ts
subgraphs/openzeppelin-governor/protocols/ousd-governance/src/OgvStaking.ts
subgraphs/openzeppelin-governor/protocols/rarible-governance/config/deployments/rarible-governance-ethereum/configurations.json
subgraphs/openzeppelin-governor/protocols/rarible-governance/config/templates/rarible-governance.template.yaml
subgraphs/openzeppelin-governor/protocols/rarible-governance/src/RariGovernor.ts
subgraphs/openzeppelin-governor/protocols/rarible-governance/src/Staking.ts
subgraphs/openzeppelin-governor/src/versions.ts

Extending OpenZeppelin Governor coverage to include two new DAOs Rarible and OUSD. 
https://thegraph.com/hosted-service/subgraph/danielkhoo/rarible-governance
https://thegraph.com/hosted-service/subgraph/danielkhoo/ousd-governance
Once the subgraphs are ready, the next phase is adding them to the `governor-service` ingestion

[GOV-329][GOV-330] Add OZGovernor subgraphs for Rarible and OUSD

---

.github/workflows/build-checker.yaml

Context:
Sometime the linter was not able to fetch the commit prior to the PR causing it to fail. This PR updates the changed file action to one that has worked better in the past.

fix(#patch); CI Linter; Fix changed files action 

---

.github/workflows/build-checker.yaml

When using the `all` files the linter fails when any file is removed, since it doesn't find it.

fix(#patch): lint action to only use added & modified files

---

.gitignore
deployment/deployment.json
subgraphs/uniswap-v3/configurations/configurations/interface.ts
subgraphs/uniswap-v3/package.json
subgraphs/uniswap-v3/protocols/uniswap-v3/config/deployments/uniswap-v3-arbitrum/configurations.ts
subgraphs/uniswap-v3/protocols/uniswap-v3/config/deployments/uniswap-v3-celo/configurations.ts
subgraphs/uniswap-v3/protocols/uniswap-v3/config/deployments/uniswap-v3-ethereum/configurations.ts
subgraphs/uniswap-v3/protocols/uniswap-v3/config/deployments/uniswap-v3-optimism/configurations.ts
subgraphs/uniswap-v3/protocols/uniswap-v3/config/deployments/uniswap-v3-polygon/configurations.ts
subgraphs/uniswap-v3/protocols/uniswap-v3/config/templates/uniswap.v3.template.yaml
subgraphs/uniswap-v3/protocols/uniswap-v3/src/common/constants.ts
subgraphs/uniswap-v3/schema.graphql
subgraphs/uniswap-v3/src/common/constants.ts
subgraphs/uniswap-v3/src/common/creators.ts
subgraphs/uniswap-v3/src/common/getters.ts
subgraphs/uniswap-v3/src/common/updateMetrics.ts
subgraphs/uniswap-v3/src/common/utils/backfill.ts
subgraphs/uniswap-v3/src/mappings/core.ts

**Context:**
We recently incorporated collect events into Uniswap V3 in attempt to fix TVL issues that were occurring in PR #1092. I made the change based on a PR the Uni team was using to address this issue.
After making these changes, however, we were getting negative token values. I have discovered that when incorporating both the `burn` and the `collect` events, tokens are being removed from liquidity pools, in a sense, twice. This is because the `amount0` and `amount1` emitted from the burn event do not refer to the actual amount of tokens leaving the liquidity pool, rather, it refers to an increasing balance of tokens owed to the user that can be collected.
`Burn` and `collect` are often emitted together, and with the same amounts, but this is not guaranteed, and the `burn` event …

fix(#minor); Uniswap V3; Updated to use Collect instead of burn. Also, configured to use deployment versions

---

subgraphs/euler-finance/protocols/euler-finance/config/templates/euler.template.yaml
subgraphs/euler-finance/src/mappings/handlers.ts
subgraphs/euler-finance/src/mappings/helpers.ts

This PR uses event.receipt to avoid having to roll back revenues for liquidations.
The diff is bit messed up. `getRepayForLiquidation` is not revised from `rollbackRevenue`, but a different function that gets ride of the need of rolling back.
Test deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/benqi?version=pending&selected=logs
https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/benqi&tab=protocol

feat (); euler-finance; used event.receipt

---

deployment/deployment.json
subgraphs/uniswap-forks/protocols/spookyswap/config/templates/spookyswap.template.yaml
subgraphs/uniswap-forks/protocols/spookyswap/src/common/handlers/handleRewardV2.ts

**Context:**
The references to the MasterChefV2 handlers needed to be updated. Just removed `V2` from the end since this caused the subgraphs to halt. The fix is currently being grafted at the Messari Spookyswap Fantom Hosted Service. 
Additionally, the pool addition events were not being emitted for some staking pools in MasterChefV2 before they were being deposited into. This caused issues, so I added some handling to getOrCreateMasterChefStakingPool.

fix(#patch); Spookyswap Fantom; Fixed references to masterchefV2 handlers in template

---

subgraphs/governor-alpha-bravo/protocols/reflexer-governance/src/GovernorBravo.ts

Reflexer governance proposal are created undefined values for `signatures` and `values`. This causes issues further down the pipeline as the target, calldata and signature lengths don't match. This PR adds a simple workaround to replace the undefined with empty values.

[GIN] Fix reflexer governance proposal with empty values and signatures

---

deployment/deployment.json
subgraphs/compound-forks/abis/venus/Comptroller.json
subgraphs/compound-forks/protocols/venus/config/deployments/venus-protocol-bsc/configurations.json
subgraphs/compound-forks/protocols/venus/config/templates/venus.template.yaml
subgraphs/compound-forks/protocols/venus/src/constants.ts
subgraphs/compound-forks/protocols/venus/src/mapping.ts
subgraphs/compound-forks/protocols/venus/src/rewards.ts
subgraphs/compound-forks/src/constants.ts

This PR has 2 purposes (they are split on separate commits):
- Fixes an issue with `ActionPaused` events:
- I had to change the Comptroller ABI to be able to use part of Venus specific functionality, and the project stopped building. It was because the ActionPaused event name differs in Venus from the original Compound contract.
- Adds XVS rewards.
- Each market is given a `reward speed`, that every time it changes emits an event. This determines the `market.rewardTokenEmissionsAmount` values.
- Every time that event or `AccrueInterest` are emitted, we'll recalculate the USD value of that `rewardTokenAmount`.
- To translate `reward speed` to yearly rewards I'm using the code in `rewards.ts` which was copied as is [from here](https://github.com/messari/subgraphs/blob/master/subgraphs/compou …

Venus rewards

---

deployment/deployment.json
package-lock.json
subgraphs/compound-forks/abis/iron-bank/BeethovenXPool.json
subgraphs/compound-forks/abis/iron-bank/BeethovenXVault.json
subgraphs/compound-forks/abis/iron-bank/StakingRewards.json
subgraphs/compound-forks/abis/iron-bank/StakingRewardsFactory.json
subgraphs/compound-forks/protocols/iron-bank/README.md
subgraphs/compound-forks/protocols/iron-bank/config/deployments/iron-bank-avalanche/configurations.json
subgraphs/compound-forks/protocols/iron-bank/config/deployments/iron-bank-ethereum/configurations.json
subgraphs/compound-forks/protocols/iron-bank/config/deployments/iron-bank-fantom/configurations.json
subgraphs/compound-forks/protocols/iron-bank/config/deployments/iron-bank-optimism/configurations.json
subgraphs/compound-forks/protocols/iron-bank/config/templates/iron-bank.template.yaml
subgraphs/compound-forks/protocols/iron-bank/src/constants.ts
subgraphs/compound-forks/protocols/iron-bank/src/mapping.ts
subgraphs/compound-forks/schema.graphql
subgraphs/compound-forks/src/constants.ts

This PR adds reward emission for iron-bank.
- Test deployment: [iron-bank optimism](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/iron-bank-optimism&tab=protocol)
Notes:
1. From what I see, iron-bank only has reward emission for optimism: https://docs.ib.xyz/v/optimism/ . veIB was used to be on Fantom, but was migrated to optimism (https://docs.ib.xyz/v/fantom/veib/veib-contract-address)
2. ~~I cannot find a working price oracle for the IB reward token on optimism. The reward factory was [deployed on optimism at block 12661952](https://optimistic.etherscan.io/address/0x35F70CE60f049A8c21721C53a1dFCcB5bF4a1Ea8#code), and none of the oracle in [our current price-lib](https://github.com/messari/subgraphs/tree/master/subgraphs/_reference_/src/pr …

feat (#patch); iron-bank; added reward emission

---

subgraphs/maker-governance/protocols/maker-governance/config/templates/maker-governance.template.yaml
subgraphs/maker-governance/protocols/maker-governance/src/ds-chief.ts
subgraphs/maker-governance/protocols/maker-governance/src/ds-spell.ts
subgraphs/maker-governance/schema.graphql

- Disable track on poll emitter contract (Maker has gone multi-chain so polling is better tracked with the Maker API instead of from the subgraph)
- Add fields to track `liftedBlock`, `scheduledBlock`, `castBlock`

[GIN-589] Disable poll tracking, add blocks for lifted, scheduled, cast

---

subgraphs/alpaca-finance-lending/schema.graphql

Add markets field into LendingProtocol schema to fix subgraph bot monitor error at  https://discord.com/channels/953684103012683796/1027699754437726321/1046985971071205427

fix(#patch): alpaca-finance-lending; add markets field into LendingProtocol schema

---

deployment/deployment.json
subgraphs/lido/protocols/lido/config/templates/lido.template.yaml
subgraphs/lido/src/entities/token.ts
subgraphs/lido/src/entityUpdates/financialMetrics.ts
subgraphs/lido/src/mappings/Lido.ts
subgraphs/lido/src/mappings/Oracle.ts

We were only updating snapshots when there was a mint of stETH. This only happens once every 24 hours, so hourly snapshots were only being created once daily.
Had to make some readjustments to the way we take snapshots in this subgraph and the times we update TVL and revenues:
- TVL was not being updated when a deposit was made, only on daily revenue mint. **Fixed this.**
- Snaphots are not updated as a whole. Only certain parts of it at a time (tvl alone, supply side revenue alone, total revenue alone, protocol revenue alone). Since revenue only increases every 24h, taking a snapshot before then would make 0 cumulative values on revenue on the hourly snapshots. **Added all the copying cumulative values on all snapshot taking functions.**
- Total revenue was calculated by observing mint …

fix(#patch): lido-ethereum; update snaphsots and tvl more often

---

deployment/deployment.json
subgraphs/compound-forks/abis/dforce/Comptroller.json
subgraphs/compound-forks/abis/dforce/RewardDistributor.json
subgraphs/compound-forks/protocols/bastion-protocol/src/mapping.ts
subgraphs/compound-forks/protocols/dforce/README.md
subgraphs/compound-forks/protocols/dforce/config/templates/dforce.template.yaml
subgraphs/compound-forks/protocols/dforce/src/constants.ts
subgraphs/compound-forks/protocols/dforce/src/mapping.ts

Reward arrays could be mismatched and were. We cannot allow this so this was updated.
Also refactored rewards to be more readable and update emissions with events.
Testing:
- arb: https://okgraph.xyz/?q=dmelotik%2Fdforce-arbitrum
- bsc: https://okgraph.xyz/?q=dmelotik%2Fdforce-bsc
- eth: https://okgraph.xyz/?q=dmelotik%2Fdforce-ethereum
- optimism: https://okgraph.xyz/?q=dmelotik%2Fdforce-optimism
- polygon: https://okgraph.xyz/?q=dmelotik%2Fdforce-polygon

fix(#patch); dForce; reward array mismatch

---

deployment/deployment.json

Moved this to `prod`, but it actually had not been deployed on Messari hosted. Going to move it back to `dev`, so subgraph monitor bot does not spam alerts about it

chore(); Belt Finance status back to dev

---

deployment/deployment.json
subgraphs/makerdao/protocols/makerdao/config/deployments/makerdao-ethereum/configurations.json
subgraphs/makerdao/src/mapping.ts

This fixes the unreasonable protocol side revenue for USDC-A liquidation reported by @bye43  in #1502
- Test deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/makerdao-ethereum?version=pending&selected=logs
- validation dashboard: https://api.thegraph.com/subgraphs/name/tnkrxyz/makerdao-ethereum/graphql?query=%7B%0A++marketDailySnapshots+%28orderBy%3A+dailyLiquidateUSD%2C+orderDirection%3Adesc%2C+where%3A+%7Btimestamp_gte%3A+1670284800%2C+timestamp_lte%3A+1670371199%7D%29+%7B%0A++++timestamp%0A++++market+%7B%0A++++++name%0A++++++id%0A++++%7D%0A++++dailyLiquidateUSD+%0A++++dailyProtocolSideRevenueUSD%0A++%7D++%0A%7D

fix(#patch); makerdao; fixed a bug when liquidationPenalty is set to 0

---

subgraphs/_reference_/src/sdk/protocols/bridge/account.ts

We broke down that field in the schema into two other fields and didn’t get updated in the SDK.

patch(): sdk; Fixed bridge sdk bug from schema change

---

subgraphs/_reference_/src/sdk/protocols/bridge/account.ts
subgraphs/_reference_/src/sdk/protocols/bridge/pool.ts
subgraphs/_reference_/src/sdk/protocols/bridge/tokens.ts

In tokens.ts, the argument for `getOrCreateToken` and `getTokenParams` is specified as type `Address`, but Token.id is specified as `Bytes` in the schema. This PR changes the argument type to `Bytes`.

fix (#patch); bridge sdk; fixed argument type for token

---

deployment/deployment.json
subgraphs/goldfinch/protocols/goldfinch/config/templates/goldfinch.template.yaml
subgraphs/goldfinch/schema.graphql
subgraphs/goldfinch/src/common/constants.ts
subgraphs/goldfinch/src/common/getters.ts
subgraphs/goldfinch/src/common/helpers.ts
subgraphs/goldfinch/src/common/log.ts
subgraphs/goldfinch/src/entities/market.ts
subgraphs/goldfinch/src/entities/senior_pool.ts
subgraphs/goldfinch/src/mappings/membership/capital_ledger.ts
subgraphs/goldfinch/src/mappings/membership/membership_collector.ts
subgraphs/goldfinch/src/mappings/senior_pool.ts
subgraphs/goldfinch/src/mappings/tranched_pool.ts

Added goldfinch membership rewards (staking of output ERC 720 tokens) #1499
- test deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/goldfinch-ethereum
- validation dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/goldfinch-ethereum

feat (#patch); goldfinch; added membership rewards

---

deployment/deployment.json
subgraphs/balancer-forks/src/common/initializers.ts

**Context:**
.save() implemented too early in the protocol getter. Must save at the end of the getter, otherwise the entity looks incomplete.

fix(#patch); Balancer Forks; Fix protocol getter

---

subgraphs/_reference_/src/sdk/protocols/bridge/account.ts

Added `messageOut` and `messageIn` method for Account and necessary helper functions to handle messages sent/received across the bridge managed by the bridge protocol.
Note that there are protocol.cumulativeUniqueMessageSenders, UsageMetric.cumulativeUniqueMessageSenders and daily/hourlyActiveMessageSenders, but not protocol.cumulativeUniqueMessageReceivers or UsageMetric.daily/hourlyActiveMessageReceivers in the schema. As [jaimehgb explains](https://discord.com/channels/953684103012683796/961658223444787220/1063578350985150545), that is because receiving a message is not done by an account per se, but by a contract.

feat (); bridge sdk; Added account methods messageOut and messageIn

---

deployment/deployment.json
schema-bridge.graphql
schema-dex-agg.graphql
schema-dex-amm-extended.graphql
schema-dex-amm.graphql
schema-generic.graphql
schema-lending.graphql
schema-network.graphql
schema-nft-marketplace.graphql
schema-yield.graphql
subgraphs/network/protocols/evm/config/deployments/evm-gnosis/configurations.json
subgraphs/network/schema.graphql
subgraphs/network/src/constants.ts
subgraphs/qidao/protocols/qidao/config/deployments/qidao-gnosis/configurations.json
subgraphs/qidao/protocols/qidao/config/templates/qidao.template.yaml
subgraphs/qidao/schema.graphql
subgraphs/qidao/src/utils/constants.ts
subgraphs/uniswap-forks/configurations/configurations/configurations.ts
subgraphs/uniswap-forks/protocols/honeyswap/config/deployments/honeyswap-gnosis/configurations.json
subgraphs/uniswap-forks/protocols/honeyswap/config/deployments/honeyswap-gnosis/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-gnosis/configurations.json
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-gnosis/configurations.ts
subgraphs/uniswap-forks/schema.graphql
subgraphs/uniswap-forks/src/common/constants.ts
subgraphs/uniswap-forks/src/common/rewards.ts

**Context:**
The Graph seems to be transitioning to referencing the Gnosis chain as Gnosis (prev xdai). In response, I have update the schemas to use the GNOSIS network in the namespace instead of XDAI. Also, we would like to update our current production subgraphs to follow this schema, so I have update those to conform.

fix(#patch); XDAI to Gnosis; Update schemas to use Gnosis instead of XDAI

---

deployment/deployment.json

Since our id's use Bytes and the Byte < > comparisons are only avail on the hosted service right now we need to avoid trying to query the decentralized network.
We will add this back in once the changes are persisted on the decentralized network.

chore(); remove comp v3 decentralized network

---

.github/workflows/build-checker.yaml
package.json

This PR adds an additional action to the CI to validate that subgraph files are formatted with `prettier`. If they are not, it will fail. Enforcing contributors to push the code already formatted.

feat; actions: Validate formatting

---

deployment/deployment.json
subgraphs/compound-v3/protocols/compound-v3/src/constants.ts
subgraphs/compound-v3/protocols/compound-v3/src/mapping.ts

With the addition of the new ethereum market the prices are returned in ETH, unfortunately there is nothing on chain identifying this so we need to hardcode in logic to get the ETH price to get the real TVL.
Test: https://okgraph.xyz/?q=dmelotik%2Fcompound-v3-ethereum

fix(#major); comp v3; ETH pricing

---

deployment/deployment.json
subgraphs/aave-forks/protocols/aave-amm/src/mapping.ts
subgraphs/aave-forks/protocols/aave-arc/src/mapping.ts
subgraphs/aave-forks/protocols/aave-rwa/src/mapping.ts
subgraphs/aave-forks/protocols/aave-v2/src/mapping.ts
subgraphs/aave-forks/protocols/aave-v3/src/mapping.ts
subgraphs/aave-forks/protocols/geist-finance/src/mapping.ts
subgraphs/aave-forks/protocols/radiant-capital/src/mapping.ts
subgraphs/aave-forks/protocols/uwu-lend/src/mapping.ts
subgraphs/aave-forks/src/mapping.ts

Liquidations were not properly mapped. Fixed:
- `liquidate.asset` is now the asset that is borrowed, not the collateral asset
- `liquidate.profitUSD` is now the difference between the amount seized and the amount of debt paid by the liquidator.
Test deployment: https://okgraph.xyz/?q=dmelotik%2Faave-v2-ethereum

fix(#minor); aave forks; fix liquidations

---

deployment/deployment.json
subgraphs/multichain/src/common/getters.ts

https://okgraph.xyz/?q=QmSoawPaM5fWFiSMH7yaGDwNprXXTwGoV3cv5JsebojWhn
`Pool.destinationTokens` is showing empty for multichain. Since destination tokens are linked to pool routes, whenever a new pool route is added to a pool, we’ll add the token too if not there already.

fix(#patch): multichain; add missing pool destination tokens

---

deployment/deployment.json
subgraphs/alpaca-finance-lending/protocols/alpaca-finance-lending/config/deployments/alpaca-finance-lending-fantom/configurations.json
subgraphs/alpaca-finance-lending/protocols/alpaca-finance-lending/config/templates/alpaca.finance.lending.template.yaml
subgraphs/alpaca-finance-lending/src/entities/market.ts
subgraphs/alpaca-finance-lending/src/entities/rate.ts
subgraphs/alpaca-finance-lending/src/entities/token.ts
subgraphs/alpaca-finance-lending/src/mappings/vault.ts

**Updated 2023/02/02**
- test deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/alpaca-finance-lending-bsc
- data validation: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/alpaca-finance-lending-bsc&tab=protocol
- test deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/alpaca-finance-lending-fantom
- data validation: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/alpaca-finance-lending-fantom&tab=protocol

feat (); alpaca-finance-lending-fantom; added configuration & deployment

---

subgraphs/_reference_/src/common/constants.ts
subgraphs/_reference_/src/prices/config/arbitrum.ts
subgraphs/_reference_/src/prices/config/aurora.ts
subgraphs/_reference_/src/prices/config/avalanche.ts
subgraphs/_reference_/src/prices/config/bsc.ts
subgraphs/_reference_/src/prices/config/cronos.ts
subgraphs/_reference_/src/prices/config/fantom.ts
subgraphs/_reference_/src/prices/config/fuse.ts
subgraphs/_reference_/src/prices/config/gnosis.ts
subgraphs/_reference_/src/prices/config/harmony.ts
subgraphs/_reference_/src/prices/config/mainnet.ts
subgraphs/_reference_/src/prices/config/moonbeam.ts
subgraphs/_reference_/src/prices/config/optimism.ts
subgraphs/_reference_/src/prices/config/polygon.ts
subgraphs/_reference_/src/sdk/util/constants.ts

Made all addresses in price-lib and SDK lowercase so that when using them in our subgraphs they don’t break the linter.

chore(): lint price-lib and sdk

---

deployment/deployment.json

Until Compound V2 is fully synced on the decentralized network we want to ingest data from the hosted service subgraph to reduce downtime.

chore(); comp v2; remove bad deployment ID

---

deployment/deployment.json

**Context:**
@yulesa requested to have a project tag within the deployment.json. The project tag encompasses all related subgraphs under the same organization. For example, Aave V2, Aave V3, Aave RWA, Aave AMM, Aave ARC, and Aave Governance will receive the project tag of `aave`. Balancer V2 and Beethoven X will receive the project tag of `balancer`. Osmosis DEX and Osmosis chain will receive a tag of `osmosis.` This will be used to reference subgraphs by a project category in protocol metrics so that you can view all of the different facets of Aave, for example.

feat(); deployment.json; Add project tag to the deployment.json

---

subgraphs/_reference_/src/sdk/protocols/bridge/tokens.ts

Having `Interface | null` doesn't seem to work well when left null. Instead, I added a default implementation for the TokenManager TokenPresaver that does nothing, and can be replaced with a custom one instead.

fix(#patch): Fix strange behavior with nullable interfaces on bridge sdk

---

deployment/deployment.json
subgraphs/makerdao/protocols/makerdao/config/deployments/makerdao-ethereum/configurations.json
subgraphs/makerdao/protocols/makerdao/config/templates/makerdao.template.yaml
subgraphs/makerdao/schema.graphql
subgraphs/makerdao/src/common/helpers.ts
subgraphs/makerdao/src/mapping.ts

This PR fixes inaccurate TVL/inputTokenBalance in maker markets, esp. ETH-A and ETH-B, as reported in #1695 . Basically, a refactoring I did to consolidate handlers causes liquidated collateral not removed from TVL. To fix this, I moved liquidatePosition call up to `Cat.Bite()` and `Dog.Bark()` when liquidation auction was first set up, from when liquidation auction ends (`handleFlipEndAuction()` and `handleClipTakeBid()`).
- test deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/makerdao-ethereum?version=pending&selected=logs
- validation dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmdWkF7LsHEq88hrMAMHdoCeNxLyzSqNZdd2qyHiCCpCXQ&tab=protocol

fix (#minor); makerdao; fixed inaccurate TVL

---

deployment/deployment.json
subgraphs/alpaca-finance-lending/src/entities/market.ts
subgraphs/alpaca-finance-lending/src/mappings/vault.ts

This PR fixes issue reported [here](https://github.com/messari/subgraphs/pull/1631#issuecomment-1419563809) and in #1766. The `changeMarketBorrowBalance` only updates the USD amount for each borrow/repay, not repricing the total borrow balance in the market, while `updateMarketTVL` reprices inputToken balance using the latest price for each deposit/withdraw. This causes the totalBorrowBalanceUSD much higher than TVL ($23M > $5.3M for the USDC market).
- Fantom deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/alpaca-finance-lending-fantom
- Fantom validation dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/alpaca-finance-lending-fantom&tab=protocol
- BSC deployment: 
- BSC validation:

fix (#minor); alpaca-finance-lending; fixed incorrect borrowbalanceUSD

---

deployment/deployment.json
subgraphs/makerdao/protocols/makerdao/config/deployments/makerdao-ethereum/configurations.json
subgraphs/makerdao/protocols/makerdao/config/templates/makerdao.template.yaml
subgraphs/makerdao/src/common/constants.ts
subgraphs/makerdao/src/mapping.ts

This fixes the issue in protocol side revenue (#1785) due to liquidity penalty using incorrect decimals for the Cat V1 contract.
- cat v1: https://etherscan.io/address/0x78f2c2af65126834c51822f56be0d7469d7a523e#code
- cat v2: https://etherscan.io/address/0xa5679C04fc3d9d8b0AaB1F0ab83555b301cA70Ea#code
- deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/makerdao-ethereum?version=pending
- validation dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmdN5XkS372qmKv1mDVq9SJZ68PsMb9YXrXRZS3Qha3Xfc&tab=protocol

fix (#minor); makerdao-ethereum; fixed procotoal side rev from wrong liquidation penality #1785

---

deployment/deployment.json
subgraphs/platypus-finance/src/common/getters.ts
subgraphs/saddle-finance/src/utils/price.ts

**Context:**
Fix subgraph as there was a backward compatibility break from when I upgraded the new CLI version. The fix was very simple. I just had to fix assertions for some non-required fields on the Token entity. There were a few instances where I just had. to check if the field existed because running another condition on the value. 
Second, I noticed in Platypus to null return values from the price lib were given a value of `1`. It makes more sense to set the price to 0 if no price is returned. It is possible that setting these null values to 1 could throw off our pricing if the actual cost of the token is much lower.

fix(#minor); Saddle && Platypus; Fix compatibility with the required fields from graph version update.

---

subgraphs/_reference_/src/sdk/protocols/bridge/account.ts
subgraphs/_reference_/src/sdk/protocols/bridge/tokens.ts

Changed the type from Address to Bytes in transferIn, transferOut, and transfer, and token addresses, so non-EVM address can be supported.

feat (); bridge sdk; support non-evm addresses for transfer and token

---

schema-derivatives-options.graphql

Some small changes to Options schema in order to compile and deploy related dopex subgraph.
1. Some changes are needed as the errors happening when compiling, deploying and running subgraphs otherwise.
2. Add PCV as the subgraph dashboard will complain it does not comply with generic schema otherwise.
3. Add two extra kinds of fee type to be same with Perp schema.
4. Modify some entry names to be compliant with naming convention.

feat(#minor): Fix Options schema problem happening during compilation and deployment

---

schema-derivatives-perpfutures.graphql

broke down open interest into Long Open interest and short open interest. The granular breakdown of the metrics makes it more useful for research. 
Open to discussion, will tag on GMX pull request and SDK pull request.

Fix(#minor); Breakdown open interest into Long and short open interest in Perp schema

---

deployment/deployment.json
subgraphs/makerdao/protocols/makerdao/config/deployments/makerdao-ethereum/configurations.json
subgraphs/makerdao/protocols/makerdao/config/templates/makerdao.template.yaml
subgraphs/makerdao/src/common/helpers.ts
subgraphs/makerdao/src/mapping.ts

This PR fixes crash of makerdao subgraph (#1855) due to negative borrower balance in the D3MHub because the subgraph didn't account for fees in D3MHub contract.
- deployment 1: https://thegraph.com/hosted-service/subgraph/tnkrxyz/makerdao-ethereum?version=pending (drafted from messari/makerdao-ethereum)
- deployment 2: https://thegraph.com/hosted-service/subgraph/tnkrxyz/test-subgraph (sync from scratch)
- dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmeVJZYjMnmL3KUQXAJjkFLLXFnnwhnz8SNxSj96fQ2A5y&tab=protocol

fix (#minor); makerdao-ethereum; fix crash due to negative position bal reported in #1855

---

deployment/deployment.json
subgraphs/rocket-pool/protocols/rocket-pool/config/deployments/rocket-pool-ethereum/configurations.json
subgraphs/rocket-pool/src/checkpoints/nodeUtilities.ts
subgraphs/rocket-pool/src/updaters/financialMetrics.ts

Rocket pool TVL fell.. HARD. This is not accurate. The subgraph is telling us there is no Ethereum in rocket pool. Our subgraph says there are no minipools, so our eth counter is not working.
The rocket pool official subgraph does have minipools, and we use the same code...
Test: https://okgraph.xyz/?q=dmelotik%2Frocket-pool-ethereum

fix(#minor); rpl; fix TVL fall

---

deployment/deployment.json

mark Pancakeswap V3 deployments as `prod`

chore(); update Pancakeswap V3 status

---

schema-derivatives-options.graphql

`VolumeUSD` currently refers to notional volume at pool level. This is the most relevant metric. in discussions from dopex it was suggested to add `collateralVolume` as an additional metric as it can also be tracked. it is a less relevant metric but makes our schema more comprehensive.

Feat(#minor); Added `collateralvolume` on options schema 

---

deployment/deployment.json
subgraphs/uniswap-v3-forks/abis/pancakeswap-v3/TickLens.json
subgraphs/uniswap-v3-forks/abis/uniswap-v3/TickLens.json
subgraphs/uniswap-v3-forks/protocols/pancakeswap-v3/config/templates/pancakeswapV3Template.yaml
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/templates/uniswapV3Template.yaml
subgraphs/uniswap-v3-forks/src/common/entities/tick.ts
subgraphs/uniswap-v3-forks/src/common/entities/token.ts
subgraphs/uniswap-v3-forks/src/common/utils/backfill.ts
subgraphs/uniswap-v3-forks/src/common/utils/utils.ts

**Context:**
The `liquidityGross` and `liquidityNet` values on the tick entities and the `totalLiquidity` value on the liquidity pool entities were incorrect for this network because there was a re-genesis of Optimism, and all previous data was lost. Because these values are usually tracked in an accumulating manner, this breaks the calculation for Optimism. This PR addresses this issue by running contract calls at the beginning of indexing to pull these liquidity values for each tick and updating the necessary fields before continuing with the regular indexing protocol. This was an adjustment to the backfill already done with the Optimism pools, and it should not impact the data of any other chain for Uniswap or Pancakeswap. 
**Changes:**
- Improved the performance of the exponentiation …

fix(#minor); Uniswap V3 Optimism; Instantiate ticks at re-genesis

---

deployment/deployment.json
subgraphs/axelar/README.md
subgraphs/axelar/protocols/axelar/config/deployments/axelar-arbitrum/configurations.json
subgraphs/axelar/protocols/axelar/config/deployments/axelar-avalanche/configurations.json
subgraphs/axelar/protocols/axelar/config/deployments/axelar-bsc/configurations.json
subgraphs/axelar/protocols/axelar/config/deployments/axelar-celo/configurations.json
subgraphs/axelar/protocols/axelar/config/deployments/axelar-ethereum/configurations.json
subgraphs/axelar/protocols/axelar/config/deployments/axelar-fantom/configurations.json
subgraphs/axelar/protocols/axelar/config/deployments/axelar-moonbeam/configurations.json
subgraphs/axelar/protocols/axelar/config/deployments/axelar-polygon/configurations.json
subgraphs/axelar/src/mappings.ts

This PR fixes the revenue issue found in the axelar QA (#2007 ), and the handle of non-evm src addresses in `handleContractCallApproved`.
- Test deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/axelar-ethereum?version=pending&selected=logs
- Dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmYqtQzyWSc5LPevXUesaw4bP5VzmK6QXVH98s1H9PeNaK&tab=protocol

fix (#patch); axelar; fixed revenue and non-evm address

---

deployment/deployment.json

There is an `arbitrum-one-bridge` and `arbitrum-bridge` deployment. Removing the later

chore(); Remove `arbitrum-bridge` from deployment.json

---

deployment/deployment.json
subgraphs/euler-finance/README.md
subgraphs/euler-finance/protocols/euler-finance/config/deployments/euler-finance-ethereum/configurations.json
subgraphs/euler-finance/protocols/euler-finance/config/templates/euler.template.yaml
subgraphs/euler-finance/src/common/constants.ts
subgraphs/euler-finance/src/mappings/handlers.ts
subgraphs/euler-finance/src/mappings/helpers.ts

This PR fixes a bug in Euler liquidation profit (#2037) and updates the reward emission (#1488). Since the euler contract is still paused as of April 27th, tvl is not updated.
- test deployment (indexing in progress): https://thegraph.com/hosted-service/subgraph/tnkrxyz/euler-finance-ethereum?version=pending
- dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://thegraph.com/hosted-service/subgraph/tnkrxyz/euler-finance-ethereum%3Fversion%3Dpending&tab=protocol
Note that the messari Euler subgraph ([hosted](https://subgraphs.messari.io/subgraph?endpoint=messari/euler-finance-ethereum&tab=protocol) and [decentralized](https://subgraphs.messari.io/subgraph?endpoint=https://gateway.thegraph.com/api/2b7eeacb471d383c093a79133a0a17a4/subgraphs/id/8cLf29KxAedWLVaEqjV8qKomdwwXQxjptBZF …

fix (#minor); euler-finance; fix liquidation profit, updated rewards

---

subgraphs/_eslint-rules/no-string-literals.js

Allowing usage of string literal in `ethereum.decode()` e.g. `ethereum.decode("address", log.data)`. Otherwise, we have to go through
```
const ADDRESS = "address";
ethereum.decode(ADDRESS, log.data);
```
and adds no more readability.

chore(); allowed string literal in ethereum.decode call

---

subgraphs/lido/schema.graphql
subgraphs/rocket-pool/schema.graphql
subgraphs/tornado-cash/schema.graphql

- Add additional GraphQL directives to various Generic Protocols subgraph schemas. These directives will be helpful to Messari's internal data ingestion. It also helps in identifying the type and nature of the affected entities.
Affected subgraphs: Lido, RocketPool, TornadoCash

Add directives to Generic Protocols

---

deployment/deployment.json
subgraphs/arrakis-finance/src/mappings/handlers/liquidityGauge.ts
subgraphs/arrakis-finance/src/mappings/helpers/liquidityGauge.ts

This PR fixes the issue with [reward emission with Arrakis-finance-polygon](https://github.com/messari/subgraphs/issues/1408#issuecomment-1530814542):
- added missing updateRewardData() call
- removed FAKE reward tokens (FAKECRV, FAKEWMATIC) - likely used for testing
- polygon deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/arrakis-finance-polygon?version=pending
- polygon dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmZwBbRLX1EgzutSmuRgrnyqUPjGb1uqNv6quPQJwYfjS7&tab=pool&poolId=
- optimism deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/arrakis-finance-optimism?version=pending
- optimism dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmauJTJPRJPUKUrbVYbddbk …

fix (#patch); arrakis-finance; fixed reward emissions #1408

---

subgraphs/compound-forks/protocols/banker-joe/README.md

Forgot to remove the fuse/admin fee from rari fuse when copying over the readme from Rari Fuse subgraph.
Fixed issue

chore(); fix banker joe readme

---

subgraphs/uniswap-v3-forks/schema.graphql

- The Position Snapshot should be tagged as a @snapshot instead of @regularPolling as the entities are immutable.

Update uniswap-v3-fork schema directive

---

deployment/deployment.json
subgraphs/uniswap-forks/protocols/apeswap/config/deployments/apeswap-bsc/configurations.ts
subgraphs/uniswap-forks/protocols/honeyswap/config/deployments/honeyswap-gnosis/configurations.ts
subgraphs/uniswap-forks/protocols/pangolin/config/templates/pangolin.template.yaml
subgraphs/uniswap-forks/protocols/quickswap/config/deployments/quickswap-polygon/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-arbitrum/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-avalanche/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-polygon/configurations.ts
subgraphs/uniswap-forks/protocols/trader-joe/src/common/handlers/handleRewarder.ts
subgraphs/uniswap-forks/src/price/price.ts

**Context:**
There are 2 issues out for subgraphs within the Uniswap Forks directory. These are #2145 and #2168. This PR addresses the issues covered here for the Uniswap Forks subgraphs. Below are the changes implemented:
**Changes:**
- Apeswap BSC: Blacklisted Mor StableCoin and NFTGirl tokens
- Quickswap Polygon: Blacklisted Drop and Flamingo tokens
- Trader Joe Avalanche - Fixed null value for creation of the _MasterChefRewarder that caused run-time error.
- Honeyswap Gnosis - Blacklisted Honey/hiveWATER Token LP, Giveth Test Giv, and Test HNY tokens.
- Added factory contract abi to subgraph template. 
- Sushiswap Arbitrum - Blacklist 5 tokens. 
- Sushiswap Avalanche - Blacklist Wrapped Memo
- Sushiswap Polygon - Remove blacklist for klima dao and toucan protocol token
- Fixed pricing …

fix(#minor); Uniswap Forks; Fix issues for Uniswap Forks from issues 2145 and 2168

---

deployment/deployment.json
subgraphs/multichain/protocols/multichain/config/deployments/multichain-gnosis/configurations.json
subgraphs/uniswap-v3-forks/protocols/sushiswap-v3/config/deployments/sushiswap-v3-gnosis/configurations.json

**Context:**
Arbitrum on the decentralized network is now live! We want to begin migrating our subgraphs from being deployed on Ethereum to Arbitrum.
This PR also includes the addition of Panacakeswap V3 and Sushiswap V3 to the decentralized network.

chore(); Arbitrum Migration; Migrate decentralized network subgraphs to Arbitrum

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/common/chartComponents/TableChart.tsx
dashboard/src/interfaces/tabs/PoolTabEntity.tsx
dashboard/src/interfaces/tabs/ProtocolTabEntity.tsx
dashboard/src/queries/bridge/schema.ts
dashboard/src/queries/dex/schema.ts
dashboard/src/queries/generic/schema.ts
dashboard/src/queries/lending/schema.ts
dashboard/src/queries/yield/schema.ts

> Note: schemas for options and perp subgraphs do not have field `blockNumber` in their snapshot entities, hence block column will not show in their tables.

feat(#minor); dashboard; add blocknumber to snapshot tables

---

dashboard/src/App.tsx
dashboard/src/common/utilComponents/DeploymentOverlayDropDown.tsx
dashboard/src/deployments/DeploymentsPage.tsx
dashboard/src/deployments/ProtocolSection.tsx

> Note: 
> Only decentralized deployments with `signalledTokens > 0` are considered to list.
> The deployments with no indexers, example [uniswap-v3-celo](https://thegraph.com/explorer/subgraphs/8cLf29KxAedWLVaEqjV8qKomdwwXQxjptBZFrqWNH5u2?view=Indexers&chain=arbitrum-one) will give `DEPLOYMENT ERROR ` on protocol page

fix(#patch); dashboard; fix decentralized deployments list on protocols page/deployments overlay dropdown

---

deployment/deployment.json
subgraphs/morpho/protocols/morpho-aave-v2/config/deployments/morpho-aave-v2-ethereum/configurations.json
subgraphs/morpho/protocols/morpho-aave-v2/config/templates/morpho.aave.v2.template.yaml
subgraphs/morpho/protocols/morpho-compound/config/deployments/morpho-compound-ethereum/configurations.json
subgraphs/morpho/protocols/morpho-compound/config/templates/morpho.compound.template.yaml
subgraphs/morpho/src/mapping/morpho-compound/comptroller.ts

Morpho deployments needed to be separated to ensure our BE assumptions were met.
We assume that each protocol has only 1 deployment of each network.
Fix: separate into 2 separate protocols in the `deployment.json`

chore(); morpho; fix deployment structure

---

subgraphs/_reference_/src/sdk/protocols/lending/account.ts
subgraphs/_reference_/src/sdk/protocols/lending/manager.ts
subgraphs/_reference_/src/sdk/protocols/lending/position.ts
subgraphs/_reference_/src/sdk/protocols/lending/snapshots.ts
subgraphs/_reference_/src/sdk/protocols/lending/token.ts

without this, i run into the following error during compilation:
```
stdout: ERROR TS2322: Type 'generated/schema/Position | null' is not assignable to type 'generated/schema/Position'.
this.position.isCollateral = isCollateral;
~~~~~~~~~~~~~
in src/sdk/position.ts(84,7)
ERROR TS2322: Type 'generated/schema/Position | null' is not assignable to type 'generated/schema/Position'.
this.position.save();
~~~~~~~~~~~~~
in src/sdk/position.ts(85,7)
ERROR TS2322: Type 'generated/schema/Position | null' is not assignable to type 'generated/schema/Position'.
this.position.isIsolated = isIsolated;
~~~~~~~~~~~~~
in src/sdk/position.ts(91,7)
ERROR TS2322: Type 'generated/schema/Position | null' is not assignable to type 'generated/schema/Position'.
this.position.save();
~~~~~~~~~~~~~
in …
```

fix: force nullability check on `this.position`

---

deployment/deployment.json
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-ethereum/configurations.ts

**Context:** 
X token is causing the TVL on Uniswap V3 Ethereum to be in the trillions. The purpose of this PR is to blacklist this token so that it can be grafted and fixed. 
Connect to issue #2299
https://api.thegraph.com/subgraphs/name/messari/uniswap-v3-ethereum/graphql?query=%7B%0A++liquidityPool+%28id%3A+%220x8e002692a1604fdde5cb21cdce4002dda9833496%22%29+%7B%0A++++name%0A++++id%0A++++totalValueLockedUSD%0A++++inputTokens+%7B%0A++++++id%0A++++++name%0A++++++lastPriceUSD%0A++++%7D%0A++%7D%0A%7D++

fix(#minor); Uniswap V3 Etheruem; Blacklist X token

---

subgraphs/aave-governance/src/handlers.ts

More Aave proposal data from ipfs are no longer consistently json, but a mix of json and markdown (string). Currently if the retrieved data isnt json we leave it blank. This changes falls back to saving it as a string.

fix(#minor); Aave Governance; Parse non-json proposal data 

---

deployment/deployment.json
subgraphs/aave-forks/protocols/aave-v2/src/mapping.ts

This PR fixes a bug for aave-v2 in handleReserveDataUpdated. When calling _handleReserveDataUpdated, the 4th argument should be `variableBorrowIndex`, but it was set to `variableBorrowRate`.

fix (#patch) aave-v2 bug incorrect argument in handleReserveDataUpdated

---

deployment/deployment.json
subgraphs/lido/README.md
subgraphs/lido/protocols/lido/config/templates/lido.template.yaml
subgraphs/lido/src/mappings/Lido.ts
subgraphs/lido/src/utils/constants.ts

Deployments,
- lido-ethereum (graft, block: 17590000): https://okgraph.xyz/?q=QmYVWJKizmhAFf9hi3t5qD1n36fJGwpd8ng57y7Zfs1ZBi
- lido-ethereum (complete): https://okgraph.xyz/?q=QmVRX9S5VCzovKdffLdP24LxXVCPe2THF9QTauc4EDc7JB

fix(#patch); lido; skip aragon voting in counting protocol revenue

---

deployment/deployment.json
subgraphs/_reference_/src/sdk/protocols/perpfutures/poolSnapshot.ts
subgraphs/level-finance/src/common/initializers.ts
subgraphs/level-finance/src/sdk/protocols/perpfutures/poolSnapshot.ts

- Error: Trying to overwrite immutable `LiquidityPoolHourlySnapshot` due to duplicate ids
- Cause: 
- `PoolHourlySnapshot`'s id is created using `pool._lastUpdateTimestamp`, which is internally updated everytime there is an update on pool entity's fields
- In the current implementation, `getOrCreatePool` is called inside handler `handleLogPoolAddition`, but no field of the pool is updated. This creates a `LiquidityPoolHourlySnapshot` object, but does not update `pool._lastUpdateTimestamp`, which causes indexer to fail in the following iteration.
- Fix: This unnecessary `getOrCreatePool` call can be removed with no impact
- Deployments:
- https://okgraph.xyz/?q=dhruv-chauhan%2Flevel-finance-bsc
- https://okgraph.xyz/?q=dhruv-chauhan%2Flevel-finance-arbitrum

fix(#patch); level-finance; remove unnecessary getOrCreatePool call

---

deployment/deployment.json
subgraphs/arrakis-finance/package.json
subgraphs/arrakis-finance/protocols/arrakis-finance/config/templates/arrakis.finance.template.yaml
subgraphs/arrakis-finance/src/mappings/handlers/liquidityGauge.ts

- Error: 
- `vaultContract.pool() failed for vault: 0x5ee3148bfc8b449b9e565178927b1a6028adc49a`
- Cause:
- Arrakis Finance team has been testing out V2 contracts privately.
- The vault in the log above is a V2 vault and does not have read method `pool`.
- V2 will have a different Vault Factory contract but a common Gauge Registry contract.
- Fix: 
- For now we will skip creating gauge for V2 vaults. We shall  add support for V2 as it's rolled out.
- Deployments:
- https://okgraph.xyz/?q=dhruv-chauhan%2Farrakis-finance-optimism
- https://okgraph.xyz/?q=dhruv-chauhan%2Farrakis-finance-polygon
- https://okgraph.xyz/?q=dhruv-chauhan%2Farrakis-finance-ethereum

fix(#patch); arrakis-finance; skip creating gauge for v2 pools

---

deployment/deployment.json
subgraphs/cbridge/protocols/cbridge/config/deployments/cbridge-gnosis/configurations.json
subgraphs/curve-finance/protocols/curve-finance/config/deployments/curve-finance-gnosis/configurations.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-xdai/configurations.json

**Context:**
All of the query IDs added to the deployment.json are for newly deployed subgraphs to the decentralized network. Additionally, some of the gnosis network references have been updated from xdai to gnosis to match the graph's deployment API.

chore(); Decentralized Network; Add new decentralized network Query IDs

---

deployment/deployment.json
subgraphs/bancor-v3/package-lock.json
subgraphs/bancor-v3/package.json
subgraphs/bancor-v3/src/constants.ts
subgraphs/bancor-v3/src/mapping.ts
subgraphs/bancor-v3/yarn.lock

- Issue: 
- [tradeOutputBySourceAmount](https://etherscan.io/address/0x8E303D296851B320e6a697bAcB979d13c9D6E760#readProxyContract#F25) call seems to be reverting, given `targetToken` as `DAI` address
- example log: 
`[getTokenPriceUSD] try_tradeOutputBySourceAmount(0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee, 0x6b175474e89094c44da98b954eedeac495271d0f, 1000000000000000000) reverted`
- Fix: Added `USDC` and `USDT` to be also considered as `targetToken`s for `tradeOutputBySourceAmount` call
- Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Fbancor-v3-ethereum
- Query: https://api.thegraph.com/subgraphs/id/QmYLawGQf6rdA7o9BfaT4zfutFN8xPxNGGiFZHmxwamiSu/graphql?query=%7B%0A++swaps+%28orderBy%3A+timestamp%2C+orderDirection%3Adesc%29+%7B%0A++++hash%0A++++tokenIn+%7B%0A++++++name%0A++++++id%0A++ …

fix(#patch); bancor-v3; add other possible stable target tokens for tradeOutputBySourceAmount

---

subgraphs/uniswap-forks-swap/protocols/pancakeswap-v2-swap/config/deployments/pancakeswap-v2-swap-bsc/configurations.json
subgraphs/uniswap-forks-swap/src/common/constants.ts
subgraphs/uniswap-forks-swap/src/common/creators.ts

- Issue: converting raw amount to token decimal terms fails 
- with error, `big decimal exponent 6145 is outside the -6143 to 6144 range`
- for token, https://bscscan.com/address/0x6a204b19b8273f346381B476BCAAd6B7b0D71fbd
- Fix: ignore swap events if token decimals out of range [-6143, 6144]
- Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Fpancakeswap-v2-swap

fix(#patch); pancakeswap-v2-swap; add check for token.decimals

---

subgraphs/maker-governance/protocols/maker-governance/src/ds-chief.ts

The correct progression for a maker proposal/spell is active->lifted->scheduled->cast. But a few older proposals were getting lifted after casting, resulting in the end state being inaccurate.

fix(#patch); Maker Governance; avoid lifting inactive spells

---

deployment/deployment.json
subgraphs/uniswap-forks-swap/src/common/constants.ts
subgraphs/uniswap-forks-swap/src/common/creators.ts
subgraphs/uniswap-forks-swap/src/common/getters.ts

- Issue: 
- Decimals for [token - CoinToken](https://bscscan.com/address/0xFBBd78a1Bf76E43D5FC8f1f880F72718040ACbE5) is set to `1370893090329243333764287979126883543363385161129`, which exceeds i32 range.
- Fix:
- While creating pair, check if `tokenContract.decimals.i32()`. If not, set decimals to MAX_INT32 and further ignore creating pair.
- Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Fpancakeswap-v2-swap

fix(#patch); pancakeswap-v2-swap; check if tokenContract.decimals return i32

---

deployment/deployment.json
subgraphs/aave-forks/protocols/spark-lend/config/deployments/spark-lend-gnosis/configurations.json
subgraphs/aave-forks/protocols/spark-lend/src/constants.ts
subgraphs/aave-forks/src/constants.ts
subgraphs/aave-forks/src/sdk/constants.ts

* Adds gnosis chain deployment of Spark Lend
* Renames xDAI to Gnosis constant (AFAIK it wasn't used anyway)
[Hosted service deployment](https://thegraph.com/hosted-service/subgraph/krzkaczor/spark-lend-gnosis)
[Sparklend Gnosis Deployment Info](https://github.com/marsfoundation/sparklend/pull/31/files#diff-41e7bb259a6845eb0ebd1ff79702654d67672ded6b28c8aff722d825120b229c)

Add spark-lend on gnosis

---

deployment/deployment.json
subgraphs/_reference_/src/sdk/util/arrays.ts
subgraphs/gmx-forks/protocols/gmx/config/deployments/gmx-arbitrum/configurations.json
subgraphs/gmx-forks/protocols/gmx/config/deployments/gmx-avalanche/configurations.json
subgraphs/gmx-forks/protocols/gmx/config/templates/gmx.template.yaml
subgraphs/gmx-forks/src/sdk/protocols/perpfutures/pool.ts
subgraphs/gmx-forks/src/sdk/util/arrays.ts

Deployments,
- gmx-arbitrum-graft (graft, block: 104485000): https://okgraph.xyz/?q=dhruv-chauhan%2Fgmx-arbitrum-graft
- gmx-arbitrum (complete): https://okgraph.xyz/?q=dhruv-chauhan%2Fgmx-arbitrum
Query,
https://api.thegraph.com/subgraphs/id/QmfYbKE9pBpXii8CYemccw9XdsDc2Hd3hDiFahpB1JBiit/graphql?query=%7B%0A++liquidityPoolDailySnapshots%28%0A++++first%3A5%2C%0A++++orderBy%3Adays%2C%0A++++orderDirection%3Adesc%2C%0A++++where%3A+%7B%0A++++++days_in%3A+%5B19533%2C19534%2C19535%5D%0A++++%7D%0A++%29%7B%0A++++days%0A++++inputTokens+%7B%0A++++++id%0A++++%7D%0A++++dailyVolumeByTokenUSD%0A++%7D%0A%7D

fix(#patch); gmx-forks; update subtractArrays method to handle uneven arrays

---

deployment/deployment.json
schema-derivatives-perpfutures.graphql
subgraphs/gains-trade/package.json
subgraphs/gains-trade/schema.graphql
subgraphs/gmx-forks/package.json
subgraphs/gmx-forks/schema.graphql
subgraphs/level-finance/package.json
subgraphs/level-finance/schema.graphql
subgraphs/mux-protocol/package.json
subgraphs/mux-protocol/schema.graphql

- Issue: 
- For Gmx, the following [query](https://api.thegraph.com/subgraphs/id/QmYa7FVFgxc2vsGRnvfbcdfU6Q4NXkTwCvPMn3VVnca14T/graphql?query=%7B%0A++positions%7B%0A++++liquidation%7Bid%7D%0A++%7D%0A%7D) fails with message: `"message": "Ambiguous result for derived field 'liquidation': Multiple 'Liquidate' entities refer back via 'position'"`
- Same is the case with mummy-finance, and level-finance.
- Fix:
- On tracing a position, we figured that a position can be partially liquidated multiple times, so the assumption in the schema that a position shall only point to one liquidation event is not true. (Trace: [position_logs.md](https://github.com/messari/subgraphs/files/13230701/position_logs.md))
- Since these liquidation events are getting created fine, it’s only the reference to the …

fix(); perps-schema; allow multiple liquidations per position

---

subgraphs/.eslintrc.js
subgraphs/_reference_/src/common/tokens.ts
subgraphs/_reference_/src/common/utils/datetime.ts
subgraphs/_reference_/src/common/utils/strings.ts
subgraphs/_reference_/src/prices/config/arbitrum.ts
subgraphs/_reference_/src/prices/config/aurora.ts
subgraphs/_reference_/src/prices/config/avalanche.ts
subgraphs/_reference_/src/prices/config/bsc.ts
subgraphs/_reference_/src/prices/config/celo.ts
subgraphs/_reference_/src/prices/config/cronos.ts
subgraphs/_reference_/src/prices/config/fantom.ts
subgraphs/_reference_/src/prices/config/fuse.ts
subgraphs/_reference_/src/prices/config/gnosis.ts
subgraphs/_reference_/src/prices/config/harmony.ts
subgraphs/_reference_/src/prices/config/moonbeam.ts
subgraphs/_reference_/src/prices/config/optimism.ts
subgraphs/_reference_/src/prices/config/polygon.ts
subgraphs/_reference_/src/prices/config/template.ts
subgraphs/_reference_/src/prices/routers/UniswapForksRouter.ts
subgraphs/_reference_/src/sdk/protocols/bridge/chainIds.ts

I am proposing to remove the magic number lint checker rule. We added this in to try and button up our code more.
However, magic numbers are needed in a lot of cases when building subgraphs (such as block numbers, pricing mechanisms, configs). And there are too many use edge cases to try and create a custom rule (we will always be one step behind).
We ended up just ignoring the rule too many time.

chore(); remove magic number checker

---

deployment/deployment.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-xdai/configurations.ts
subgraphs/hop-protocol/src/sdk/util/constants.ts
subgraphs/hop-protocol/src/sdk/util/rewards.ts

- Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-xdai-graft

fix(#patch); hop-protocol-xdai; add missing WMATIC_XDAI address

---

deployment/deployment.json
subgraphs/uniswap-forks-swap/protocols/uniswap-v2-swap/config/deployments/uniswap-v2-swap-ethereum/configurations.json
subgraphs/uniswap-forks-swap/protocols/uniswap-v2-swap/config/deployments/uniswap-v2-swap-ethereum/configurations.ts
subgraphs/uniswap-forks/protocols/uniswap-v2/config/deployments/uniswap-v2-ethereum/configurations.json
subgraphs/uniswap-forks/protocols/uniswap-v2/config/deployments/uniswap-v2-ethereum/configurations.ts

- Issue: uniswap-v2-ethereum / uniswap-v2-swap-ethereum deployments are failing with message: `overflow converting 0x... to i32` inside `getOrCreateToken()` method.
- This is due to [token](https://etherscan.io/address/0x000000000000B91B6956FEAD1dda24c66Aa6b972) with unverified ABI.
- Previously seen: https://github.com/messari/subgraphs/pull/2341
- Deployments:
- uniswap-v2-swap-ethereum: https://okgraph.xyz/?q=dhruv-chauhan%2Funiswap-v2-swap-ethereum
- uniswap-v2-ethereum: https://okgraph.xyz/?q=dhruv-chauhan%2Funiswap-v2-ethereum

fix(#patch); uniswap-v2-ethereum; add broken ERC20 tokens

---

subgraphs/abracadabra/package-lock.json
subgraphs/abracadabra/package.json
subgraphs/abracadabra/schema.graphql
subgraphs/abracadabra/src/common/constants.ts
subgraphs/abracadabra/src/common/getters.ts
subgraphs/abracadabra/src/common/metrics.ts
subgraphs/abracadabra/src/common/setters.ts
subgraphs/abracadabra/src/common/snapshots.ts
subgraphs/abracadabra/src/common/utils/utils.ts
subgraphs/abracadabra/src/mapping.ts
subgraphs/abracadabra/src/positions.ts

- Huge arrays in `abracadabra-money-avalanche` deployment causing issues for other subgraphs in the shard.
- As a [suggested storage optimization](https://docs.google.com/document/d/1xJif1OtgQl0hEEjtK1D71b7eGII_J0CT4Ibqj3RzfR8/edit), we looked to convert large arrays (length>50) as `@derivedFrom` mappings, but on querying it looks like the larger arrays already follow this convention, others do not need to due to very small length. [Reference query](https://api.thegraph.com/subgraphs/id/QmUjj4BbyeAEeBxFtgZeG7e4akyU29Y7fwe4utPN8qYNWX/graphql?query=%7B%0A++lendingProtocols%7B%0A++++mintedTokens%7Bid%7D%0A++++mintedTokenSupplies%0A++++marketIDList%0A++++%0A++++%23%23%23+derived%0A++++%23+dailyUsageMetrics%7Bid%7D%0A++++%23+hourlyUsageMetrics%7Bid%7D%0A++++%23+financialMetrics%7Bid%7D%0A++++%2 …

feat(#major); abracadabra; subgraph optimizations

---

deployment/deployment.json
subgraphs/compound-forks/abis/venus/ComptrollerV2.json
subgraphs/compound-forks/abis/venus/VTokenV2.json
subgraphs/compound-forks/package-lock.json
subgraphs/compound-forks/package.json
subgraphs/compound-forks/protocols/venus/config/deployments/venus-protocol-bsc/configurations.json
subgraphs/compound-forks/protocols/venus/config/templates/venus.template.yaml
subgraphs/compound-forks/protocols/venus/src/mapping.ts
subgraphs/compound-forks/src/mapping.ts

- Issues:
- missing markets
- deposits not being recorded
- These issues are due to updated implementations for proxy Comproller and VToken equivalent contracts.
- Deployments:
- (grafted) https://okgraph.xyz/?q=dhruv-chauhan%2Fvenus-protocol-bsc
- (complete) https://okgraph.xyz/?q=dhruv-chauhan%2Fvenus-protocol-bsc-2
- Note:
- grafted deployment fixed missing markets, lists new markets for UNI and FDUSD and records deposit events for them
- for capturing mint (deposit) events older markets like BTC, we will have to wait for complete syncing

fix(#patch); venus; handle proxy contracts update

---

deployment/deployment.json
subgraphs/goldfinch/protocols/goldfinch/config/deployments/goldfinch-ethereum/configurations.json
subgraphs/goldfinch/src/entities/tranched_pool.ts

- Issue: `assert(PoolToken.load(poolTokenIds[i]))` fails since some PoolToken was removed from store [here](https://github.com/messari/subgraphs/blob/master/subgraphs/goldfinch/src/mappings/pool_tokens.ts#L25) on `TokenBurned`. `tranchedPool.tokens` stores reference to PoolToken. Iterating over this array in code still shows the removed token Id.
- Previously seen: https://github.com/messari/subgraphs/pull/2369
- Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Fgoldfinch-ethereum

fix(#patch); goldfinch; failing assert on burned PoolToken

---

deployment/deployment.json
subgraphs/uniswap-v3-forks-swap/protocols/uniswap-v3-swap/config/deployments/uniswap-v3-swap-optimism/configurations.json
subgraphs/uniswap-v3-forks-swap/protocols/uniswap-v3-swap/config/deployments/uniswap-v3-swap-optimism/configurations.ts
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-arbitrum/configurations.json
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-arbitrum/configurations.ts
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-optimism/configurations.json
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-optimism/configurations.ts
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-polygon/configurations.json
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-polygon/configurations.ts

- Issue: uniswap-v3 / uniswap-v3-swap deployments are failing with message: `overflow converting 0x... to i32` inside `getOrCreateToken()` method.
- This is due to tokens with unverified ABIs
- Arbitrum: [token](https://arbiscan.io/address/0x000000000000b91b6956fead1dda24c66aa6b972) and [token](https://arbiscan.io/address/0x0000000000e586517bccb5ec52e70119299d2c9c)
- Polygon: [token](https://polygonscan.com/address/0x000000000000b91b6956fead1dda24c66aa6b972) and [token](https://polygonscan.com/address/0x0000000000e586517bccb5ec52e70119299d2c9c)
- Optimism: [token](https://optimistic.etherscan.io/address/0x000000000000b91b6956fead1dda24c66aa6b972) and [token](https://optimistic.etherscan.io/address/0x0000000000e586517bccb5ec52e70119299d2c9c)
- Previously seen: #2341 & #2445 
- Deployments: …

fix(#patch); uniswap-v3; failed deployment for tokens with unverified ABI

---

deployment/deployment.json
subgraphs/eigenlayer/src/common/events.ts
subgraphs/eigenlayer/src/mappings/handlers.ts

Fixes #2485
Fix: indexing of withdrawals containing multiple tokens
Before fix [query](https://api.thegraph.com/subgraphs/name/messari/eigenlayer-ethereum/graphql?query=query+MyQuery+%7B++%0A++withdraws%28%0A++++where%3A+%7Bwithdrawer%3A+%220x991c468AbcE2b4DD627a6210C145373EbABdd186%22%2C+nonce%3A+3%7D%0A++%29+%7B%0A++++token+%7B%0A++++++symbol%0A++++%7D%0A++++hash%0A++++nonce%0A++++blockNumber%0A++++completed%0A++++hashCompleted%0A++++blockNumberCompleted%0A++%7D%0A%7D#):
After fix [query](https://query.thegraph.kiln.fi/subgraphs/name/eigenlayer-test/graphql?query=query+MyQuery+%7B%0A++_meta+%7B%0A++++block+%7B%0A++++++number%0A++++%7D%0A++++deployment%0A++%7D%0A++withdraws%28%0A++++where%3A+%7Bwithdrawer%3A+%220x991c468AbcE2b4DD627a6210C145373EbABdd186%22%2C+nonce%3A+3%7D%0A++%29+%7B%0A+ …

fix(#major); eigenlayer; index completed withdrawals of multiple tokens

---

deployment/deployment.json
subgraphs/friend-tech/package-lock.json
subgraphs/friend-tech/package.json
subgraphs/friend-tech/schema.graphql
subgraphs/friend-tech/src/common/events.ts
subgraphs/friend-tech/src/common/getters.ts
subgraphs/friend-tech/src/common/metrics.ts
subgraphs/friend-tech/src/mappings/handlers.ts

- Huge arrays in `friend-tech-base` deployment causing issues for other subgraphs in the shard.
- These arrays were primarily defined to link `Trade` directly to `Account` entity and vice-versa. However, this can also be accessed using through a mapping table - `Connection`. 
Other arrays are either defined as derivedFrom fields or their lengths are bound by input tokens length.
- Test deployment: https://thegraph.com/studio/subgraph/friend-tech-base/
(Getting some graph-node error when trying to deploy on hosted service, checking with graph team and update)

feat(#major); friend-tech; subgraph optimizations

---

deployment/deployment.json

In the internal Messari Subgraph service, we only sync subgraphs marked as "prod" to our internal Snowflake. Bumping spookyswap-fantom to prod to enable this sync.

chore(); bump spookyswap-fantom from dev to prod

---

deployment/deployment.json
subgraphs/uniswap-v3-forks-swap/protocols/uniswap-v3-swap/config/deployments/uniswap-v3-swap-optimism/configurations.json
subgraphs/uniswap-v3-forks-swap/protocols/uniswap-v3-swap/config/deployments/uniswap-v3-swap-optimism/configurations.ts
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-arbitrum/configurations.json
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-arbitrum/configurations.ts
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-bsc/configurations.json
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-bsc/configurations.ts
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-ethereum/configurations.json
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-ethereum/configurations.ts
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-optimism/configurations.json
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-optimism/configurations.ts
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-polygon/configurations.json
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-polygon/configurations.ts

- Issue: uniswap-v3 / uniswap-v3-swap deployments are failing with message: `overflow converting 0x... to i32` inside `getOrCreateToken()` method due to bad decimal value returned. The ABI for the token contract is unverified.
- Previously seen: #2470, #2341 & #2445 
- Deployed to Messari hosted service, will take some considerable time to graft:
- uniswap-v3-arbitrum: https://okgraph.xyz/?q=messari%2Funiswap-v3-arbitrum
- uniswap-v3-bsc: https://okgraph.xyz/?q=messari%2Funiswap-v3-bsc
- uniswap-v3-ethereum: https://okgraph.xyz/?q=messari%2Funiswap-v3-ethereum
- uniswap-v3-optimism: https://okgraph.xyz/?q=messari%2Funiswap-v3-optimism
- uniswap-v3-polygon: https://okgraph.xyz/?q=messari%2Funiswap-v3-polygon
- uniswap-v3-swap-optimism: …

fix(#patch); uniswap-v3; indexing error due to token with unverified ABI

---

deployment/deployment.json
subgraphs/aave-forks/protocols/aave-v3/config/templates/aave.v3.template.yaml
subgraphs/aave-forks/protocols/aave-v3/src/constants.ts
subgraphs/aave-forks/protocols/aave-v3/src/mapping.ts
subgraphs/aave-forks/protocols/spark-lend/config/templates/spark.lend.template.yaml
subgraphs/aave-forks/protocols/spark-lend/src/constants.ts
subgraphs/aave-forks/protocols/spark-lend/src/mapping.ts
subgraphs/aave-forks/src/mapping.ts

```
// Earlier, 
liquidationProtocolFee = liquidationPenalty * liquidationProtocolFeePercentage * liquidatedCollateralAmount / (1 + liquidationPenalty - liquidationPenalty*liquidationProtocolFeePercentage)
// Changed,
// From the BalanceTransfer events sent on LiquidationCall https://github.com/aave/aave-v3-core/blob/724a9ef43adf139437ba87dcbab63462394d4601/contracts/protocol/tokenization/AToken.sol#L117
liquidationProtocolFee = balanceTransfer.value * (balanceTransfer.param_index / 10^27)
```
Test deployments,
- aave-v3-ethereum: https://okgraph.xyz/?q=dhruv-chauhan%2Faave-v3-ethereum-2
- spark-lend-ethereum: https://okgraph.xyz/?q=dhruv-chauhan%2Fspark-lend-ethereum-2

fix(#patch); aave-v3-forks; fix liquidation protocol fee calculation

---

deployment/deployment.json
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-base/configurations.ts

This PR Blacklists a set of 5 tokens that are currently throwing off the TVL in the Uniswap V3 Base subgraph

[DAT-2579]; Uniswap V3 Base; Blacklist Some Tokens To Fix TVL

---

deployment/deployment.json
subgraphs/aave-forks/src/mapping.ts
subgraphs/curve-finance/abis/Pool.json
subgraphs/curve-finance/package-lock.json
subgraphs/curve-finance/package.json
subgraphs/curve-finance/protocols/curve-finance/config/templates/curve.template.yaml
subgraphs/curve-finance/src/mappings/poolMappings.ts
subgraphs/curve-finance/src/prices/config/mainnet.ts

Fixes: #2457
- Linear Issue: [DAT-2538](https://linear.app/messari/issue/DAT-2538/fix-curve-eth-subgraph)
- Deployment: https://thegraph.com/hosted-service/subgraph/harsh9200/curve-finance-ethereum

feat(#minor); Curve Finance ETH; Address spike in TVL and missing volume for few pools

---

monitor/Dockerfile

**Context:**
We can safely remove `apt update && apt upgrade --yes`. We don't need to further update packages, they'll be recent on node:20. This change is in an attempt to resolve build error in subgraph monitor deployment

[DAT-2640]; Remove apt update & upgrade from monitor dockerfile

---

deployment/deployment.json

**Context:**
The subgraph studio UI was being pretty buggy, and I thought that some of the deployments got messed up so I incremented the versions. No changes are actually indicated by these version updates, but they will keep the deployment.json up to date with the Arbitrum DN deployments.

[DAT-2663]; Update versions in deployment.json per DN deployment

---

dashboard/Dockerfile

**Context:**
We want to see if pushing through an update of the node version to node:20 will resolve the security vulnerability issues we are facing in the subgraph monitor. 
The Dashboard is still up and functional after this update when run locally with docker as shown in the images below.

[DAT-2562]; Update node version to address security vulnerability

---

dashboard/package.json
dashboard/src/common/chartComponents/TableChart.tsx
dashboard/src/common/utilComponents/DatePicker.tsx
dashboard/src/common/utilComponents/DateRangePicker.tsx
dashboard/yarn.lock

**Context:**
This PR makes 5 main changes:
1. Ran `yarn upgrade` to update all packages to address vulnerabilities
2. Installed newest react-dom to resolve module import error after upgrade
3. Added types in the DatePicker files where necessary to resolve errors
4. Handle error in the sorting functionality on TableCharts.
5. Update GH-Pages package to version 5.0.0 to address vulnerability.
The app was breaking, but now it logs this error due to fix 4. The feature still works fine, but sometimes you have to click twice to get sorting on the TableCharts to work.

[DAT-2562]; Update all yarn packages, upgrade react-dom package, resolve type errors

---

deployment/produce_decentralized_network_csv.py

**Context:**
Received some recent requests to produce a CSV of our decentralized network deployments. Just pushing this script so that its saved and can be used to produce again in the future. 
https://linear.app/messari/issue/DAT-2798/provide-a-list-of-decentralized-network-deployments-to-the-graph

[DAT-2798]; Add script to produce decentralized network deployment csv

---

deployment/deployment.json
subgraphs/lido/protocols/lido/config/deployments/lido-ethereum/configurations.json
subgraphs/lido/src/mappings/Lido.ts

- In Lido V2 (after withdrawals were activated), reward distribution to nodes was changed (earlier directly, now via the node registry). In the early migration phase, rewards appear to be distributed in both ways. The subgraph had an if/else switch that did not account for this overlap.
- Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Flido-ethereum

fix(#patch); lido; Fix protocol side revenue

---

deployment/deployment.json
subgraphs/ellipsis-finance/src/common/constants.ts
subgraphs/ellipsis-finance/src/common/initializers.ts
subgraphs/uniswap-forks/protocols/ubeswap/config/deployments/ubeswap-celo/configurations.json

The purpose of this PR is to:
1. Deploy new subgraphs to the decentralized network and add query IDs to the deployment.json
2. Make other corresponding changes to updating OOS decentralized network deployments.
- Mantle Staked Ethereum
- Moonwell Base
- Seamless
- Morpho Aave V3 Ethereum
- Etherfi
- Puffer Swell Liquid Staking
- Stader
- Frax Ether Staking
- Add query ids for new decentralized network deployments to the deployment.json
- Update Ubeswap Celo to set graft = false to fix DN deployment
- Update ellipsis finance to have versions propagated from the deployment.json
- Update version for TC Ethereum, Aave V3 Base, Compound V3 Base, and Ellipsis BSC to fix bug in DN deployment.

[DAT-2888] Deploy Subgraphs To Decentralized Network

---

subgraphs/_reference_/src/prices/common/utils.ts
subgraphs/_reference_/src/prices/config/blast.ts

Add Pricing Support For Blast Network In the subgraph price lib.

feat(#minor); Price Lib; Add blast network 

---

dashboard/src/App.tsx

**Context:**
There was some instability yesterday in the subgraphs.xyz dashboard. It was caused from an object that failed to be loaded in. This PR just adds some conditional logic on reading the object to improve future stability even though the issue has now resolved iteself

Add conditional logic to handle invalid object causing instability

---

deployment/deployment.json
subgraphs/uniswap-forks-swap/protocols/pancakeswap-v2-swap/config/deployments/pancakeswap-v2-swap-bsc/configurations.json
subgraphs/uniswap-forks-swap/protocols/pancakeswap-v2-swap/config/deployments/pancakeswap-v2-swap-bsc/configurations.ts

- Issues: 
- pancakeswap-v2-swap-bsc deployment is failing with messages: 
- `overflow converting 0xa9f551de0f330654f37bcd89128d8828e4f820f000 to i32` inside `getOrCreateToken()` method. 
This is due to [token](https://bscscan.com/address/0xFBBd78a1Bf76E43D5FC8f1f880F72718040ACbE5#readContract) with it's decimals = `1370893090329243333764287979126883543363385161129` which overflows i32 when trying to bind the token to an ERC20 abi.
- `overflow converting 0x000064a7b3b6e00d to i32`, due to unverified [token](https://bscscan.com/address/0x5285d9d9f784bce2aA7b82CF318D632d423C1047#code) contract.
- Another similar occurance at tx: https://bscscan.com/tx/0x6580a2c83d60ef7794896c4f11a37ecabbc7871d0a98ed1ed1c4346f04f90d5d, due to unverified token contract: …

fix(#patch); pancakeswap-v2-swap-bsc; add broken ERC20 tokens

---

subgraphs/erc20/src/mappings/token.ts

@nemani @dhruv-chauhan @melotik 
Fix: `currentHolderCount` value turns negative for some tokens.
Eg. arbitrum (0x9e20461bc2c4c980f62f1B279D71734207a6A356)
Before fix:
After fix:

fix(#patch); currentHolderCount in erc20 subgraph

---

dashboard/src/App.tsx
dashboard/src/common/DashboardVersion.tsx

Subgraphs.xyz has been unstable because of errors returned from the subgraph status service. This has been causing the entire app to crash. This is a quick fix for the charting feature while the status service is being fixed that prevents the app from crashing when the status service returns an error.

Subgraphs.xyz charting quick fix

---

deployment/deployment.json

**Context**
Uniswap V2 Swap Ethereum subgraph has already been deployed to the Arbitrum Decentralize Network. Here I am just adding the query ID to the deployment.json.

Add Uniswap V2 Swap Ethereum query ID for Arbitrum Decentralized Network

---

deployment/deployment.json

Just completed monthly deployment of new subgraphs to Arbitrum decentralized network and added new query IDs to the deployment.json.
- Node DAO Ethereum
- Origin Ether Ethereum
- Slisbnb BSC
- Coinbase Wrapped Staked ETH Ethereum
- Benqi Staked AVAX Avalanche
- Llama Airforce Ethereum
- Vaultka Arbitrum
- Concentrator Ethereum
- Stakestone Ethereum
- Prime Staked ETH Ethereum
- Bedrock uniETH Ethereum
- Eigenpie Ethereum
- Mellow LRT Ethereum

Deploy DN Subgraphs & Add Query IDs

---

deployment/deployment.json

Adding new deployment keys for: 
- Binance Staked ETH BSC/Ethereum
- Paxos/Tether Gold Ethereum
- Aurus Ethereum
- Matrixdock Ethereum
- Klimadao Polygon
- Dinero pxETH Etheruem
- Stake Link Liquid Ethereum
- Gogopool Avalanche
- Gaurda Staking Ethereum
- Tenderize V2 Ethereum/Arbitrum
- Tensorplex Ethereum

Add new DN deployments from 2024/09

---

deployment/deployment.json
subgraphs/aave-forks/package-lock.json
subgraphs/aave-forks/protocols/superlend/config/deployments/superlend-etherlink-mainnet/configurations.json
subgraphs/aave-forks/protocols/superlend/config/templates/superlend.template.yaml
subgraphs/aave-forks/protocols/superlend/src/constants.ts
subgraphs/aave-forks/protocols/superlend/src/mapping.ts
subgraphs/aave-forks/schema.graphql
subgraphs/aave-forks/src/constants.ts

Adds subgraph for Superlend on
- network: etherlink-mainnet
- schema: generic (uses generic SDK)
- test deployment: https://okgraph.xyz/?q=Qma9z58tTa2gMHreFSANUAgS24gGZY8umKgU9GQcTeqdir
QA
- Supply and Borrow Balance: 
- Revenue:
- Usage:

feat(#major); superlend; add subgraph
