schema-lending.graphql

add protocolControlledValueUSD and protocolTreasuryUSD

Add fields to lending financialSnapshot

---

schema-common.graphql
schema-dex-amm.graphql
subgraphs/_reference_/schema.graphql
subgraphs/_reference_/src/common/constants.ts
subgraphs/uniswap-v2/schema.graphql
subgraphs/uniswap-v2/src/common/constants.ts
subgraphs/uniswap-v2/src/common/helpers.ts
subgraphs/uniswap-v3/schema.graphql
subgraphs/uniswap-v3/src/common/constants.ts
subgraphs/uniswap-v3/src/common/helpers.ts

refactor uniswap v3 at the same time

add FIXED_PROTOCOL_FEE and DYNAMIC_PROTOCOL_FEE

---

subgraphs/stakedao/src/common/constants.ts
subgraphs/tokemak/src/common/constants.ts
subgraphs/yearn-v2/src/common/constants.ts

They are not dex so they don't need LiquidityPoolFeeType

remove unneeded LiquidityPoolFeeType

---

subgraphs/_reference_/src/common/getters.ts
subgraphs/_reference_/src/common/metrics.ts

This PR aims to fix the build script in the `_reference_` subgraph

Fix: Helper entities imports

---

docs/Mapping.md

added useful links and link to youtube video

Add more docs for running node

---

subgraphs/liquity/schema.graphql
subgraphs/liquity/src/entities/market.ts
subgraphs/liquity/src/entities/protocol.ts
subgraphs/liquity/src/utils/constants.ts

Also fix `UsageMetricsHourlySnapshot.hourlyActiveUsers`

Update Liquity subgraph to schema version 1.2.1

---

subgraphs/compound-forks/README.md
subgraphs/compound-forks/src/mapping.ts

daily revenue fields are no longer zeros

Fix compound forks daily revenue

---

subgraphs/liquity/README.md
subgraphs/liquity/src/entities/event.ts
subgraphs/liquity/src/mapping/TroveManager.ts
subgraphs/liquity/src/utils/constants.ts
subgraphs/liquity/subgraph.yaml

- Create separate `Liquidate` entities for each trove liquidated in a single transaction

Track Liquity liquidations individually

---

subgraphs/abracadabra/src/common/constants.ts
subgraphs/abracadabra/src/common/getters.ts

updated getter.ts to add mintedTokens to protocol entity, init snapshot values with running protocol values

Abracadabra

---

subgraphs/belt-finance/README.md
subgraphs/belt-finance/schema.graphql
subgraphs/belt-finance/src/constant.ts
subgraphs/belt-finance/src/entities/Metrics.ts
subgraphs/belt-finance/src/entities/Protocol.ts
subgraphs/belt-finance/src/entities/Token.ts
subgraphs/belt-finance/src/entities/Vault.ts
subgraphs/belt-finance/src/handlers/common.ts
subgraphs/belt-finance/src/handlers/deposit.ts
subgraphs/belt-finance/src/handlers/vault.ts
subgraphs/belt-finance/src/handlers/withdraw.ts
subgraphs/belt-finance/src/utils/numbers.ts
subgraphs/belt-finance/subgraph.yaml

Belt schema update

---

subgraphs/compound-forks/aurigami/package.json
subgraphs/compound-forks/aurigami/src/constants.ts
subgraphs/compound-forks/aurigami/src/mapping.ts
subgraphs/compound-forks/aurigami/subgraph.yaml

https://github.com/messari/subgraphs/pull/209 should be merged first

add aurigami

---

dashboard/package-lock.json
dashboard/src/common/DashboardVersion.tsx
dashboard/src/interfaces/tabs/PoolTab.tsx
dashboard/yarn.lock

Fixed the conditional to determine which equation is used to calculate APR

Fix APR logic

---

dashboard/package-lock.json
dashboard/src/common/DashboardVersion.tsx
dashboard/src/common/chartComponents/Chart.tsx
dashboard/src/common/utilComponents/CopyLinkToClipboard.tsx
dashboard/src/index.css
dashboard/src/interfaces/IssuesDisplay.tsx
dashboard/src/interfaces/ProtocolDashboard.tsx
dashboard/src/interfaces/SchemaTable.tsx
dashboard/src/interfaces/tabs/EventsTab.tsx
dashboard/src/interfaces/tabs/PoolTab.tsx
dashboard/src/interfaces/tabs/ProtocolTab.tsx
dashboard/yarn.lock

-Fixes to various bugs mentioned in Discord
-Added issue conditions

Dashboard v1.0.3

---

subgraphs/compound-forks/.gitignore
subgraphs/compound-forks/Makefile
subgraphs/compound-forks/README.md
subgraphs/compound-forks/aurigami/src/mapping.ts
subgraphs/compound-forks/aurigami/subgraph.yaml
subgraphs/compound-forks/banker-joe/src/mapping.ts
subgraphs/compound-forks/banker-joe/subgraph.yaml
subgraphs/compound-forks/bastion-protocol/src/mapping.ts
subgraphs/compound-forks/bastion-protocol/subgraph.yaml
subgraphs/compound-forks/benqi/src/mapping.ts
subgraphs/compound-forks/benqi/subgraph.yaml
subgraphs/compound-forks/cream-finance/package.json
subgraphs/compound-forks/cream-finance/src/mapping.ts
subgraphs/compound-forks/cream-finance/subgraph.template.yaml
subgraphs/compound-forks/cream-finance/subgraph.yaml
subgraphs/compound-forks/iron-bank/package.json
subgraphs/compound-forks/iron-bank/src/mapping.ts
subgraphs/compound-forks/iron-bank/subgraph.template.yaml
subgraphs/compound-forks/moonwell/src/mapping.ts
subgraphs/compound-forks/moonwell/subgraph.yaml
subgraphs/compound-forks/package.json
subgraphs/compound-forks/schema.graphql
subgraphs/compound-forks/scream/src/mapping.ts
subgraphs/compound-forks/scream/subgraph.yaml
subgraphs/compound-forks/src/constants.ts
subgraphs/compound-forks/src/mapping.ts
subgraphs/compound-forks/venus/src/mapping.ts
subgraphs/compound-forks/yarn.lock

Organize mapping.ts code, add some constants, update dependecies

comp-fork update

---

subgraphs/convex/README.md

Convex Protocol Subgraph Metrics Methodology

---

subgraphs/platypus-finance/README.md

Platypus Finance Metrics Methodology v1.0

Platypus Finance Methodology

---

subgraphs/gmx/README.md

GMX Protocol Subgraph Metrics Methodology v1.0

GMX Protocol Subgraph Metrics Methodology 

---

README.md
subgraphs/compound-forks/Makefile

Deploy Comp forks and compound `1.5.7`

Comp Fork Deployments

---

subgraphs/abracadabra/src/mapping.ts

Fixes `liquidate.market [COLLATERAL] ==  liquidate.asset [REPAID]`

Abracadabra bug fix

---

deployment/deploymentConfigurations.json
subgraphs/uniswap-forks/protocols/sushiswap/config/networks/xdai/xdai.json

Sushiswap Gnosis - Set deploy-on-merge to true and made inconsequential change that will trigger deployment

---

subgraphs/compound-forks/moonwell/subgraph.yaml
subgraphs/compound-forks/src/mapping.ts

Fixing build error created from #359

fix build error forks

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/constants.ts
dashboard/src/deployments/Deployment.tsx
dashboard/src/deployments/DeploymentsPage.tsx
dashboard/src/interfaces/AllDataTabs.tsx
dashboard/src/interfaces/ProtocolDashboard.tsx
dashboard/src/interfaces/SchemaTable.tsx
dashboard/src/interfaces/tabs/PoolTab.tsx
dashboard/src/interfaces/tabs/PoolTabEntity.tsx
dashboard/src/interfaces/tabs/ProtocolTab.tsx
dashboard/src/interfaces/tabs/ProtocolTabEntity.tsx
dashboard/src/queries/dex/poolOverview.ts
dashboard/src/queries/dex/schema.ts

most of these changes are from prettier while I was logging around to figure things out. Any removed imports were unused

Support dex schema v1.3.0 on dashboard

---

subgraphs/treasuredao/README.md

TreasureDAO Protocol Metrics Subgraph Methodology v1.0

TreasureDAO Protocol Metrics Subgraph Methodology

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/queries/lending/poolOverview.ts
dashboard/src/queries/lending/schema.ts
dashboard/src/queries/yield/poolOverview.ts
dashboard/src/queries/yield/schema.ts

support 1.3.0 for yield and lending. Lmk if there's anything else that needs to be updated

finish supporting schema 1.3.0

---

deployment/README.md
deployment/execution.js
deployment/package.template.json

CI/CD - Removed `graph build` from deployment execution script since it is redundant and added dependencies to README

---

subgraphs/makerdao/src/mapping.ts
subgraphs/makerdao/src/mappings/core/spot.ts

MakerDAO: Fix warnings

---

subgraphs/dodo-v2/README.md

Dodo v2 Methodology 

---

schema-dex-amm-extended.graphql

Identical duplicate (other than schema version). Will make it easier to diff later on.

Duplicate DEX AMM schema for extension

---

subgraphs/qidao/schema.graphql
subgraphs/qidao/src/entities/event.ts
subgraphs/qidao/src/mappings/QiStablecoin.ts
subgraphs/qidao/src/mappings/erc20QiStablecoin.ts
subgraphs/qidao/src/utils/constants.ts
subgraphs/saddle-finance/src/entities/event.ts
subgraphs/saddle-finance/src/utils/constants.ts

- Also fix QiDao Liquidate liquidatee and asset fields
resolve #444

Fix from/to for Saddle and QiDao events

---

.husky/pre-commit
package-lock.json
package.json

Added pre-commit hook using husky to execute prettier on changed files before each commit

---

subgraphs/_reference_/src/common/utils/arrays.ts

adds: removeFromArrayAtIndex and addToArrayAtIndex to the utils for the reference subgraph

Reference Subgraph: Add more Array Utils

---

subgraphs/compound-forks-ext/protocols/compound-v2/src/mapping.ts

Syncing https://okgraph.xyz/?q=messari%2Fcompound-ethereum-extended

compound extended

---

subgraphs/yearn-v2/package.json
subgraphs/yearn-v2/src/common/initializers.ts
subgraphs/yearn-v2/yarn.lock

Deployment URL: https://thegraph.com/hosted-service/subgraph/harsh9200/yearn-v2?version=pending

Fix yearn-v2 deployment error

---

subgraphs/rari-vaults/package-lock.json
subgraphs/rari-vaults/package.json
subgraphs/rari-vaults/src/common/getters.ts
subgraphs/rari-vaults/subgraph.yaml

Fix Rari Vault issue

---

subgraphs/aave-v2-forks-ext/src/mapping.ts

PositionId was null in geist finance, when it should not be. Fix error checking

Geist Position ID fix

---

subgraphs/aave-v2-forks/protocols/geist-finance/src/mapping.ts

NOTE: turn off deployment script bc I already deployed this version to messari

fix geist build error

---

subgraphs/uniswap-forks/protocols/apeswap/src/common/handlers/handleReward.ts
subgraphs/uniswap-forks/protocols/apeswap/src/common/helpers.ts
subgraphs/uniswap-forks/protocols/sushiswap/src/common/handlers/handleReward.ts
subgraphs/uniswap-forks/protocols/sushiswap/src/common/helpers.ts
subgraphs/uniswap-forks/protocols/trader-joe/src/common/helpers.ts
subgraphs/uniswap-forks/protocols/vvs-finance/src/common/handlers/handleReward.ts

Updated so that reward token only populates if masterchef staking is used for that pool.

---

subgraphs/governance/README.md
subgraphs/governance/ens-governance/README.md
subgraphs/governance/ens-governance/subgraph.yaml

Fix ENS governance subgraph
Use the correct start block for the ENS token subgraph
https://thegraph.com/hosted-service/subgraph/messari/ens-governance

Fix ENS governance subgraph

---

subgraphs/compound-forks-ext/protocols/moonwell/config/networks/moonbeam/moonbeam.json
subgraphs/compound-forks-ext/src/mapping.ts

testing: https://okgraph.xyz/?q=dmelotik%2Fmoonwell-moonbeam

Remove Moonwell moonbeam from ext schema

---

deployment/deploymentConfigurations.json
subgraphs/aave-v3/protocols/aave-v3-extended/src/entities/event.ts
subgraphs/aave-v3/protocols/aave-v3-extended/src/entities/rate.ts
subgraphs/aave-v3/protocols/aave-v3-extended/src/utils/constants.ts
subgraphs/aave-v3/protocols/aave-v3/src/entities/rate.ts
subgraphs/aave-v3/src/utils/constants.ts
subgraphs/aave-v3/src/utils/numbers.ts

Aave V3: Convert interest rates to APY

---

schema-dex-amm-extended.graphql

1- See discord discussion (https://discord.com/channels/953684103012683796/953685205531631637/997813063430447175)
2- https://github.com/messari/subgraphs/commit/52113f4b04066c3b2d140248cab9dab96e3bff67
cc @this-username-is-taken

Add counter to Position ID, remove derivable feilds

---

subgraphs/aave-v2-forks-ext/README.md
subgraphs/aave-v2-forks-ext/protocols/aave-v2/src/constants.ts
subgraphs/aave-v2-forks-ext/protocols/aave-v2/src/mapping.ts
subgraphs/aave-v2-forks/README.md
subgraphs/aave-v2-forks/protocols/aave-v2/src/constants.ts
subgraphs/aave-v2-forks/protocols/aave-v2/src/mapping.ts

Fixing #532 
Testing: https://api.thegraph.com/subgraphs/id/QmUTWnF4EkeRAUNQic7XN5Vgc2nhSDYfVHTedcUeCFwwuM/graphql?query=query+MyQuery+%7B%0A++markets+%7B%0A++++name%0A++++id%0A++++inputTokenPriceUSD%0A++++inputToken+%7B%0A++++++name%0A++++++decimals%0A++++%7D%0A++%7D%0A%7D / https://okgraph.xyz/?q=dmelotik%2Faave-v2-avalanche

Aave V2: Fix Avalanche prices

---

subgraphs/aave-v2-forks-ext/protocols/aave-v2/src/mapping.ts

Aave Forks ext: add import

---

subgraphs/uniswap-forks/protocols/trader-joe/config/templates/trader.joe.template.yaml

Fixed handler naming in subgraph.yaml template for MasterChefV3

---

deployment/deployment.json
subgraphs/openzeppelin-governor/schema.graphql

https://linear.app/messari/issue/GOV-45/add-block-and-block-timestamp-to-vote-entity
Also set the deploy on merge flag to update 2 existing subgraphs

Make OZGovernor vote block and blocktime required

---

deployment/deployment.json
subgraphs/aave-v2-forks-ext/README.md
subgraphs/aave-v2-forks-ext/abis/aave-v2/StakedAave.json
subgraphs/aave-v2-forks-ext/protocols/aave-v2/config/templates/aave.v2.template.yaml
subgraphs/aave-v2-forks-ext/protocols/aave-v2/src/mapping.ts
subgraphs/aave-v2-forks/README.md
subgraphs/aave-v2-forks/abis/aave-v2/StakedAave.json
subgraphs/aave-v2-forks/protocols/aave-v2/config/templates/aave.v2.template.yaml
subgraphs/aave-v2-forks/protocols/aave-v2/src/mapping.ts

Grab reward price for aave v2 ethereum, because the reward token is stkAAVE which is tied to the price of AAVE
testing: https://okgraph.xyz/?q=dmelotik%2Faave-v2-grafting

Aave v2 Ethereum get rewards price working

---

deployment/deployment.json
subgraphs/aave-v2-forks-ext/protocols/aave-v2/src/constants.ts
subgraphs/aave-v2-forks-ext/protocols/aave-v2/src/mapping.ts
subgraphs/aave-v2-forks/protocols/aave-v2/src/constants.ts
subgraphs/aave-v2-forks/protocols/aave-v2/src/mapping.ts

Fixing pricing in polygon aave v2 ext and non ext
Testing:
- https://okgraph.xyz/?q=dmelotik%2Faave-v2-polygon-ext
- https://okgraph.xyz/?q=dmelotik%2Faave-v2-polygon
You can keep deployments on, it should deploy only polygon

Aave V2 polygon: fix pricing

---

deployment/deployment.json
subgraphs/aave-v3/protocols/aave-v3-extended/src/entities/position.ts

Added missing closing timestamp to Aave v3 extended mappings

Aave-v3-ext: Add closing timetamp

---

deployment/deployment.json
subgraphs/platypus-finance/README.md
subgraphs/platypus-finance/protocols/platypus-finance/config/networks/avalanche/avalanche.json
subgraphs/platypus-finance/protocols/platypus-finance/config/templates/platypus.template.yaml
subgraphs/platypus-finance/src/common/getters.ts
subgraphs/platypus-finance/src/mappings/masterPlatypus.ts

- Handle unexpected assets in master chef contract.
- Moved alt pools initialisation from code to deployment config.
- Added steps to add new pool in readme.

Platypus Fix

---

subgraphs/uniswap-forks/protocols/sushiswap/src/common/handlers/handleReward.ts
subgraphs/uniswap-forks/protocols/sushiswap/src/common/handlers/handleRewardV2.ts

These changes are already in deployment.

Sushiswap - Updated sushiPerBlock calculation in masterChefV2 to be done in masterChefV1

---

deployment/deployment.json
subgraphs/saddle-finance/package.json
subgraphs/saddle-finance/schema.graphql
subgraphs/saddle-finance/src/entities/pool.ts
subgraphs/saddle-finance/src/entities/protocol.ts
subgraphs/saddle-finance/src/utils/constants.ts
subgraphs/saddle-finance/subgraph.yaml
subgraphs/saddle-finance/yarn.lock

#556 
All fields related to pool.inputTokens should now be fixed, protocol.totalPoolCount should now match actual pool count.

Saddle Finance: update dependency versions, fix inputTokens order 

---

schema-nft-marketplace.graphql

Minimal schema for NFT marketplace.

add nft marketplace schema

---

subgraphs/compound-forks-ext/protocols/compound-v2/config/templates/compound-v2.template.yaml
subgraphs/compound-forks-ext/protocols/compound-v2/src/mapping.ts
subgraphs/compound-forks-ext/schema.graphql

Fixing #631 
Test query: https://api.thegraph.com/subgraphs/name/dmelotik/compound-ethereum-ext/graphql?query=query+MyQuery+%7B%0A++positions+%7B%0A++++account+%7B%0A++++++id%0A++++%7D%0A++++id%0A++++isCollateral%0A++%7D%0A%7D

Compound Ext: Fixing #631

---

deployment/deployment.json
subgraphs/openzeppelin-governor/schema.graphql
subgraphs/openzeppelin-governor/src/handlers.ts

https://linear.app/messari/issue/GOV-67/add-txnhash-to-vote-entity
Add transaction hash to votes to align schemas on the FE and in our GQL server

[Gov] Add txn hash to vote entity

---

subgraphs/compound-forks/protocols/benqi/src/mapping.ts

Fixing QA #627 
Changes:
- Rewards were being calculated for the year, changed to perDay
testing: https://okgraph.xyz/?q=dmelotik%2Fbenqi
** still waiting for sync to verify change

Benqi: Fixing issue #627

---

subgraphs/openzeppelin-governor/src/handlers.ts

Fix typo `VoteChoice.ABSTAIN_VALUE` should be `VoteChoice.AGAINST_VALUE`

Fix typo in getVoteChoiceByValue

---

subgraphs/uniswap-forks/abis/mm-finance/ERC20.json
subgraphs/uniswap-forks/abis/mm-finance/Factory.json
subgraphs/uniswap-forks/abis/mm-finance/MasterMeerkat.json
subgraphs/uniswap-forks/abis/mm-finance/Pair.json
subgraphs/uniswap-forks/configurations/configurations/configurations.ts
subgraphs/uniswap-forks/configurations/configurations/deploy.ts
subgraphs/uniswap-forks/protocols/mm-finance/config/networks/cronos/cronos.json
subgraphs/uniswap-forks/protocols/mm-finance/config/networks/cronos/cronos.ts
subgraphs/uniswap-forks/protocols/mm-finance/config/templates/mm.finance.template.yaml
subgraphs/uniswap-forks/protocols/mm-finance/src/common/constants.ts
subgraphs/uniswap-forks/protocols/mm-finance/src/common/handlers/handleReward.ts
subgraphs/uniswap-forks/protocols/mm-finance/src/mappings/mastermeerkat/reward.ts

Dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://graph.cronoslabs.com/subgraphs/name/messari/mm-finance
Graphql endpoint: https://graph.cronoslabs.com/subgraphs/name/messari/mm-finance
The deployed version integrates the changes in #722

feat: uniswap-forks; Added mm-finance

---

subgraphs/aave-v3/protocols/aave-v3/src/entities/event.ts
subgraphs/aave-v3/protocols/aave-v3/src/entities/position.ts
subgraphs/aave-v3/protocols/aave-v3/src/mappings/AToken.ts
subgraphs/aave-v3/protocols/aave-v3/src/mappings/StableDebtToken.ts
subgraphs/aave-v3/protocols/aave-v3/src/utils/constants.ts
subgraphs/aave-v3/schema.graphql

Also changed aToken transfer logic so that transfer volume is not included in market/protocol deposit and withdraw volume.

Aave v3: Fix stable mode borrow balance, close borrower position on liquidation

---

deployment/deployment.json
subgraphs/compound-forks/protocols/venus/README.md

Add readme addressing the notes made in the QA.
Relating to #707

docs(); Venus Protocol; add readme addressing QA

---

subgraphs/openzeppelin-governor/schema.graphql
subgraphs/openzeppelin-governor/src/handlers.ts

Include the transaction hash of proposal creation in the proposal entity

[Gov] Add txnHash to proposal entity

---

subgraphs/uniswap-forks/protocols/trader-joe/config/networks/avalanche/avalanche.ts
subgraphs/uniswap-forks/protocols/trader-joe/src/common/constants.ts

fix(#patch): trader-joe; Add USDC.e as whitelisted stablecoin

---

dashboard/public/deployments.json
dashboard/src/common/DashboardVersion.tsx
dashboard/src/common/SubgraphLogo.tsx
dashboard/src/common/chartComponents/TablePoolOverview.tsx
dashboard/src/deployments/DecentralizedNetworkRow.tsx
dashboard/src/interfaces/ProtocolDashboard.tsx
dashboard/src/interfaces/tabs/PoolTabEntity.tsx

Added env variable for decentralized network API key

Dashboard v1.3.3

---

docs/Schema.md

- Added more in-depth information to the schema documentation about fields related to rewards calculations for dexes
- We want to keep fields like (`rewardTokenEmissionsAmount`, `rewardTokenEmissionsUSD`, `stakedOutputTokenAmount`, `rewardToken`) null unless the related pool is used in staking. 
- Even if the pool is no longer earning rewards, we still want to leave these fields as non-null values.
- Response to issue #740. Related PR #755

docs(); schema; updated Reward Token information for DEXs

---

subgraphs/makerdao/protocols/makerdao/config/templates/makerdao.template.yaml

Updated makerdao.template.yaml with necessary abis to fix deployment fail

updated/fixed makerdao.template.yaml

---

README.md
subgraphs/compound-forks/protocols/tectonic/src/constants.ts
subgraphs/compound-forks/protocols/tectonic/src/mapping.ts

Changes:
- add `NewReserveFactor` handler
- calculate rewards rate based on rolling blocks/day calculator
- calculate interest rates using rolling blocks/day calculator
Test: https://graph.cronoslabs.com/subgraphs/name/protocols/tectonic-cronos
Note to deploy to cronos portal once merged/approved
There is still an issue with liquidates having a non-null position entity, but that is a greater compound-fork issue

fix(#patch); tectonic; address QA

---

subgraphs/makerdao/schema.graphql

This fixes a non-nullable field error in `handleClipTakeBid()`.

Fix (#minor); makerdao; removed unneeded fields from _ClipTakeStore in schema

---

subgraphs/notional/README.md

Add methodology for Notional Finance

---

deployment/deployment.json
subgraphs/uniswap-v3/configurations/configurations/configurations.ts
subgraphs/uniswap-v3/configurations/configurations/deploy.ts
subgraphs/uniswap-v3/configurations/configure.ts
subgraphs/uniswap-v3/protocols/uniswap-v3/config/networks/arbitrum/arbitrum.json
subgraphs/uniswap-v3/protocols/uniswap-v3/config/networks/celo/celo.json
subgraphs/uniswap-v3/protocols/uniswap-v3/config/networks/celo/celo.ts
subgraphs/uniswap-v3/protocols/uniswap-v3/config/networks/ethereum/ethereum.json
subgraphs/uniswap-v3/protocols/uniswap-v3/config/networks/optimism/optimism.json
subgraphs/uniswap-v3/protocols/uniswap-v3/config/networks/polygon/polygon.json
subgraphs/uniswap-v3/protocols/uniswap-v3/config/templates/uniswap.v3.template.yaml
subgraphs/uniswap-v3/subgraph.yaml

**Context** 
Celo network has been added to Uniswap V3. It was added a little over a month ago. The protocol has fairly low TVL currently at about 1.1 million. As a result, I have set a much lower minimum liquidity threshold for tracking token prices at about $35,000 USD. We may want to lower this depending on how well it tracks data relating to USD value, however, this can sometimes leading to a lot of abnormal pricing behavior in the Uniswap V3 subgraphs. 
**To do**
Add Uniswap V3 Celo endpoint to the Messari Hosted Service.

feat(#minor); Uniswap V3; add Celo network

---

subgraphs/makerdao/protocols/makerdao/config/templates/makerdao.template.yaml
subgraphs/makerdao/src/common/constants.ts
subgraphs/makerdao/src/common/helpers.ts
subgraphs/makerdao/src/mapping.ts

- Fixed cumulative/daily protocol side revenue fields in protocol/financial daily snapshot
- Fixed incorrect interest rates for MCD-POT and SAI market
- Updated grafting

fix(#patch); makerdao; fixed protocol side revenue/interest rate

---

subgraphs/balancer-forks/abis/beethoven-x/masterchef/MasterChefV2.json
subgraphs/balancer-forks/protocols/beethoven-x/config/networks/fantom/fantom.json

**Context:**
Beethoven X was getting a build error in CI/CD. I removed generated and build files and it deployed fine on my machine. However git does not recognize masterChef as masterchef when deploying in the actions. I updated the folder to match the casing in the subgraph manifest.

fix(#minor); Beethoven X; fixed folder casing

---

subgraphs/inverse-finance/protocols/inverse-finance/config/templates/inverse.finance.template.yaml
subgraphs/inverse-finance/src/common/constants.ts
subgraphs/inverse-finance/src/common/getters.ts
subgraphs/inverse-finance/src/common/helpers.ts
subgraphs/inverse-finance/src/common/utils.ts
subgraphs/inverse-finance/src/rewardtoken.ts
subgraphs/inverse-finance/src/stablizer.ts

- More details of the fixes/changes in #571

Fix (#patch); Inverse finance; address QA issues in #571

---

deployment/deployment.json
subgraphs/openzeppelin-governor/protocols/angle-governance/src/governor.ts
subgraphs/openzeppelin-governor/protocols/code4rena-governance/src/arena-governor.ts
subgraphs/openzeppelin-governor/protocols/ens-governance/src/ens-governor.ts
subgraphs/openzeppelin-governor/protocols/euler-governance/src/governance.ts
subgraphs/openzeppelin-governor/protocols/fei-governance/src/fei-dao.ts
subgraphs/openzeppelin-governor/protocols/hop-governance/src/hop-governor.ts
subgraphs/openzeppelin-governor/protocols/silo-governance/src/silo-governor.ts
subgraphs/openzeppelin-governor/protocols/truefi-governance/src/dao-governor.ts
subgraphs/openzeppelin-governor/protocols/unlock-governance/src/unlock-protocol-governor.ts
subgraphs/openzeppelin-governor/schema.graphql
subgraphs/openzeppelin-governor/src/handlers.ts

Add some additional block, timestamp and txnHash fields to the schema for building a proposal's state history downstream. 
- Downstream change in Governor-Service https://github.com/messari/governor-service/pull/92
https://thegraph.com/hosted-service/subgraph/messari/ens-governance

[GOV] OZ Governor: Add block and txnHash for missing proposal states

---

subgraphs/inverse-finance/README.md
subgraphs/inverse-finance/src/common/getters.ts
subgraphs/inverse-finance/src/common/helpers.ts
subgraphs/inverse-finance/src/factory.ts

Fix (#patch); inverse-finance; add notes to README for data inconsistencies

---

deployment/deployment.json
subgraphs/aave-v2-forks/protocols/aave-v2/src/mapping.ts
subgraphs/aave-v2-forks/protocols/geist-finance/config/networks/fantom/fantom.json
subgraphs/aave-v2-forks/protocols/geist-finance/src/mapping.ts
subgraphs/aave-v2-forks/src/helpers.ts
subgraphs/aave-v2-forks/src/mapping.ts
subgraphs/aave-v2-forks/src/token.ts

no need to redeploy, but I updated the imports.
I forgot to do this, and when I was deploying it was using artifacts from old builds. Everything is good, just needed to be cleaned up

fix(); aave forks; fix imports

---

subgraphs/rocket-pool/README.md

Adding formulas to Revenue section and also some changes to the TVL and Protocol Owned Liquidity pursuant to the changes in the Revenue section.

Amendments to Financial Metrics

---

deployment/deployment.json
subgraphs/compound-forks/protocols/dforce/config/templates/dforce.template.yaml
subgraphs/compound-forks/protocols/dforce/src/mapping.ts

handler function for `BorrowPaused` event is incorrectly mapped to `handleDistributedBorrowerComp`

fix (#patch); dforce; fixed wrong handler function name for BorrowPaused event

---

subgraphs/compound-forks/protocols/compound-v2/README.md

ETH pricing broken after proposal 117 executed

docs(); compound; notes about prop 117 break 

---

subgraphs/makerdao/protocols/makerdao/config/templates/makerdao.template.yaml
subgraphs/makerdao/schema.graphql
subgraphs/makerdao/src/common/constants.ts
subgraphs/makerdao/src/mapping.ts

See #500 for more details. Will be ready for review when the deployed subgraph (https://thegraph.com/hosted-service/subgraph/tnkrxyz/makerdao-ethereum?version=pending) finishes syncing and verified fixed.

fix (#patch); makerdao; fixed totalBorrowBalanceUSD after liquidation

---

README.md
deployment/deployment.json
subgraphs/compound-forks/protocols/rari-fuse/README.md
subgraphs/compound-forks/protocols/rari-fuse/src/constants.ts
subgraphs/compound-forks/protocols/rari-fuse/src/mappings.ts
subgraphs/compound-forks/schema.graphql
subgraphs/compound-forks/src/mapping.ts

Fixing QA #914 
Changes:
- update to `1.1.4`
- fix bug in liquidation decimals
- use Phonix's price oracle when Vesper pool V-dollars are out of range (.5-2)
Testing: 
- https://okgraph.xyz/?q=dmelotik%2Ffuse-mainnet
- https://okgraph.xyz/?q=dmelotik%2Ffuse-official

fix(#patch); rari fuse; fix QA issues

---

subgraphs/uniswap-forks/README.md
subgraphs/uniswap-forks/protocols/apeswap/README.md
subgraphs/uniswap-forks/protocols/honeyswap/README.md
subgraphs/uniswap-forks/protocols/mm-finance/README.md
subgraphs/uniswap-forks/protocols/quickswap/README.md
subgraphs/uniswap-forks/protocols/solarbeam/README.md
subgraphs/uniswap-forks/protocols/spiritswap/README.md
subgraphs/uniswap-forks/protocols/spookyswap/README.md
subgraphs/uniswap-forks/protocols/sushiswap/README.md
subgraphs/uniswap-forks/protocols/trader-joe/README.md
subgraphs/uniswap-forks/protocols/ubeswap/README.md
subgraphs/uniswap-forks/protocols/uniswap-v2/README.md
subgraphs/uniswap-forks/protocols/vvs-finance/README.md

**Context:**
We wanted to add documentation for each protocol in the Uniswap Forks. I have added documents describing the methodology within each protocol specific folder.

docs (#minor); Uniswap Forks; Added README for each protocol. 

---

deployment/deployment.dev.json

**Context:**
New deployment.json for use on front end and CI/CD. Other changes coming soon in PR #763.

feat(#major); deployment.json; upgrade deployment.json

---

deployment/deployment.dev.json
subgraphs/uniswap-forks/protocols/uniswap-v2/config/networks/ethereum/ethereum.ts
subgraphs/uniswap-forks/protocols/uniswap-v2/src/common/constants.ts

**Context:**
Large TVL issue for uniswap V2. Needed to blacklist tokens to fix the issue.

patch (#minor); Uniswap v2; Add blacklist tokens to uniswap v2

---

deployment/deployment.dev.json

**Context:**
There were a few things that needed fixed from the previous change

patch (#minor); Deployment Json; Update a few versions and fix vesper service

---

deployment/README.md
deployment/deployment.js

**Context:**
Typo in validation import in deployment.js from recent PR.

patch (#minor); Fixed typo in deployment.js

---

deployment/README.md

**Context:**
- Improved the documentation for using deployment scripts and CI/CD

patch (#minor); Improved README documentation

---

deployment/deployment.dev.json
deployment/deployment.json
subgraphs/uniswap-forks/protocols/apeswap/config/networks/bsc/bsc.ts
subgraphs/uniswap-forks/protocols/apeswap/config/networks/polygon/polygon.ts
subgraphs/uniswap-forks/protocols/apeswap/src/common/constants.ts

**Context:**
While updating documentation, I noticed a couple of errors with apeswap configurations. All addresses needed to be converted to lower case, the reward tokens and reward interval needed to be flipped for Apeswap BSC and Polygon. The fixing address casing should start pricing more tokens including BANANA which should also impact rewards on Polygon. The reward interval swap should also impact rewards substantially. 
**Fix:**

fix(#major); Apeswap; Fix Apeswap configurations

---

deployment/deployment.dev.json
subgraphs/uniswap-v3/configurations/configure.ts
subgraphs/uniswap-v3/protocols/uniswap-v3/config/deployments/uniswap-v3-celo/configurations.json
subgraphs/uniswap-v3/protocols/uniswap-v3/config/deployments/uniswap-v3-celo/configurations.ts
subgraphs/uniswap-v3/protocols/uniswap-v3/config/templates/uniswap.v3.template.yaml
subgraphs/uniswap-v3/src/common/utils/backfill.ts

**Conext:** 
There were some minor pricing issues in the Uniswap V3 Celo. I am fixing this by making some small changes to the configurations with the reference token and minimum liquidity threshold. This is in response to a data issue brought to my attention from @bye43.
- https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/uniswap-v3-celo&tab=pool&poolId=0xd88d5f9e6c10e6febc9296a454f6c2589b1e8fae

fix (#minor); Uniswap V3 Celo; Updated reference token and reduced minimum liquidity threshold. 

---

deployment/README.md
deployment/validation/deployment-tests.txt

**Context:**
Some people may experience unexpected results when using upper case letters in the deployment scripts for config variables. Updated README to recommend using lower case letters to avoid anyone else having issues with this,

doc; Deployment Scripts; Updated recommendations on npm config casing for deployment scripts.

---

deployment/deploymentClass.js

@steegecs I think there might have been an issue introduced with #1012 
It was preventing me from deploying as no scripts were generated.
Yup. Great catch! Thanks for going ahead and fixing this.

fix(#patch); Incorrect path in prepareScripts

---

deployment/deployment.json
subgraphs/uniswap-v3/protocols/uniswap-v3/config/templates/uniswap.v3.template.yaml
subgraphs/uniswap-v3/src/common/creators.ts
subgraphs/uniswap-v3/src/common/price/price.ts
subgraphs/uniswap-v3/src/common/utils/backfill.ts

patch (#minor): Uniswap V3; a few small things needed patched

---

subgraphs/compound-forks/protocols/rari-fuse/README.md

update readme to talk about reentrancy attacks in april 30 2022

docs(); rari fuse; update hack info

---

deployment/deployment.dev.json
deployment/deployment.json
subgraphs/aave-v2-forks/protocols/aave-v2/README.md
subgraphs/aave-v2-forks/protocols/aave-v2/config/templates/aave.v2.template.yaml
subgraphs/aave-v2-forks/protocols/aave-v2/src/constants.ts
subgraphs/aave-v2-forks/protocols/aave-v2/src/mapping.ts
subgraphs/aave-v2-forks/protocols/geist-finance/config/templates/geist.finance.template.yaml
subgraphs/aave-v2-forks/protocols/geist-finance/src/constants.ts
subgraphs/aave-v2-forks/protocols/geist-finance/src/mapping.ts
subgraphs/aave-v2-forks/src/helpers.ts
subgraphs/aave-v2-forks/src/mapping.ts

Changes:
- addressing #704 
- update version of aave v2 and geist
- get borrow position balance from debt tokens to eliminate crazy high borrow issue
- add more position updates for all transfers in a liquidation
- update position balances during transfer events
Testing:
- https://okgraph.xyz/?q=dmelotik%2Faave-v2-arc
- https://okgraph.xyz/?q=dmelotik%2Faave-v2-avalanche-ext
- https://okgraph.xyz/?q=dmelotik%2Faave-v2-ethereum-ext
- https://okgraph.xyz/?q=dmelotik%2Faave-v2-ethereum-amm
- https://okgraph.xyz/?q=dmelotik%2Faave-v2-polygon
- https://okgraph.xyz/?q=dmelotik%2Faave-v2-rwa
- https://okgraph.xyz/?q=dmelotik%2Fgeist-fantom

fix(#patch); aave v2 forks; position issues

---

deployment/deployment.json
subgraphs/euler-finance/protocols/euler-finance/config/deployments/euler-finance-ethereum/configurations.json
subgraphs/euler-finance/protocols/euler-finance/config/templates/euler.template.yaml
subgraphs/euler-finance/src/common/constants.ts
subgraphs/euler-finance/src/common/conversions.ts
subgraphs/euler-finance/src/mappings/handlers.ts
subgraphs/euler-finance/src/mappings/helpers.ts

We saw a price issue in CTX (Cryptex) on block `15358330` which was making dailyBorrowUSD artificially high.
Fix: take the price and hardcode from coingecko at that exact block

fix(#patch); euler; fix CTX price mismatch

---

deployment/deployment.json
subgraphs/compound-forks/protocols/cream-finance/config/deployments/cream-finance-ethereum/configurations.json
subgraphs/compound-forks/protocols/cream-finance/src/mapping.ts

deprecate snapshots as well to ensure proper viewing on protocol metrics FE
Grafting: https://okgraph.xyz/?q=dmelotik%2Fcream-finance-ethereum

fix(#patch); cream eth; deprecate snapshots

---

deployment/deployment.json
subgraphs/compound-forks/protocols/rari-fuse/config/deployments/rari-fuse-arbitrum/configurations.json
subgraphs/compound-forks/protocols/rari-fuse/src/constants.ts
subgraphs/compound-forks/protocols/rari-fuse/src/mappings.ts
subgraphs/compound-forks/protocols/rari-fuse/src/rewards.ts

Exotic / test markets throwing off protocol TVL on arbitrum. We will blocklist those 2 markets to fix this.

fix(#patch); rari fuse arb; blocklist exotic markets

---

deployment/deployment.json

update truefi status on deployment.json

fix(); truefi; update truefi status

---

deployment/deployment.json

removing for now, will add back in separate PR #1057

fix(#patch); deployment.json; remove outdated cryptopunks deployment config

---

deployment/deployment.json
subgraphs/uniswap-forks/protocols/trader-joe/src/common/constants.ts
subgraphs/uniswap-forks/protocols/trader-joe/src/common/handlers/handleRewarder.ts
subgraphs/uniswap-forks/protocols/trader-joe/src/common/handlers/rewarderRate/rewardRateCalculator.ts

The build was broken for trader joe. It worked for me the last time I pushed it because I had some leftovers on my `generated` folder.

fix(#patch): fixed trader joe build

---

docs/Contributing.md

Fix: typos

---

subgraphs/compound-forks/protocols/cream-finance/README.md

udpate docs to make the issue known where we cannot get the price at the beginning of the deployment.

docs(); cream; update docs

---

schema-nft-marketplace.graphql

ref: #1053 
- add derived fields (marketplace collections/daily snapshots) as mentioned in these comments: 
- https://github.com/messari/subgraphs/pull/746#discussion_r945223239
- https://github.com/messari/subgraphs/pull/746#discussion_r945223239
- update `STANDARD_SALE` strategy to `FIXED_PRICE`
- remove `tokenCount` field in `Collection` entity (in favor of ERC721 metadata subgraph token count)

refactor(#major); schema; update for NFT marketplaces 

---

subgraphs/gmx/README.md

Updates, and more detail, to original README courtesy of the honorable @SerenityFund

GMX Readme v1.0.1

---

subgraphs/makerdao/protocols/makerdao/config/templates/makerdao.template.yaml
subgraphs/makerdao/src/common/constants.ts
subgraphs/makerdao/src/mapping.ts

- Skip handling ilk TELEPORT-FW-A as a temp fix for error caused by the new DAI Teleport bridge contract;
- fixed subgraph version inconsistency between deployment.json and subgraph (constants.ts)

fix (#patch); makerdao; #1144

---

.github/workflows/build-checker.yaml
package-lock.json
package.json
subgraphs/.eslintrc.json
subgraphs/package-lock.json

**Context:**
We want to make sure that the code that is getting merged into the repository is linted. This PR adds an action to the workflow that runs our linter on changed files within the subgraph folder. When a file needs to be linted, this portion of the action will fail.

feat (#minor); Eslint action; Add linting action when pushing to the repo.

---

deployment/deployment.json

Updated deployment.json for TrueFi, CREAM, Rari Fuse, Rari Vaults

chore(); Updated deployment.json for TrueFi, CREAM, Rari Fuse, Rari Vaults

---

deployment/deployment.json

chore(); deployments.json; ArrakisFinance: Add polygon and optimism support

---

deployment/deployment.json
subgraphs/compound-forks/protocols/dforce/src/mapping.ts
subgraphs/compound-forks/src/mapping.ts

Fixed QA issues reported in #868
1. Fixed underlying token conflict: ZERO_ADDRESS is ETH on mainnet, BNB on BSC
2. Fixed protocol.mintedTokens and protocol.mintedTokenSupplies
3. Fixed financialDailySnapshot.mintedTokenSupplies (compound-forks/src/mapping.ts)
4. ARBITRUM_BLOCKS_PER_YEAR and ARBITRUM_BLOCKS_PER_DAY (also in #1049; will rebase this PR if #1049 is merged first)
5. bumped subgraph version to 1.2.0

fix (#minor); dforce; fixed QA issues reported in #868

---

deployment/deployment.json
subgraphs/compound-forks/protocols/aurigami/src/mapping.ts
subgraphs/compound-forks/protocols/banker-joe/src/mapping.ts
subgraphs/compound-forks/protocols/bastion-protocol/src/mapping.ts
subgraphs/compound-forks/protocols/benqi/src/mapping.ts
subgraphs/compound-forks/protocols/compound-v2/src/constants.ts
subgraphs/compound-forks/protocols/compound-v2/src/mapping.ts
subgraphs/compound-forks/protocols/cream-finance/src/mapping.ts
subgraphs/compound-forks/protocols/dforce/src/mapping.ts
subgraphs/compound-forks/protocols/iron-bank/src/mapping.ts
subgraphs/compound-forks/protocols/moonwell/src/mapping.ts
subgraphs/compound-forks/protocols/rari-fuse/src/constants.ts
subgraphs/compound-forks/protocols/rari-fuse/src/mappings.ts
subgraphs/compound-forks/protocols/scream/src/mapping.ts
subgraphs/compound-forks/protocols/tectonic/src/mapping.ts
subgraphs/compound-forks/protocols/venus/src/mapping.ts
subgraphs/compound-forks/src/constants.ts
subgraphs/compound-forks/src/mapping.ts

This PR adds updates for tvl/deposit for mint/redeem event, and totalBorrowBalance for borrow/repay event and addresses issue described in #1111

fix (#patch); compound-forks; improve accuracy of tvl/totalBorrow

---

.gitignore

**Config:**
Added: 
- deploymentJsonContext.ts
- deploymentJsonContext.json
- **/configurations/configure.ts

(#feat); gitignore; Added gitignore configs

---

subgraphs/aave-governance/protocols/aave-governance/src/aave-token-v-2.ts
subgraphs/aave-governance/protocols/aave-governance/src/staked-token-v-2-rev-3.ts
subgraphs/aave-governance/protocols/dydx-governance/src/dydx-token.ts
subgraphs/aave-governance/protocols/dydx-governance/src/staked-dydx-token.ts
subgraphs/aave-governance/schema.graphql
subgraphs/aave-governance/src/handlers.ts
subgraphs/aave-governance/src/tokenHandlers.ts

Propagate new entities from OpenZeppelin to Aave subgraphs

[GOV] Add delegate and voting power change entities to Aave / dYdX subgraphs

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/common/chartComponents/Chart.tsx
dashboard/src/common/chartComponents/ChartContainer.tsx
dashboard/src/common/chartComponents/TableChart.tsx
dashboard/src/index.css
dashboard/src/interfaces/tabs/PoolTabEntity.tsx
dashboard/src/interfaces/tabs/ProtocolTabEntity.tsx
dashboard/src/utils/index.ts

-Added buttons for download all snapshot charts and all snapshot csv data
-Styling changes like putting download buttons on the same line as other buttons and underline on hover
-Changed button labels
-Fix Date csv output

refactor(#major); Dashboard; v1.6.2 Restructure csv and image downloads

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/common/chartComponents/TableChart.tsx
dashboard/src/deployments/ProtocolSection.tsx
dashboard/src/interfaces/ProtocolDashboard.tsx
dashboard/src/interfaces/tabs/PoolTabEntity.tsx

-Handle zero entity subgraphs
-Improve behvaior for switching between pending/current subgraphs
-Fix erroneous csv outputs
-Reorder buttons
-Fix rewardAPR behavior for multiple reward tokens on a pool
-Split csv array columns into multiple individual columns
-Added derived fields into csv
-Changes to deployment table indexing percentage and 'synced' logic

refactor(#major); Dashboard; v1.6.3 CSV refactor, deployment table, 0 entity handling

---

docs/Mapping.md

It is a bit long; feel free to edit.

docs (); Added subsection for debugging oneshot error

---

deployment/deployment.json

fix(); vesta; update status

---

deployment/deployment.json
subgraphs/compound-forks/protocols/bastion-protocol/README.md

Update bastion docs. We are going to move this to prod and fix issues later as outlined in README
deployment: https://okgraph.xyz/?q=dmelotik%2Fbastion-protocol-aurora

docs(); bastion; update bastion notes

---

deployment/deployment.json
subgraphs/governor-alpha-bravo/abis/gitcoin-governance/GTC.json
subgraphs/governor-alpha-bravo/abis/gitcoin-governance/GovernorAlpha.json
subgraphs/governor-alpha-bravo/abis/pooltogether-governance/GovernorAlpha.json
subgraphs/governor-alpha-bravo/abis/pooltogether-governance/Pool.json
subgraphs/governor-alpha-bravo/protocols/gitcoin-governance/config/deployments/gitcoin-governance-ethereum/configurations.json
subgraphs/governor-alpha-bravo/protocols/gitcoin-governance/config/templates/gitcoin-governance.template.yaml
subgraphs/governor-alpha-bravo/protocols/gitcoin-governance/src/GTC.ts
subgraphs/governor-alpha-bravo/protocols/gitcoin-governance/src/GovernorAlpha.ts
subgraphs/governor-alpha-bravo/protocols/pooltogether-governance/config/deployments/pooltogether-governance-ethereum/configurations.json
subgraphs/governor-alpha-bravo/protocols/pooltogether-governance/config/templates/pooltogether-governance.template.yaml
subgraphs/governor-alpha-bravo/protocols/pooltogether-governance/src/GovernorAlpha.ts
subgraphs/governor-alpha-bravo/protocols/pooltogether-governance/src/Pool.ts
subgraphs/governor-alpha-bravo/src/versions.ts

Relatively straightforward, cloning the existing GAB template to add subgraphs for Gitcoin and PoolTogether
https://thegraph.com/hosted-service/subgraph/danielkhoo/gitcoin-governance
https://thegraph.com/hosted-service/subgraph/danielkhoo/pooltogether-governance

[GOV-383][GOV-384] Create subgraphs for Gitcoin and PoolTogether Governor Alpha

---

deployment/deployment.json

**Context:**
Turn `mainnet` reference to `ethereum`

fix(#patch); Fix aura finance deployment.json

---

deployment/deployment.json

**Context:** 
Deployment.json version was wrong for Ubeswap.

fix(#patch); Update ubeswap version in deployment.json

---

subgraphs/aave-v2-forks/protocols/aave-amm/config/templates/aave.amm.template.yaml
subgraphs/aave-v2-forks/protocols/aave-arc/config/deployments/aave-arc-ethereum/deploymentJsonContext.json
subgraphs/aave-v2-forks/protocols/aave-arc/config/templates/aave.arc.template.yaml
subgraphs/aave-v2-forks/protocols/aave-rwa/config/templates/aave.rwa.template.yaml

Fix the directory path to point to the correct src folders for arc, amm, and rwa aave deployments

fix(); aave v2; fix directory path

---

deployment/deployment.json
subgraphs/compound-forks/protocols/aurigami/src/mapping.ts
subgraphs/compound-forks/protocols/banker-joe/src/mapping.ts
subgraphs/compound-forks/protocols/bastion-protocol/src/mapping.ts
subgraphs/compound-forks/protocols/benqi/src/mapping.ts
subgraphs/compound-forks/protocols/compound-v2/src/constants.ts
subgraphs/compound-forks/protocols/cream-finance/src/mapping.ts
subgraphs/compound-forks/protocols/dforce/src/mapping.ts
subgraphs/compound-forks/protocols/iron-bank/src/mapping.ts
subgraphs/compound-forks/protocols/moonwell/src/mapping.ts
subgraphs/compound-forks/protocols/rari-fuse/src/constants.ts
subgraphs/compound-forks/protocols/scream/src/mapping.ts
subgraphs/compound-forks/protocols/tectonic/src/mapping.ts
subgraphs/compound-forks/protocols/venus/src/mapping.ts
subgraphs/compound-forks/src/mapping.ts

fix(#patch); comp forks; update liquidated asset

---

deployment/deployment.json
subgraphs/openzeppelin-governor/abis/threshold-governance/T.json
subgraphs/openzeppelin-governor/abis/threshold-governance/TokenholderGovernor.json
subgraphs/openzeppelin-governor/protocols/threshold-governance/config/deployments/threshold-governance-ethereum/configurations.json
subgraphs/openzeppelin-governor/protocols/threshold-governance/config/templates/threshold-governance.template.yaml
subgraphs/openzeppelin-governor/protocols/threshold-governance/src/t.ts
subgraphs/openzeppelin-governor/protocols/threshold-governance/src/tokenholder-governor.ts
subgraphs/openzeppelin-governor/src/constants.ts

Cloning the existing OZ template for Threshold Network

[GOV-419] Create OZ governance subgraph for Threshold Network

---

deployment/deployment.json
subgraphs/governor-alpha-bravo/abis/idle-governance/GovernorBravoDelegate.json
subgraphs/governor-alpha-bravo/abis/idle-governance/Idle.json
subgraphs/governor-alpha-bravo/abis/indexed-governance/GovernorAlpha.json
subgraphs/governor-alpha-bravo/abis/indexed-governance/Ndx.json
subgraphs/governor-alpha-bravo/protocols/idle-governance/config/deployments/idle-governance-ethereum/configurations.json
subgraphs/governor-alpha-bravo/protocols/idle-governance/config/templates/idle-governance.template.yaml
subgraphs/governor-alpha-bravo/protocols/idle-governance/src/GovernorBravoDelegate.ts
subgraphs/governor-alpha-bravo/protocols/idle-governance/src/Idle.ts
subgraphs/governor-alpha-bravo/protocols/indexed-governance/config/deployments/indexed-governance-ethereum/configurations.json
subgraphs/governor-alpha-bravo/protocols/indexed-governance/config/templates/indexed-governance.template.yaml
subgraphs/governor-alpha-bravo/protocols/indexed-governance/src/GovernorAlpha.ts
subgraphs/governor-alpha-bravo/protocols/indexed-governance/src/Ndx.ts

Cloning the existing GAB template to add subgraphs for Idle and Indexed

[GOV-386][GOV-387] Create governance subgraphs for Idle and Indexed

---

deployment/deployment.json

**Context:** 
Velo is now in prod

Chore(); Velodrome; Update Velo from dev to prod

---

.gitignore

**Context:**
Remove deploymnetJsonContext.ts from gitignore since the CLI changed.

chore(); gitignore; Remove TS context from gitignore

---

deployment/deployment.json

**Context:**
Set: 
- Pangolin
- Solarbeam
- mm finance
- VVS Finance
To `prod` in deployment.json.

chore(); deployment.json; Set dexes to prod that are prod ready in deployment.json

---

deployment/deployment.json
subgraphs/euler-finance/src/common/constants.ts
subgraphs/euler-finance/src/mappings/handlers.ts

Fixed negative rev by reverting assetStatus update to the end of handleAssetStatus()

fix(#bug); euler-finance; fixed negative revenues

---

deployment/deployment.json
subgraphs/aave-v2-forks/protocols/aave-amm/src/constants.ts
subgraphs/aave-v2-forks/protocols/aave-arc/src/constants.ts
subgraphs/aave-v2-forks/protocols/aave-rwa/src/constants.ts
subgraphs/aave-v2-forks/protocols/aave-v2/src/constants.ts
subgraphs/aave-v2-forks/protocols/geist-finance/src/constants.ts
subgraphs/aave-v2-forks/protocols/radiant-capital/src/constants.ts
subgraphs/aave-v2-forks/protocols/uwu-lend/src/constants.ts
subgraphs/aave-v2-forks/src/helpers.ts

Fix derived field `lendingProtocol.markets`. This was picked up by the bot monitor!

fix(#patch); aave v2 forks; fix dervied field

---

deployment/deployment.json

**Context:**
Status update for subgraphs in deployment.json
- Pangolin - dev
- Uniswap V3 (All) - prod
- Spiritswap - prod
- Velodrome - dev

Chore(); deployment.json; Fix deployment statuses

---

deployment/deployment.json

**Context:**
Velodrome is indexed to head and ingested.

feat(); Velodrome Finance; Change velodrome finance to prod

---

deployment/deployment.json
subgraphs/uniswap-forks/src/common/creators.ts
subgraphs/uniswap-forks/src/common/utils/utils.ts

**Context:**
The context for this PR is described in issue #1390. 
Uniswap V2 Subgraph with fix: 
https://thegraph.com/hosted-service/subgraph/steegecs/uniswap-v2-ethereum

fix(minor/major); Uniswap Forks; Fix swaps and volume

---

deployment/deployment.json
subgraphs/compound-forks/protocols/venus/config/deployments/venus-protocol-bsc/configurations.json
subgraphs/compound-forks/protocols/venus/config/templates/venus.template.yaml
subgraphs/compound-forks/protocols/venus/src/constants.ts
subgraphs/compound-forks/protocols/venus/src/mapping.ts

test: https://okgraph.xyz/?q=dmelotik%2Fvenus
#940

fix(#patch); venus; dai price

---

deployment/deployment.json
subgraphs/maple-finance/schema.graphql
subgraphs/maple-finance/src/common/mappingHelpers/getOrCreate/markets.ts
subgraphs/maple-finance/src/common/mappingHelpers/getOrCreate/protocol.ts
subgraphs/maple-finance/src/common/mappingHelpers/update/intervalUpdate.ts

test: https://okgraph.xyz/?q=dmelotik%2Fmaple-finance-ethereum
Added this to properly update the protocol tvl. Before we were seeing issue like this:

fix(#patch); maple; fix protocol tvl

---

deployment/deployment.json

**Context:**
Add DForce to decentralized network in deployment.json.

chore(); DForce; Add to decentralized network

---

subgraphs/compound-forks/protocols/banker-joe/README.md

#932
Deciding not to do rewards per @ken

docs(); Banker Joe Rewards

---

deployment/deployment.json
subgraphs/qidao/README.md

Explain why we cannot calculate rewards rates for QiDao on chain

docs(); qidao; rewards explanation

---

deployment/deployment.json
subgraphs/compound-forks/protocols/moonwell/src/constants.ts
subgraphs/compound-forks/protocols/moonwell/src/mapping.ts
subgraphs/compound-forks/src/constants.ts

Fix moonbeam rewards and separate network stuff using a class.
Moonriver: https://okgraph.xyz/?q=dmelotik%2Fmoonwell
Moonbeam: https://okgraph.xyz/?q=dmelotik%2Fmoonwell-moonbeam

fix(#patch); moonwell; moonbeam rewards

---

deployment/deployment.json
subgraphs/aave-v2-forks/protocols/uwu-lend/src/mapping.ts

We want to ensure that rewards are 0 if they are not being emitted.
test: https://okgraph.xyz/?q=dmelotik%2Fuwu-lend-ethereum

fix(#patch); uwu lend; 0 rewards

---

deployment/deployment.json
subgraphs/aave-v2-forks/protocols/uwu-lend/src/mapping.ts

Fix reward break.
test: https://okgraph.xyz/?q=dmelotik%2Fuwu-lend-ethereum

fix(#patch); uwu lend; fix reward break

---

deployment/deployment.json

Moved yearn-v2 decentralized deployment from ARB to ETH

fix(#minor); Update yearn V2 deployment info

---

deployment/deployment.json

Update belt finance status to prod

chore(); deployments.json: update belt status

---

deployment/deployment.json

DForce Avalanchge is not deployed

fix(); dforce; avax to dev status

---

deployment/deployment.json
subgraphs/ellipsis-finance/schema.graphql

**Context:** 
https://thegraph.com/hosted-service/subgraph/messari/ellipsis-finance-bsc
Ellipsis Finance is deploying. When It syncs to head, this PR will update to prod, and make a couple small fixes.

chore/fix(#patch); Ellipsis Finance; set to prod, remove a few unnecessary fields in the schema, update schema version.

---

deployment/deployment.json
subgraphs/aave-v3/schema.graphql

Add immutability to transactions: https://okgraph.xyz/?q=dmelotik%2Faave-v3-[CHAIN]

feat(#patch); aave v3; add immutability

---

deployment/deployment.json
subgraphs/compound-v3/src/sdk/constants.ts
subgraphs/compound-v3/src/sdk/manager.ts
subgraphs/compound-v3/src/sdk/snapshots.ts

Fixes a few things that I forgot to update and fixing snapshots not updating.
Also made the updates jaime suggested on the sdk

fix(#patch); comp v3; snapshots not updating

---

subgraphs/_reference_/src/sdk/README.md
subgraphs/_reference_/src/sdk/lending/README.md
subgraphs/_reference_/src/sdk/lending/account.ts
subgraphs/_reference_/src/sdk/lending/constants.ts
subgraphs/_reference_/src/sdk/lending/manager.ts
subgraphs/_reference_/src/sdk/lending/position.ts
subgraphs/_reference_/src/sdk/lending/snapshots.ts
subgraphs/_reference_/src/sdk/lending/token.ts
subgraphs/compound-v3/src/sdk/constants.ts
subgraphs/compound-v3/src/sdk/manager.ts
subgraphs/compound-v3/src/sdk/snapshots.ts

Also added README.md to describe the lending SDK

feat(#major): reference; add lending sdk

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/new_subgraph_template.md

feat(#major); add issue / PR templates

---

deployment/deployment.json
subgraphs/uniswap-v3/README.md
subgraphs/uniswap-v3/configurations/configure.mustache
subgraphs/uniswap-v3/protocols/uniswap-v3/config/deployments/uniswap-v3-ethereum/configurations.ts
subgraphs/uniswap-v3/src/common/constants.ts
subgraphs/uniswap-v3/src/common/creators.ts
subgraphs/uniswap-v3/src/common/utils/utils.ts

**Context:**
The TVL spiked downward, in order to fix this I have blacklisted the culprit pool.

fix(#minor); Uniswap-v3; Fix TVL spike down

---

subgraphs/maker-governance/protocols/maker-governance/src/ds-chief.ts
subgraphs/maker-governance/src/helpers.ts

Handle edge case where Maker delegate votes for a wrong address that isn't a proposal/spell.

[GIN] fix (#patch); maker Gov; fixed handling invalid spells

---

deployment/deployment.json

Update badgerdao ethereum status to prod

chore(); Update badgerdao to "prod"

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/common/chartComponents/BridgeOutboundChart.tsx
dashboard/src/common/chartComponents/ChartContainer.tsx
dashboard/src/common/chartComponents/DynamicColumnTableChart.tsx
dashboard/src/common/chartComponents/TableChart.tsx
dashboard/src/common/chartComponents/TablePoolOverview.tsx
dashboard/src/interfaces/BridgeOutboundVolumeLogic.tsx
dashboard/src/interfaces/SchemaTable.tsx
dashboard/src/interfaces/tabs/PoolTab.tsx
dashboard/src/interfaces/tabs/PoolTabEntity.tsx

-Added Bridge outflow volume table
-Bridge outflow volume chart display changes
-Bridge outflow volume CSV/chart image download
-Fixed schema specific baseYield bug
-Fixed reward token enums

feat(#minor); Dashboard; v1.9.7 Bridge outflow table, display changes

---

deployment/deployment.json
subgraphs/compound-forks/package-lock.json
subgraphs/compound-forks/package.json
subgraphs/compound-forks/protocols/benqi/config/deployments/benqi-avalanche/configurations.json
subgraphs/compound-forks/protocols/benqi/config/templates/benqi.template.yaml

Benqi had a runtime error of: 
```
A determinstic fatal error occured at block 24510208: Failed to call 'asc_type_id' with 'ArrayBuffer' wasm backtrace: 0: 0x23d5 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall 1: 0xca99
```
Fixing that with test deployment: https://okgraph.xyz/?q=dmelotik%2Fbenqi

fix(#patch); benqi; fix runtime error

---

deployment/deployment.json
docs/CHANGES.md
schema-lending.graphql
subgraphs/_reference_/src/sdk/protocols/lending/manager.ts
subgraphs/_reference_/src/sdk/protocols/lending/snapshots.ts
subgraphs/compound-v3/schema.graphql
subgraphs/compound-v3/src/sdk/manager.ts
subgraphs/compound-v3/src/sdk/snapshots.ts

Change `RevenueDetails` to `RevenueDetail` because the plural is interfering with the queries

fix(#patch); comp v3; revenue details

---

deployment/deployment.json

Update status of biswap from "dev" to "prod" in deployments.json

chore(); Update biswap to "prod"

---

deployment/deployment.json
schema-dex-amm-extended.graphql
subgraphs/uniswap-v3/configurations/configure.ts
subgraphs/uniswap-v3/schema.graphql
subgraphs/uniswap-v3/src/common/dex_event_handler.ts
subgraphs/uniswap-v3/src/common/entities/pool.ts
subgraphs/uniswap-v3/src/common/entities/protocol.ts
subgraphs/uniswap-v3/src/common/entities/tick.ts

**Context:**
Make a few fixes in response to data quality review for schema 3.0.0 transition.

fix(#minor); Uniswap V3; Make fixes on data review

---

deployment/deployment.json

Updated saddle (ALL), trader-joe (AVAX), and balancer v2 (ETH) to prod

chore(); Update deployments.json status

---

deployment/deployment.json
subgraphs/truefi/src/entities/protocol.ts

- Fix truefi schema version to prevent "protocol out of sync" error on PM

fix(#patch); truefi; fix versions

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/constants.ts
dashboard/src/deployments/ProtocolSection.tsx
dashboard/src/interfaces/tabs/PoolTab.tsx
dashboard/src/interfaces/tabs/PoolTabEntity.tsx
dashboard/src/interfaces/tabs/ProtocolTab.tsx
dashboard/src/interfaces/tabs/ProtocolTabEntity.tsx
dashboard/src/queries/bridge/schema.ts
dashboard/src/queries/dex/poolOverview.ts
dashboard/src/queries/dex/schema.ts
dashboard/src/queries/lending/schema.ts

-Add support for DEX AMM 3.0.3, deprecate 3.0.0,2,3
-Adding logic to default timeseries date val to be constructed from day/hour field rather than the timestamp
-Changed the deployment table okgraph URL to direct to correct subgraph slug
-Enable schema specififc custom logic to protocol tab

Charts to build date off day/hour field, DEX 3.0.3

---

subgraphs/multichain/src/mappings/handlers.ts
subgraphs/multichain/src/mappings/helpers.ts

test deployments: 
mainnet: https://okgraph.xyz/?q=Qmd8kcJtynQmoBz8sEVoWDSrwqvLpyU166y2mGFzKxLUkH
fantom: https://okgraph.xyz/?q=Qmbo7MH9DrgThLRMYuJwWTVJZ7YrPRkyxgEAFoS5qcC3g2

fix(#patch); multichain; fix unique transfer receivers count

---

deployment/deployment.json

Update multichain status to prod in deployments.json

chore(); Update status for multichain

---

deployment/deployment.json
subgraphs/abracadabra/package-lock.json
subgraphs/abracadabra/protocols/abracadabra/config/deployments/abracadabra-ethereum/configurations.json
subgraphs/abracadabra/src/common/tokens.ts

Fixing holey array issue in abra: #1617
- Build using different structure
- Testing: https://okgraph.xyz/?q=dmelotik%2Fabracadabra-ethereum

fix(#patch); abra; fix holey array

---

subgraphs/network/src/helper.ts
subgraphs/network/src/mapping.ts

fix(); network; lint

---

subgraphs/network/package-lock.json
subgraphs/network/package.json
subgraphs/network/protocols/arweave/config/templates/arweave.template.yaml
subgraphs/network/protocols/cosmos/config/templates/cosmos.template.yaml
subgraphs/network/protocols/cronos/config/templates/cronos.template.yaml
subgraphs/network/protocols/evm/config/deployments/evm-optimism/configurations.json
subgraphs/network/protocols/evm/config/templates/evm.template.yaml
subgraphs/network/src/helper.ts

In an attempt to increase the sync speed of `network-optimsim` (and others) I updated the spec to the latest versiona and all the latest graph-cli/ts versions
Deployment: https://okgraph.xyz/?q=dmelotik%2Fnetwork-optimism
See https://github.com/messari/subgraphs/pull/1638 for linting

fix(#patch); network; update spec/versions

---

deployment/deployment.json
subgraphs/_reference_/src/sdk/protocols/lending/position.ts
subgraphs/compound-v3/src/sdk/position.ts

New positions do not update the balance or position event count. Fixed this

fix(#minor); comp v3; fix addPosition

---

deployment/deployment.json
subgraphs/abracadabra/schema.graphql
subgraphs/abracadabra/src/common/constants.ts
subgraphs/abracadabra/src/common/getters.ts
subgraphs/abracadabra/src/common/metrics.ts
subgraphs/abracadabra/src/common/utils/utils.ts
subgraphs/abracadabra/src/mapping.ts
subgraphs/abracadabra/src/positions.ts

#957 fix negative position counts
- I think positions were not being moved to closedPositions, yet market.openPositionCount was being decremented
#1293 
- Attempting to fix the spikes in iinput tokens. Not visible in the api though...
- Fixed empty market snapshot rates
Also fixed the abracadabra linting errors to get the actions to pass
Test: 
- https://okgraph.xyz/?q=dmelotik%2Fabracadabra-avalanche
- https://okgraph.xyz/?q=dmelotik%2Fabracadabra-arbitrum
- https://okgraph.xyz/?q=dmelotik%2Fabracadabra-bsc
- https://okgraph.xyz/?q=dmelotik%2Fabracadabra-fantom
- https://okgraph.xyz/?q=dmelotik%2Fabracadabra-ethereum

fix(#patch); abra; fix negative positions

---

deployment/deployment.json
subgraphs/compound-forks/abis/sonne-finance/CToken.json
subgraphs/compound-forks/package-lock.json
subgraphs/compound-forks/package.json
subgraphs/compound-forks/protocols/sonne-finance/README.md
subgraphs/compound-forks/protocols/sonne-finance/config/deployments/sonne-finance-optimism/configurations.json
subgraphs/compound-forks/protocols/sonne-finance/config/templates/sonne.finance.template.yaml
subgraphs/compound-forks/protocols/sonne-finance/src/constants.ts
subgraphs/compound-forks/protocols/sonne-finance/src/mapping.ts

**Describe the PR**
Add Sonne finance with rewards
**Links**
Test: https://okgraph.xyz/?q=dmelotik%2Fsonne-finance-optimism

feat(#major); sonne finance; add new subgraph

---

deployment/deployment.json
subgraphs/aave-v3/protocols/aave-v3/config/deployments/aave-v3-ethereum/configurations.json
subgraphs/aave-v3/protocols/aave-v3/src/entities/market.ts

Test: https://okgraph.xyz/?q=messari%2Faave-v3-ethereum

feat(#major); aave v3; add aave v3 ethereum

---

deployment/deployment.json
subgraphs/uniswap-forks/abis/pangolin/Factory.json
subgraphs/uniswap-forks/configurations/configure.ts
subgraphs/uniswap-forks/protocols/apeswap/src/common/constants.ts
subgraphs/uniswap-forks/protocols/biswap/src/common/constants.ts
subgraphs/uniswap-forks/protocols/honeyswap/src/common/constants.ts
subgraphs/uniswap-forks/protocols/mm-finance/src/common/constants.ts
subgraphs/uniswap-forks/protocols/pangolin/config/deployments/pangolin-avalanche/configurations.ts
subgraphs/uniswap-forks/protocols/pangolin/src/common/constants.ts
subgraphs/uniswap-forks/protocols/quickswap/src/common/constants.ts
subgraphs/uniswap-forks/protocols/solarbeam/src/common/constants.ts
subgraphs/uniswap-forks/protocols/spiritswap/src/common/constants.ts
subgraphs/uniswap-forks/protocols/spookyswap/src/common/constants.ts
subgraphs/uniswap-forks/protocols/sushiswap/src/common/constants.ts
subgraphs/uniswap-forks/protocols/trader-joe/src/common/constants.ts
subgraphs/uniswap-forks/protocols/trisolaris/src/common/constants.ts
subgraphs/uniswap-forks/protocols/ubeswap/src/common/constants.ts
subgraphs/uniswap-forks/protocols/uniswap-v2/src/common/constants.ts
subgraphs/uniswap-forks/protocols/vvs-finance/src/common/constants.ts
subgraphs/uniswap-forks/src/common/constants.ts
subgraphs/uniswap-forks/src/common/creators.ts
subgraphs/uniswap-forks/src/common/updateMetrics.ts
subgraphs/uniswap-forks/src/mappings/pool.ts

This PR fixes fee issue reported in #1598 by editing the relevant value in configurations.ts
- Test deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/pangolin-avalanche
- data validation: https://subgraphs.messari.io/subgraph?endpoint=https://thegraph.com/hosted-service/subgraph/tnkrxyz/pangolin-avalanche&tab=protocol
- relevant query: https://api.thegraph.com/subgraphs/name/tnkrxyz/pangolin-avalanche/graphql?query=query+MyQuery+%7B%0A++liquidityPools%28where%3A+%7Bid%3A+%220xbd918ed441767fe7924e99f6a0e0b568ac1970d9%22%7D%29+%7B%0A++++fees+%7B%0A++++++feePercentage%0A++++++feeType%0A++++++id%0A++++%7D%0A++%7D%0A%7D

fix (#patch); pangolin-avalanche; fixed fees

---

subgraphs/qidao/README.md

Updated revenue on qidao docs to reflect subgraphs. Also removed rewards calculation as that is done offchain.

Updates to qidao readme docs

---

schema-derivatives-perpfutures.graphql

Some small changes to Perp schema in order to compile and deploy related GMX subgraph.
1. Some changes are needed as the following errors happening when compiling, deploying and running subgraphs otherwise.
2. Change some id from Bytes to String as it contains some string such as Deposit
3. Change some entries from immutable:true to immutable:false as the mapping codes may need to update the snapshot more than once.

feat(#minor): Fix Perp schema problem happening during compilation and deployment

---

deployment/deployment.json

Change stargate deployments (avax, bsc, arb, matic, op) to `dev`

chore(); Update deployments.json; Stargate deployments

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/constants.ts
dashboard/src/interfaces/ErrorDisplay.tsx
dashboard/src/interfaces/SchemaTable.tsx
dashboard/src/interfaces/tabs/PoolTab.tsx
dashboard/src/queries/bridge/poolOverview.ts
dashboard/src/queries/bridge/schema.ts
dashboard/src/queries/dex/schema.ts
dashboard/src/queries/generic/schema.ts
dashboard/src/queries/lending/schema.ts
dashboard/src/queries/yield/schema.ts

-update schema constants
-Fix Bridge routes blank out error
-Add support for Bridges v1.1.x

fix(#minor); Dashboard; Bridges support 1.1.x and fix breaking error

---

.github/ISSUE_TEMPLATE/subgraph_qa.md

Add QA issue template to reduce friction for people who make QAs

chore(); qa issue template

---

subgraphs/_reference_/src/sdk/protocols/bridge/account.ts
subgraphs/_reference_/src/sdk/protocols/bridge/pool.ts
subgraphs/_reference_/src/sdk/protocols/bridge/poolSnapshot.ts
subgraphs/_reference_/src/sdk/protocols/bridge/protocol.ts
subgraphs/_reference_/src/sdk/protocols/bridge/protocolSnapshot.ts

The build of the SDK broke after moving a few things around. This fixes it.
Fixes #1696

fix(#patch): fix SDK broken build

---

deployment/deployment.json

Add all pending (in dev) deployments to the deployment.json in order to add them to subgraphs.xyz

chore(); deployments; add pending

---

deployment/deployment.json
subgraphs/compound-forks/protocols/compound-v2/config/deployments/compound-v2-ethereum/configurations.json
subgraphs/compound-forks/protocols/compound-v2/src/constants.ts
subgraphs/compound-forks/protocols/compound-v2/src/rewards.ts

Fixing div by 0 runtime error compound V2.
Testing graft: https://okgraph.xyz/?q=dmelotik%2Fcompound-ethereum

fix(#minor); comp v2; fix div by 0 runtime error

---

subgraphs/_reference_/src/prices/calculations/CalculationsCurve.ts
subgraphs/_reference_/src/prices/calculations/CalculationsSushiswap.ts
subgraphs/_reference_/src/prices/index.ts
subgraphs/_reference_/src/prices/oracles/AaveOracle.ts
subgraphs/_reference_/src/prices/oracles/ChainLinkFeed.ts
subgraphs/_reference_/src/prices/oracles/YearnLensOracle.ts
subgraphs/_reference_/src/prices/routers/CurveRouter.ts
subgraphs/_reference_/src/prices/routers/UniswapForksRouter.ts

feat(#minor); Price lib; make block param optional

---

subgraphs/multichain/protocols/multichain/config/deployments/multichain-ethereum/configurations.json
subgraphs/multichain/src/mappings/helpers.ts

Deployment: https://okgraph.xyz/?q=QmWX3ZUMiCN2TRvtz9y4zt5QzzVA2UgGRgxkESxuHbSBhB

Multichain fix unexpected null

---

deployment/deployment.json

chore (); iron-bank; bumped subgraph version for iron-bank-fantom

---

subgraphs/multichain/protocols/multichain/config/deployments/multichain-ethereum/configurations.json
subgraphs/multichain/src/mappings/handlers.ts
subgraphs/multichain/src/mappings/helpers.ts

Test deployment: https://okgraph.xyz/?q=QmNY1GDA23MDuKYyDuqsuaLftk84hPjNfAb8pqKRgY5wNz

fix(#minor); multichain; fix poolSnapshots.routes

---

schema-derivatives-perpfutures.graphql

Sneak some changes into the futures schema.
Context: a couple things were found mising from the updates made recently. No subgraphs have been built yet using this so we are planning to sneak it in without a version change

fix(); futures schema

---

deployment/deployment.json
subgraphs/goldfinch/package-lock.json
subgraphs/goldfinch/package.json
subgraphs/goldfinch/protocols/goldfinch/config/deployments/goldfinch-ethereum/configurations.json
subgraphs/goldfinch/protocols/goldfinch/config/templates/goldfinch.template.yaml
subgraphs/goldfinch/src/mappings/membership/capital_ledger.ts

- Null trace fixed
- Update versions
- clean package.json
Test: https://okgraph.xyz/?q=dmelotik%2Fgoldfinch-ethereum

fix(#minor); goldfinch; fix null

---

deployment/deployment.json
subgraphs/aura-finance/package-lock.json
subgraphs/aura-finance/package.json
subgraphs/aura-finance/protocols/aura-finance/config/deployments/aura-finance-ethereum/configurations.json
subgraphs/aura-finance/src/common/getters.ts
subgraphs/aura-finance/src/common/utils/numbers.ts

- Fix div by 0 error
- update package.json
- update versions
Test: https://okgraph.xyz/?q=dmelotik%2Faura-finance-ethereum

fix(#minor); aura finance; div by 0 err

---

deployment/deployment.json
subgraphs/goldfinch/protocols/goldfinch/config/deployments/goldfinch-ethereum/configurations.json
subgraphs/goldfinch/src/mappings/membership/capital_ledger.ts
subgraphs/goldfinch/src/mappings/senior_pool.ts
subgraphs/goldfinch/src/mappings/tranched_pool.ts

fix null goldfinch errors.
Test: https://okgraph.xyz/?q=dmelotik%2Fgoldfinch-ethereum

fix(#minor); goldfinch; null errors

---

deployment/deployment.json
subgraphs/compound-forks/protocols/benqi/config/deployments/benqi-avalanche/configurations.json

**Context:**
The Graph now supports Arbitrum and Avalanche networks. I deployed all production Arbitrum and Avalanche subgraphs to the decentralized network except the DEXs. Will merge when oracle changes get merged into main.

chore(); Arbitrum/Avalanche Decentralized Network Deployments; 

---

deployment/deployment.json

Added Uniswap V3 and Sushiswap to Celo network. Also, made a fix to Ribbon Finance.

chore(); Celo Decentralized Network; Add celo to decentralized network

---

deployment/deployment.json
subgraphs/_reference_/src/sdk/protocols/lending/README.md
subgraphs/_reference_/src/sdk/protocols/lending/account.ts
subgraphs/_reference_/src/sdk/protocols/lending/manager.ts
subgraphs/_reference_/src/sdk/protocols/lending/position.ts
subgraphs/_reference_/src/sdk/protocols/lending/snapshots.ts
subgraphs/_reference_/src/sdk/protocols/lending/token.ts
subgraphs/compound-v3/package-lock.json
subgraphs/compound-v3/package.json
subgraphs/compound-v3/protocols/compound-v3/src/constants.ts
subgraphs/compound-v3/src/sdk/account.ts
subgraphs/compound-v3/src/sdk/manager.ts
subgraphs/compound-v3/src/sdk/position.ts
subgraphs/compound-v3/src/sdk/snapshots.ts
subgraphs/compound-v3/src/sdk/token.ts

Fix Lending SDK:
- update comp v3 / lending sdk to populate revenue detail and populate with values.
- update lending SDK in `_reference_`
- Start versioning the lending SDK with version `1.0.1`
Test: https://okgraph.xyz/?q=dmelotik%2Fcompound-v3-ethereum

fix(#patch); comp v3; no null revenueDetail

---

monitor/github.js
monitor/indexingStatus.js
monitor/messageDiscord.js
monitor/protocolLevel.js
monitor/util.js

-Updated GH issue body/title format
-Separated Decentralized GH issue threads from hosted service
-Further redundancy to improve issue posting and fetching already posted issues

fix(#minor); Monitor; v1.3.2 GH issue thread fixes

---

deployment/deployment.json
subgraphs/euler-finance/README.md
subgraphs/euler-finance/protocols/euler-finance/config/deployments/euler-finance-ethereum/configurations.json
subgraphs/euler-finance/src/common/constants.ts
subgraphs/euler-finance/src/mappings/handlers.ts
subgraphs/euler-finance/src/mappings/helpers.ts

This PR fixes inaccurate TVL/borrow balance (#1869) due to [the euler hack on 2023/03/13](https://etherscan.io/tx/0xc310a0affe2169d1f6feec1c63dbc7f7c62a887fa48795d327d4d2da2d6b111d)
- deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/euler-finance-ethereum?version=pending&selected=logs
- dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmaxeJ3MbMPQEoHuuV54jMQn4zUa57d5xW4nZNKhLPPg4A&tab=protocol

fix (#patch); Euler-finance-ethereum; fixed inaccurate TVL/borrow balance #1869

---

subgraphs/aura-finance/protocols/aura-finance/config/deployments/aura-finance-ethereum/configurations.json
subgraphs/aura-finance/src/common/getters.ts

Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Faura-finance-mainnet

fix(#minor); aura-finance; fix out of range indexing error

---

deployment/deployment.json

Marked all Stargate deployments as `prod`

chore(); Update deployment.json; Stargate deployments

---

subgraphs/rocket-pool/protocols/rocket-pool/config/templates/rocket-pool.template.yaml
subgraphs/rocket-pool/src/mappings/rocketMinipoolQueueMapping.ts
subgraphs/rocket-pool/src/mappings/rocketRewardsPoolMapping.ts

Rocketpool was not building from scratch. Needed to update some paths and things

fix(#patch): fix rocketpool build on case sensitive systems

---

deployment/deployment.json
subgraphs/platypus-finance/package-lock.json
subgraphs/platypus-finance/package.json
subgraphs/platypus-finance/protocols/platypus-finance/config/deployments/platypus-finance-avalanche/configurations.json
subgraphs/platypus-finance/protocols/platypus-finance/config/templates/platypus.template.yaml
subgraphs/platypus-finance/src/mappings/masterPlatypus.ts

Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Fplatypus-finance

fix(#minor); platypus-finance; add handler for EmergencyWithdraw

---

deployment/deployment.json
subgraphs/uniswap-forks/protocols/honeyswap/config/deployments/honeyswap-gnosis/configurations.ts
subgraphs/uniswap-forks/protocols/honeyswap/config/deployments/honeyswap-polygon/configurations.ts
subgraphs/uniswap-forks/protocols/honeyswap/src/common/creators.ts

**Context:**
We had two issues out for Honeyswap: #1514 and #1396.
This PR addresses both of these issues.
**Polygon:**
- Updated pool creator in the protocol `src` folder to be up to date with current schema. 
- Added tokens to whitelist to make sure all important tokens/pools are getting priced. 
**Gnosis:**
- Updated WETH whitelist token to be all lowercase.
- Added tokens to whitelist to make sure all important tokens/pools are getting priced.

fix(#minor); Honeyswap; Address Honeyswap issues

---

deployment/deployment.json
subgraphs/abracadabra/package-lock.json
subgraphs/abracadabra/package.json
subgraphs/abracadabra/schema.graphql
subgraphs/abracadabra/src/common/constants.ts
subgraphs/abracadabra/src/common/getters.ts
subgraphs/abracadabra/src/common/metrics.ts
subgraphs/abracadabra/src/common/utils/arrays.ts
subgraphs/abracadabra/src/mapping.ts
subgraphs/abracadabra/src/positions.ts

fix the `cumulativeUniqueUsers` being too low.
Fix: try to create a new account each time an account interacts.
Test:
- https://okgraph.xyz/?q=dmelotik%2Fabracadabra-bsc
- https://okgraph.xyz/?q=dmelotik%2Fabracadabra-arbitrum
- https://okgraph.xyz/?q=dmelotik%2Fabracadabra-avalanche

fix(#patch); abra; cumulative users

---

deployment/deployment.json

Sync complete and passed QA. should be ready for PM.

chore(); Update deployment.json; Aave V2 polygon

---

deployment/deployment.json
subgraphs/uniswap-v3/README.md
subgraphs/uniswap-v3/configurations/configure.ts
subgraphs/uniswap-v3/schema.graphql
subgraphs/uniswap-v3/src/common/dex_event_handler.ts
subgraphs/uniswap-v3/src/common/entities/token.ts
subgraphs/uniswap-v3/src/common/price/price.ts

**Context:**
As per the pricing investigation that is currently underway, we have discovered that many of the pricing issues result from fake versions of tokens. The pool that ends up being the outlier in the instances seen, are often composed of a token that is a fake version of a whitelist token and another token, sometimes fake as well, that has an outlier price. This fix seeks to mitigate pricing issues from these scenarios by not getting USD metrics that contain a fake version of a whitelisted token.

feat(); Uniswap V3; Added fake token detection for more robust pricing

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/interfaces/tabs/PoolTabEntity.tsx

feat(#minor); Dashboard; convert mintSupply values to decimal representation

---

deployment/deployment.json
subgraphs/compound-v3/README.md
subgraphs/compound-v3/abis/Chainlink.json
subgraphs/compound-v3/protocols/compound-v3/config/deployments/compound-v3-polygon/configurations.json
subgraphs/compound-v3/protocols/compound-v3/config/templates/compound.v3.template.yaml
subgraphs/compound-v3/protocols/compound-v3/src/constants.ts
subgraphs/compound-v3/protocols/compound-v3/src/mapping.ts
subgraphs/compound-v3/schema.graphql

Add compound V3 polygon.
Test: https://okgraph.xyz/?q=messari%2Fcompound-v3-polygon

feat(#major); comp v3; add polygon deployment

---

deployment/deployment.json
subgraphs/network/protocols/evm/config/deployments/evm-zksync/configurations.json

Create zkSync Era subgraph using our network schema.
Test: https://okgraph.xyz/?q=QmcASJjRorpBwsdjDGHfewqe9yPtANyNpiAtL73CiUnaGv

feat(#major); zkSync Era network; add subgrah

---

deployment/deployment.json
subgraphs/network/protocols/evm/config/deployments/evm-polygon-zkevm/configurations.json

Add new subgraph.
Test: https://okgraph.xyz/?q=QmWWiEHp4rmo6C6WH8LT49BoSC6KsxH64tozHawNFBY4i8

feat(#major); plygon zkEVM; add new subgraph

---

docs/SCHEMA.md

Add some documentation to describe issues with changing immutable entities on production level subgraphs.

chore(); docs; immutable entities

---

deployment/deployment.json
subgraphs/uniswap-v3-forks/configurations/configurations/configurations.ts
subgraphs/uniswap-v3-forks/configurations/configurations/deploy.ts
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-bsc/configurations.json
subgraphs/uniswap-v3-forks/protocols/uniswap-v3/config/deployments/uniswap-v3-bsc/configurations.ts

**Context:**
Uniswap V3 on Binance Smart Chain has been deployed. This PR simply adds this deployment to the Uniswap V3 Forks code base.
**Deployment:**
https://thegraph.com/hosted-service/subgraph/messari/uniswap-v3-bsc

feat(); Uniswap V3 BSC; Add Uniswap V3 BSC

---

deployment/deployment.json

Update Curve Harmony and Aurora to `prod`

chore(); update Curve deployment status and add new deriv-perp protocols

---

deployment/deployment.json
subgraphs/uniswap-forks/protocols/apeswap/config/deployments/apeswap-bsc/configurations.ts
subgraphs/uniswap-forks/protocols/apeswap/config/deployments/apeswap-polygon/configurations.ts
subgraphs/uniswap-forks/protocols/biswap/config/deployments/biswap-bsc/configurations.ts
subgraphs/uniswap-forks/protocols/mm-finance/config/deployments/mm-finance-polygon/configurations.ts
subgraphs/uniswap-forks/protocols/pangolin/config/deployments/pangolin-avalanche/configurations.ts
subgraphs/uniswap-forks/protocols/quickswap/config/deployments/quickswap-polygon/configurations.ts
subgraphs/uniswap-forks/protocols/solarbeam/config/deployments/solarbeam-moonriver/configurations.ts
subgraphs/uniswap-forks/protocols/spiritswap/config/deployments/spiritswap-fantom/configurations.ts
subgraphs/uniswap-forks/protocols/spookyswap/config/deployments/spookyswap-fantom/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-arbitrum/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-avalanche/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-bsc/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-celo/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-ethereum/configurations.json
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-ethereum/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-fantom/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-fuse/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-gnosis/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-moonbeam/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-moonriver/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-polygon/configurations.ts
subgraphs/uniswap-forks/protocols/trisolaris/config/deployments/trisolaris-aurora/configurations.ts
subgraphs/uniswap-forks/protocols/ubeswap/src/common/constants.ts
subgraphs/uniswap-forks/protocols/uniswap-v2/config/deployments/uniswap-v2-ethereum/configurations.ts

**Context:**
Addressing issue #1969. Just requires simply blacklisting a token causing the TVL outlier brought up in the issue.
Deployment is currently pending:
https://thegraph.com/hosted-service/subgraph/messari/sushiswap-ethereum?version=pending

fix(#minor); Sushiswap Ethereum; Blacklist Deri token causing TVL outlier

---

deployment/deployment.json
subgraphs/stargate/src/mappings/handlers.ts

Test deployment, 
https://okgraph.xyz/?q=dhruv-chauhan%2Fstargate-mainnet

fix(#minor); stargate; Fix transferFrom addresses for bridge transfer-out

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/deployments/DeploymentsPage.tsx
dashboard/src/deployments/DeploymentsTable.tsx
dashboard/src/deployments/IndexingCalls.tsx

fix(#minor); dashboard; derivatives indexing status

---

deployment/deployment.json
schema-dex-amm-extended.graphql
schema-dex-amm.graphql

Update the versions of uniswap forks / schemas with Deecafs changes

chore(); Update uniswap fork versions

---

deployment/deployment.json
subgraphs/compound-v3/README.md
subgraphs/compound-v3/protocols/compound-v3/src/mapping.ts
subgraphs/compound-v3/schema.graphql
subgraphs/compound-v3/src/sdk/manager.ts
subgraphs/compound-v3/src/sdk/position.ts

#2023
This PR adds functionality to compound v3 to allow analytics of interest per position.
This is also partly an experiment to understand how this could work for other lending protocols.
Test:
- https://okgraph.xyz/?q=dmelotik%2Fcompound-v3-polygon
- https://okgraph.xyz/?q=dmelotik%2Fcompound-v3-ethereum

feat(#patch); comp v3; enable interest/pos

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/common/chartComponents/TableEvents.tsx
dashboard/src/queries/dex/poolOverview.ts
dashboard/src/queries/dex/schema.ts

Adds column for reservedAmounts in Events tables (deposit, withdraw, and swaps).

feat(#minor) Dashboard; add support for dex schema v3.0.4

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/constants.ts
dashboard/src/queries/perpetual/schema.ts

see demo for (undeployed) gains-trade subgraph v1.3.1:
polygon: https://okgraph.xyz/?q=QmSNxoxL5PFocyRRja2W2mzfQLD8FNx6nC5P9Hcpr4Pe9e
arbitrum: https://okgraph.xyz/?q=QmdpnsppGcKghriqXt6A92grnaGG4T93FS14rMURTKdXyb

feat(#minor) Dashboard; add support for perpfutures schema v1.3.1

---

subgraphs/_reference_/src/sdk/protocols/perpfutures/README.md
subgraphs/_reference_/src/sdk/protocols/perpfutures/account.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/pool.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/poolSnapshot.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/position.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/protocol.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/protocolSnapshot.ts

fix(#patch); perpfutures; update sdk

---

deployment/deployment.json
subgraphs/compound-v3/protocols/compound-v3/config/deployments/compound-v3-arbitrum/configurations.json
subgraphs/compound-v3/protocols/compound-v3/config/templates/compound.v3.template.yaml
subgraphs/compound-v3/protocols/compound-v3/src/constants.ts
subgraphs/compound-v3/protocols/compound-v3/src/mapping.ts
subgraphs/compound-v3/src/sdk/token.ts

New subgraph: #2131
Test: https://okgraph.xyz/?q=dmelotik%2Fcompound-v3-arbitrum

feat(#major); comp v3; add comp v3 arbitrum

---

deployment/deployment.json
subgraphs/axelar/protocols/axelar/config/deployments/axelar-bsc/configurations.json
subgraphs/axelar/src/mappings.ts
subgraphs/axelar/src/prices/common/constants.ts
subgraphs/axelar/src/prices/config/arbitrum.ts
subgraphs/axelar/src/prices/config/aurora.ts
subgraphs/axelar/src/prices/config/avalanche.ts
subgraphs/axelar/src/prices/config/bsc.ts
subgraphs/axelar/src/prices/config/fantom.ts
subgraphs/axelar/src/prices/config/gnosis.ts
subgraphs/axelar/src/prices/config/harmony.ts
subgraphs/axelar/src/prices/config/mainnet.ts
subgraphs/axelar/src/prices/config/moonbeam.ts
subgraphs/axelar/src/prices/config/optimism.ts
subgraphs/axelar/src/prices/config/polygon.ts
subgraphs/axelar/src/prices/config/template.ts
subgraphs/axelar/src/prices/routers/CurveRouter.ts
subgraphs/axelar/src/prices/routers/UniswapForksRouter.ts
subgraphs/axelar/src/sdk/util/constants.ts
subgraphs/axelar/src/sdk/util/numbers.ts
subgraphs/axelar/src/sdk/util/strings.ts

This PR fixes axelar deployment errors for bsc and avalanche reported in #1628  due to two separate bugs.
- bsc deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/axelar-bsc?version=pending
- bsc dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmeWuhBTWqiHTNHkz56dtNdD3diLFiCNcihx7eXNfYpDXD&tab=protocol
- avalanche deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/axelar-avalanche?version=pending
- avalanche dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/axelar-avalanche&tab=protocol

fix (#patch); axelar-bsc & axelar-avalanche; fixed deployment errors

---

subgraphs/compound-v3/schema.graphql

#2134
Add directives to compound V3 for JS to test

chore(); add directives to comp v3

---

deployment/deployment.json
schema-derivatives-perpfutures.graphql
subgraphs/_reference_/src/sdk/protocols/perpfutures/README.md
subgraphs/_reference_/src/sdk/protocols/perpfutures/account.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/pool.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/poolSnapshot.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/position.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/protocol.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/protocolSnapshot.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/tokens.ts
subgraphs/gains-trade/schema.graphql
subgraphs/gains-trade/src/sdk/protocols/perpfutures/poolSnapshot.ts
subgraphs/gains-trade/src/sdk/protocols/perpfutures/protocolSnapshot.ts
subgraphs/gmx/schema.graphql
subgraphs/gmx/src/entities/snapshots.ts

Deployments,
gains-trade-polygon: https://okgraph.xyz/?q=QmRArrWfB2n3JxDGB1jvWbWRELy9pUCV86wLqEH2TZwCif
gmx-avalanche: https://okgraph.xyz/?q=QmP3YetmbJaWdnBFJqjBfgtcLCthyMK2LtG4zqhvy5njLv

feat(#patch); perpfutures schema; add timestamp field in snapshot entities

---

README.md

Chore(); small change to read me

---

deployment/deployment.json
schema-derivatives-options.graphql
subgraphs/dopex/schema.graphql
subgraphs/dopex/src/entities/snapshots.ts
subgraphs/opyn-gamma/schema.graphql
subgraphs/opyn-gamma/src/entities/snapshot.ts

Deployments,
- dopex-polygon: https://okgraph.xyz/?q=QmaYJdSLLbWppNQtzck7Xwej1XnjunMC6xw2UV7no98KP1
- opyn-gamma-polygon: https://okgraph.xyz/?q=QmdPQMfmCVkLeNcEMCdK1W81M72uByY6rZt9wpe3ovsK4Z

feat(#patch); options schema; add timestamp field in snapshot entities

---

deployment/deployment.json
subgraphs/portal/src/prices/common/constants.ts
subgraphs/portal/src/prices/index.ts

Deployment,
portal-fantom: https://okgraph.xyz/?q=QmZiN2S6horjQfdG2HPCHS9QQ1vFqN6PkwAbZ8KF46SStQ

fix(#minor); portal-fantom; blacklist SFI token on fantom

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/constants.ts
dashboard/src/queries/dex/poolOverview.ts
dashboard/src/queries/dex/schema.ts

Adds support for changes in PR #2172 
Test with deployment, https://okgraph.xyz/?q=QmYq936w7v8fLw12RqGNWH2NT6zhwDe7tyddgeFhDkq2sa

feat(#patch); dashboard; add support for dex-extended schema v4.0.0

---

deployment/deployment.json
subgraphs/uniswap-v3-forks/src/mappings/positionManager.ts

**Context:**
Liquidity was being increased on the DecreaseLiquidity event. This was causing positions not to close as well as an improper balance on the liquidity value of the position. This issue was brought up in #2200.

fix(#minor); Uniswap V3 Forks; Fix liquidity adjustment on DecreaseLiquidityEvent for Positions

---

dashboard/src/common/DashboardVersion.tsx
dashboard/src/constants.ts
dashboard/src/queries/lending/schema.ts

feat(#minor); dashboard; add support for lending schema v3.1.0

---

deployment/deployment.json
subgraphs/_reference_/src/sdk/protocols/lending/account.ts
subgraphs/_reference_/src/sdk/protocols/lending/manager.ts
subgraphs/_reference_/src/sdk/protocols/lending/position.ts
subgraphs/_reference_/src/sdk/protocols/lending/snapshots.ts
subgraphs/_reference_/src/sdk/protocols/lending/token.ts
subgraphs/compound-v3/protocols/compound-v3/src/mapping.ts
subgraphs/compound-v3/schema.graphql
subgraphs/compound-v3/src/sdk/account.ts
subgraphs/compound-v3/src/sdk/constants.ts
subgraphs/compound-v3/src/sdk/manager.ts
subgraphs/compound-v3/src/sdk/position.ts
subgraphs/compound-v3/src/sdk/snapshots.ts
subgraphs/compound-v3/src/sdk/token.ts

#2216
https://okgraph.xyz/?q=dmelotik%2Fcompound-v3-polygon
https://okgraph.xyz/?q=dmelotik%2Fcompound-v3-ethereum
https://okgraph.xyz/?q=dmelotik%2Fcompound-v3-arbitrum
Notes:
- Updated Compound V3 to latest schema `3.1.0`
- Added `isNewMarket` to lending SDK and fixed compile errors
- Updated to newest lending SDK in comp v3
- Fixed issue -> needed to stop overwriting the `borrowIndex` each time the proxy contract for the comet market is deployed...

fix(#patch); comp v3; rev spike bug

---

deployment/deployment.json
subgraphs/uniswap-forks/protocols/mm-finance/config/deployments/mm-finance-polygon/configurations.ts
subgraphs/uniswap-forks/protocols/quickswap/config/deployments/quickswap-polygon/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-harmony/configurations.ts

**Context:**
This PR addresses issues with Quickswap Polygon, Sushiswap Harmony, and MM Finance Polygon outlined in issue #2145.

fix(#minor); Uniswap Forks; Blacklist tokens for Uniswap Forks

---

subgraphs/aave-forks/protocols/radiant-capital-v2/README.md

updated Radiant V2 Readme to reflect 75% protocol and 25% supply side revenue. also brief breakdown of fees.

Chore(#minor); Update Radiant V2 ReadMe

---

deployment/deployment.json
subgraphs/aave-forks/src/constants.ts
subgraphs/aave-forks/src/helpers.ts
subgraphs/aave-forks/src/mapping.ts

fix(#minor); spark lend; revenue issue

---

deployment/deployment.json
subgraphs/aave-forks/README.md
subgraphs/aave-forks/protocols/aave-amm/src/constants.ts
subgraphs/aave-forks/protocols/aave-arc/src/constants.ts
subgraphs/aave-forks/protocols/aave-rwa/src/constants.ts
subgraphs/aave-forks/protocols/aave-v2/src/constants.ts
subgraphs/aave-forks/protocols/aave-v3/config/deployments/aave-v3-metis/configurations.json
subgraphs/aave-forks/protocols/aave-v3/src/constants.ts
subgraphs/aave-forks/protocols/geist-finance/src/constants.ts
subgraphs/aave-forks/protocols/uwu-lend/src/constants.ts
subgraphs/aave-forks/schema.graphql
subgraphs/aave-forks/src/constants.ts

Test: https://andromeda.thegraph.metis.io/subgraphs/name/messari/aave-v3-metis

feat(#major); aave v3; add metis

---

deployment/deployment.json
subgraphs/aave-forks/protocols/aave-v3/config/deployments/aave-v3-polygon/configurations.json
subgraphs/aave-forks/protocols/uwu-lend/README.md

Few things missing:
- Update versions properly
- Update uwu lend readme
- move aave v3 to graft false

chore(); Aave forks; update versions

---

deployment/deployment.json
subgraphs/_reference_/src/sdk/protocols/lending/README.md
subgraphs/_reference_/src/sdk/protocols/lending/account.ts
subgraphs/_reference_/src/sdk/protocols/lending/constants.ts
subgraphs/_reference_/src/sdk/protocols/lending/manager.ts
subgraphs/_reference_/src/sdk/protocols/lending/position.ts
subgraphs/_reference_/src/sdk/protocols/lending/snapshots.ts
subgraphs/_reference_/src/sdk/protocols/lending/token.ts
subgraphs/aave-forks/src/sdk/constants.ts
subgraphs/aave-forks/src/sdk/manager.ts
subgraphs/compound-v3/src/sdk/account.ts
subgraphs/compound-v3/src/sdk/constants.ts
subgraphs/compound-v3/src/sdk/manager.ts
subgraphs/compound-v3/src/sdk/position.ts
subgraphs/compound-v3/src/sdk/snapshots.ts
subgraphs/compound-v3/src/sdk/token.ts
subgraphs/maple-finance-v2/src/sdk/constants.ts
subgraphs/maple-finance-v2/src/sdk/manager.ts

Deployment: [aave-v3-ethereum](https://okgraph.xyz/?q=dhruv-chauhan%2Fdev)
Query,
```
{
revenueDetails(where:{id:"0x018008bfb33d285247a21d44e50697654f754e63"}){
id
sources{id}
amountsUSD
}
markets(where:{id:"0x018008bfb33d285247a21d44e50697654f754e63"}){
cumulativeTotalRevenueUSD
}
}
```
Current response,
```
{
"data": {
"revenueDetails": [
{
"id": "0x018008bfb33d285247a21d44e50697654f754e63",
"sources": [
{
"id": "FLASHLOAN_LP_FEE"
},
{
"id": "FLASHLOAN_PROTOCOL_FEE"
},
{
"id": "LIQUIDATION_FEE"
},
{
"id": "PROTOCOL_FEE"
}
],
"amountsUSD": [
"209449.0708670190758455283707943634",
"1275.844353101844766466648931124586",
"727.197695939703718052098981890776",
"81.159013642003394055614426169224"
]
}
],
"markets": [
{
"cumulativeTotalRevenueUSD": "210954.3262805836456823331490186671"
}
]
}
} …
```

fix(#patch); lending; fix RevenueDetail ordering

---

deployment/deployment.json
subgraphs/gmx-forks/package.json
subgraphs/gmx-forks/protocols/mummy-finance/config/deployments/mummy-finance-arbitrum/configurations.json
subgraphs/gmx-forks/src/common/constants.ts

Test Deployment: https://thegraph.com/hosted-service/subgraph/shashwats22/mummy-finance-arbitrum

feat(#minor); Mummy Finance Subgraph; Add mummy finance arbitrum deployment

---

deployment/deployment.json

Make mummy finance arbitrum prod. passed QA.

chore(): Mummy Finance arbitrum to prod

---

deployment/deployment.json
subgraphs/cbridge/schema.graphql

chore(); bridge mismatch/hop status

---

deployment/deployment.json
subgraphs/uniswap-forks-swap/configurations/configurations/configurations.ts
subgraphs/uniswap-forks-swap/configurations/configurations/deploy.ts
subgraphs/uniswap-forks-swap/protocols/pancakeswap-v2-swap/README.md
subgraphs/uniswap-forks-swap/protocols/pancakeswap-v2-swap/config/deployments/pancakeswap-v2-swap-bsc/configurations.json
subgraphs/uniswap-forks-swap/protocols/pancakeswap-v2-swap/config/deployments/pancakeswap-v2-swap-bsc/configurations.ts
subgraphs/uniswap-forks-swap/protocols/pancakeswap-v2-swap/config/templates/pancakeswap.v2.swap.template.yaml
subgraphs/uniswap-forks-swap/protocols/pancakeswap-v2-swap/src/common/constants.ts

Deployment,
- pancakeswap-v2-swap-bsc: https://okgraph.xyz/?q=dhruv-chauhan%2Fpancakeswap-v2-swap

feat (#major); uniswap-forks; add pancakeswap v2 swap subgraph

---

deployment/deployment.json
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-ethereum/configurations.ts

**Context:** 
These tokens are causing TVL issues.

fix(#minor); Sushiswap Etheruem; Blacklist some tokens

---

deployment/deployment.json
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-arbitrum/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-ethereum/configurations.ts
subgraphs/uniswap-forks/protocols/sushiswap/config/deployments/sushiswap-polygon/configurations.ts

**Context:**
Raised the minimum liquidity threshold for Arbitrum and Ethereum. Also, blacklisted some tokens that were causing issues.

fix(#minor); Sushiswap; Fix some sushiswap deployments

---

deployment/deployment.json
subgraphs/_reference_/src/sdk/protocols/lending/README.md
subgraphs/aave-forks/protocols/aave-amm/src/mapping.ts
subgraphs/aave-forks/protocols/aave-arc/src/mapping.ts
subgraphs/aave-forks/protocols/aave-rwa/src/mapping.ts
subgraphs/aave-forks/protocols/aave-v2/src/mapping.ts
subgraphs/aave-forks/protocols/aave-v3/src/mapping.ts
subgraphs/aave-forks/protocols/geist-finance/src/mapping.ts
subgraphs/aave-forks/protocols/radiant-capital-v2/src/mapping.ts
subgraphs/aave-forks/protocols/radiant-capital/src/mapping.ts
subgraphs/aave-forks/protocols/spark-lend/src/mapping.ts
subgraphs/aave-forks/protocols/uwu-lend/src/mapping.ts
subgraphs/aave-forks/schema.graphql
subgraphs/aave-forks/src/mapping.ts
subgraphs/aave-forks/src/sdk/README.md
subgraphs/aave-forks/src/sdk/account.ts
subgraphs/aave-forks/src/sdk/manager.ts
subgraphs/aave-forks/src/sdk/position.ts
subgraphs/aave-forks/src/sdk/snapshots.ts
subgraphs/aave-forks/src/sdk/token.ts

#2282 
Also:
- Update to latest schema version (no breaking changes to 3.1.0)
- Update to latest SDK
Test:
- https://okgraph.xyz/?q=dmelotik%2Faave-v3-ethereum
- https://okgraph.xyz/?q=dmelotik%2Faave-v3-arbitrum

fix(#patch); aave forks; fix indexing errors

---

deployment/deployment.json
subgraphs/uniswap-forks-swap/abis/quickswap/Factory.json
subgraphs/uniswap-forks-swap/abis/quickswap/Pair.json
subgraphs/uniswap-forks-swap/protocols/quickswap-swap/config/deployments/quickswap-swap-polygon/configurations.json
subgraphs/uniswap-forks-swap/src/common/getters.ts

Made the early return on bad tokens before calling the token data.
grafting: https://okgraph.xyz/?q=messari%2Fquickswap-swap-polygon

fix(#patch); quickswap; swap only error

---

deployment/deployment.json
subgraphs/vesta-finance/protocols/vesta-finance/config/deployments/vesta-finance-arbitrum/configurations.json
subgraphs/vesta-finance/protocols/vesta-finance/config/templates/vesta.finance.template.yaml
subgraphs/vesta-finance/src/utils/logs.ts

Deployment,
vesta-finance-arbitrum: https://okgraph.xyz/?q=dhruv-chauhan%2Fvesta-finance-arbitrum

fix(#minor); vesta-finance; add check for failing ethereum.decode

---

deployment/deployment.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-arbitrum/configurations.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-arbitrum/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-ethereum/configurations.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-ethereum/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-optimism/configurations.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-optimism/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-polygon/configurations.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-polygon/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-xdai/configurations.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-xdai/configurations.ts
subgraphs/hop-protocol/src/sdk/util/constants.ts

Deployments,
- hop-protocol-arbitrum: https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-arbitrum-graft
- hop-protocol-ethereum: https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-ethereum-graft
- hop-protocol-optimism: https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-optimism-graft
- hop-protocol-polygon: https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-polygon-graft
- hop-protocol-xdai: https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-xdai-graft

fix(#minor); hop-protocol; add Base config

---

deployment/deployment.json
subgraphs/uniswap-forks-swap/configurations/configurations/configurations.ts
subgraphs/uniswap-forks-swap/configurations/configurations/deploy.ts
subgraphs/uniswap-forks-swap/protocols/baseswap-swap/README.md
subgraphs/uniswap-forks-swap/protocols/baseswap-swap/config/deployments/baseswap-swap-base/configurations.json
subgraphs/uniswap-forks-swap/protocols/baseswap-swap/config/deployments/baseswap-swap-base/configurations.ts
subgraphs/uniswap-forks-swap/protocols/baseswap-swap/config/templates/baseswap.swap.template.yaml
subgraphs/uniswap-forks-swap/protocols/baseswap-swap/src/common/constants.ts
subgraphs/uniswap-forks-swap/schema.graphql
subgraphs/uniswap-forks-swap/src/common/constants.ts
subgraphs/uniswap-v3-forks-swap/abis/uniswap-v3/Factory.json
subgraphs/uniswap-v3-forks-swap/abis/uniswap-v3/Pool.json
subgraphs/uniswap-v3-forks-swap/configurations/configurations/configurations.ts
subgraphs/uniswap-v3-forks-swap/configurations/configurations/deploy.ts
subgraphs/uniswap-v3-forks-swap/protocols/sushiswap-v3-swap/README.md
subgraphs/uniswap-v3-forks-swap/protocols/sushiswap-v3-swap/config/deployments/sushiswap-v3-swap-base/configurations.json
subgraphs/uniswap-v3-forks-swap/protocols/sushiswap-v3-swap/config/deployments/sushiswap-v3-swap-base/configurations.ts
subgraphs/uniswap-v3-forks-swap/protocols/sushiswap-v3-swap/config/templates/sushiswap.v3.swap.template.yaml
subgraphs/uniswap-v3-forks-swap/protocols/sushiswap-v3-swap/src/common/constants.ts
subgraphs/uniswap-v3-forks-swap/protocols/uniswap-v3-swap/README.md
subgraphs/uniswap-v3-forks-swap/protocols/uniswap-v3-swap/config/deployments/uniswap-v3-swap-base/configurations.json
subgraphs/uniswap-v3-forks-swap/protocols/uniswap-v3-swap/config/deployments/uniswap-v3-swap-base/configurations.ts
subgraphs/uniswap-v3-forks-swap/protocols/uniswap-v3-swap/config/templates/uniswap.v3.swap.template.yaml
subgraphs/uniswap-v3-forks-swap/protocols/uniswap-v3-swap/src/common/constants.ts
subgraphs/uniswap-v3-forks-swap/schema.graphql
subgraphs/uniswap-v3-forks-swap/src/common/constants.ts

Deployments,
- baseswap-swap-base: [deployment](https://okgraph.xyz/?q=QmQVCh63Ez4yvCpA3JLT8fqcvWpZdU7bbV8AQMR57u6M53), [query](https://api.thegraph.com/subgraphs/id/QmQVCh63Ez4yvCpA3JLT8fqcvWpZdU7bbV8AQMR57u6M53/graphql?query=%7B%0A++swaps%28orderBy%3A+timestamp%2C+orderDirection%3A+desc%29+%7B%0A++++id%0A++++hash%0A++++logIndex%0A++++protocol%7Bid%7D%0A++++to%0A++++from%0A++++blockNumber%0A++++timestamp%0A++++tokenIn%7Bid%7D%0A++++amountIn%0A++++amountInUSD%0A++++tokenOut%7Bid%7D%0A++++amountOut%0A++++amountOutUSD%0A++++reserveAmounts%0A++++pool%7Bid%7D%0A++%7D%0A%7D)
- uniswap-v3-swap-base: [deployment](https://okgraph.xyz/?q=QmRHx5owFg1QkHcTHpwoEniz5UxaQqGJv39LJfaNwFwpVe), [query](https://api.thegraph.com/subgraphs/id/QmeV1qdv6dqpM72vzz5uPVJh51WG8fbHeyCvxoz4xVcJc7/graphql?query=%7B%0A+ …

chore(); uniswap-forks; add uniswap forks swap subgraphs on base

---

deployment/deployment.json

Reverts messari/subgraphs#2330

Revert "chore(); uni v2 substream; add deployument info"

---

deployment/deployment.json

Had to revert the last one, but this should work with the `hosted-service` in the deployment

chore(); substream uni v2 eth; add deployment

---

deployment/deployment.json
subgraphs/compound-v3/README.md
subgraphs/compound-v3/protocols/compound-v3/config/deployments/compound-v3-base/configurations.json
subgraphs/compound-v3/protocols/compound-v3/src/constants.ts
subgraphs/compound-v3/schema.graphql
subgraphs/compound-v3/src/sdk/constants.ts

Add Compound V3 Base Subgraph
https://api.studio.thegraph.com/query/32057/compound-v3-base/version/latest

feat(#major); comp v3; add base config

---

deployment/deployment.json
schema-dex-amm.graphql
subgraphs/uniswap-forks/configurations/configurations/configurations.ts
subgraphs/uniswap-forks/configurations/configurations/deploy.ts
subgraphs/uniswap-forks/protocols/baseswap/README.md
subgraphs/uniswap-forks/protocols/baseswap/config/deployments/baseswap-base/configurations.json
subgraphs/uniswap-forks/protocols/baseswap/config/deployments/baseswap-base/configurations.ts
subgraphs/uniswap-forks/protocols/baseswap/config/templates/baseswap.template.yaml
subgraphs/uniswap-forks/protocols/baseswap/src/common/constants.ts
subgraphs/uniswap-forks/schema.graphql
subgraphs/uniswap-forks/src/common/constants.ts

**Context:**
This PR integrates BaseSwap Base subgraph into the Uniswap Forks folder. This is a simple integration and works just like Uniswap V2. 
**Note:**
The protocol collects all of the fees (0.25% of swap). The LPs are reimbursed through staking in the MasterChef contract. This PR is not yet going to account for rewards earned through the MasterChef contract. Just the core functionality of the DEX.

feat(); Baseswap Base; Add Baseswap Base Subgraph

---

deployment/deployment.json
subgraphs/_reference_/src/sdk/protocols/lending/README.md
subgraphs/_reference_/src/sdk/protocols/lending/account.ts
subgraphs/_reference_/src/sdk/protocols/lending/manager.ts
subgraphs/_reference_/src/sdk/protocols/lending/position.ts
subgraphs/_reference_/src/sdk/protocols/lending/snapshots.ts
subgraphs/_reference_/src/sdk/protocols/lending/token.ts
subgraphs/aave-forks/package.json
subgraphs/aave-forks/protocols/aave-v3/config/deployments/aave-v3-polygon/configurations.json
subgraphs/aave-forks/protocols/aave-v3/src/mapping.ts
subgraphs/aave-forks/protocols/spark-lend/src/mapping.ts
subgraphs/aave-forks/schema.graphql
subgraphs/aave-forks/src/helpers.ts
subgraphs/aave-forks/src/sdk/README.md
subgraphs/aave-forks/src/sdk/account.ts
subgraphs/aave-forks/src/sdk/manager.ts
subgraphs/aave-forks/src/sdk/position.ts
subgraphs/aave-forks/src/sdk/snapshots.ts
subgraphs/aave-forks/src/sdk/token.ts

Deployments,
- aave-v2-ethereum: https://okgraph.xyz/?q=QmQVb2SVgVRVyncMMCtg5XUuHcT2qXS7Xs4EpAFTh9XkaR
- aave-v3-arbitrum: https://okgraph.xyz/?q=QmQKQa6yWE4sUGqfhnHkvxm9eWmFhpAxch1fhqg86C1Ja6
- aave-v3-polygon: https://okgraph.xyz/?q=QmYT5Dgm9qdHBVExzbWHGZiAzvR8HcSHk5CyZiVrX8c7Uf
- spark-lend-ethereum: https://okgraph.xyz/?q=QmZncnZ8hnPSua1zN93mgqbGmJMYxJex6kUQFwRyhcayjC

fix(#minor); aave-forks; fix aave indexing errors

---

deployment/deployment.json
schema-lending.graphql
subgraphs/aave-forks/protocols/aave-v3/config/deployments/aave-v3-base/configurations.json
subgraphs/aave-forks/protocols/aave-v3/src/constants.ts
subgraphs/aave-forks/schema.graphql
subgraphs/aave-forks/src/constants.ts

Adding Aave V3 Base
deployment: https://okgraph.xyz/?q=messari%2Faave-v3-base

feat(#major); aave v3; add base subgraph

---

subgraphs/_reference_/schema.graphql
subgraphs/_reference_/src/common/constants.ts
subgraphs/_reference_/src/common/rewards.ts
subgraphs/_reference_/src/sdk/util/constants.ts
subgraphs/_reference_/src/sdk/util/rewards.ts
subgraphs/stargate/src/sdk/util/rewards.ts

- Error: missing Base's network key in getStartingBlockRate()
- Fix: Since Base is built on OP stack, it shall have the same block rate as Optimism
- Deployments: 
- https://okgraph.xyz/?q=dhruv-chauhan%2Fstargate-base

fix(#patch); stargate-base; add Base's block rate

---

deployment/deployment.json
subgraphs/_reference_/src/sdk/protocols/lending/README.md
subgraphs/_reference_/src/sdk/protocols/lending/account.ts
subgraphs/_reference_/src/sdk/protocols/lending/manager.ts
subgraphs/_reference_/src/sdk/protocols/lending/position.ts
subgraphs/_reference_/src/sdk/protocols/lending/snapshots.ts
subgraphs/_reference_/src/sdk/protocols/lending/token.ts
subgraphs/aave-forks/src/helpers.ts
subgraphs/aave-forks/src/mapping.ts
subgraphs/aave-forks/src/sdk/README.md
subgraphs/aave-forks/src/sdk/account.ts
subgraphs/aave-forks/src/sdk/manager.ts
subgraphs/aave-forks/src/sdk/position.ts
subgraphs/aave-forks/src/sdk/snapshots.ts
subgraphs/aave-forks/src/sdk/token.ts

- Deployments: 
- aave-v3-ethereum: https://okgraph.xyz/?q=dhruv-chauhan%2Faave-v3-ethereum
- Query: https://api.thegraph.com/subgraphs/id/Qmf8HepXi9oRSMDZthCtW7bGzX96A1R5VHj1jNoHLhHtEv/graphql?query=%7B%0A++positions%7B%0A++++id%0A++++account%7Bid%7D%0A++++balance%0A++++principal%0A++%7D%0A%7D

feat(#minor); aave-forks; add principal amounts in positions

---

deployment/deployment.json
subgraphs/uniswap-v3-forks-swap/configurations/configurations/configurations.ts
subgraphs/uniswap-v3-forks-swap/configurations/configurations/deploy.ts
subgraphs/uniswap-v3-forks-swap/protocols/uniswap-v3-swap/config/deployments/uniswap-v3-swap-optimism/configurations.json
subgraphs/uniswap-v3-forks-swap/protocols/uniswap-v3-swap/config/deployments/uniswap-v3-swap-optimism/configurations.ts

Adding Uniswap V3 Swap only subgraph and deployed.
https://okgraph.xyz/?q=messari%2Funiswap-v3-swap-optimism

feat(#major); uni v3; add uniswap v3 optimism swap only

---

docs/TOOLING.md

Adding documentation on how to query the status endpoint.

chore(); docs; add status endpoint docs

---

deployment/deployment.json
subgraphs/curve-finance/protocols/curve-finance/config/deployments/curve-finance-ethereum/configurations.json
subgraphs/curve-finance/src/prices/config/mainnet.ts

Deployments:
Curve Finance Ethereum (grafted at 14801795): https://okgraph.xyz/?q=messari%2Fcurve-finance-ethereum

fix(#patch); Curve Finance; Fix spike in TVL

---

deployment/deployment.json
subgraphs/goldfinch/package-lock.json
subgraphs/goldfinch/package.json
subgraphs/goldfinch/protocols/goldfinch/config/deployments/goldfinch-ethereum/configurations.json
subgraphs/goldfinch/src/mappings/callable_loan/helpers.ts

- Issue: 
- `assert(PoolToken.load(poolTokenIds[i]))` fails
- `PoolToken` with id: 943 was removed from store here: https://github.com/messari/subgraphs/blob/master/subgraphs/goldfinch/src/mappings/pool_tokens.ts#L25
- `callableLoan.tokens` stores reference to `PoolToken`. Iterating over this array in code still shows the removed token Id.
- Deployment:
- goldfinch-ethereum: https://okgraph.xyz/?q=dhruv-chauhan%2Fgoldfinch-ethereum

fix(#patch); goldfinch; check if PoolToken exists

---

deployment/deployment.json

- all swap subgraphs to prod
- Fix schema versions on uniswap-v3-forks-swap
- Deploy:
- https://okgraph.xyz/?q=messari%2Funiswap-v3-swap-base
- https://okgraph.xyz/?q=messari%2Fsushiswap-v3-swap-base
- https://okgraph.xyz/?q=messari%2Fbaseswap-swap-base

chore(); all swap subgraphs to `prod`

---

monitor/README.md
monitor/clear.js
monitor/errorSchemas.js
monitor/github.js
monitor/indexingStatus.js
monitor/messageDiscord.js
monitor/poolLevel/dexPoolLevel.js
monitor/poolLevel/lendingPoolLevel.js
monitor/poolLevel/vaultPoolLevel.js
monitor/protocolLevel.js
monitor/resolutions.js
monitor/script.js
monitor/util.js

... also add constants for big numbers

fix(#minor); monitor; ignore posting protocol errors for swap-only subgraphs

---

deployment/deployment.json
subgraphs/uniswap-v3-forks-swap/src/common/dexEventHandler.ts
subgraphs/uniswap-v3-forks-swap/src/common/entities/account.ts
subgraphs/uniswap-v3-forks-swap/src/mappings/core.ts

- Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Fpancakeswap-v3-swap-bsc
- Query: https://api.thegraph.com/subgraphs/id/QmdAVTee8dUNHYpsKuevdioSmPQSB9f5BVUCEuxWd2RBrJ/graphql?query=%7B%0A++swaps+%7B%0A++++protocol+%7B%0A++++++id%0A++++%7D%0A++++pool+%7B%0A++++++id%0A++++%7D%0A++++tokenIn+%7B%0A++++++id%0A++++%7D%0A++++tokenOut+%7B%0A++++++id%0A++++%7D%0A++++account+%7B%0A++++++id%0A++++++swapCount%0A++++++swaps%7Bid%7D%0A++++%7D%0A++%7D%0A%7D

fix(#patch); uniswap-v3-forks; create, update account entity on Swap

---

monitor/indexingStatus.js

*need to update `GRAPH_API_KEY` in .env while deploying*

chore(); monitor; update decentralized network deployments endpoint

---

deployment/deployment.json
subgraphs/uniswap-forks/protocols/apeswap/config/deployments/apeswap-bsc/configurations.ts
subgraphs/uniswap-forks/protocols/apeswap/config/templates/apeswap.bsc.template.yaml
subgraphs/uniswap-forks/protocols/apeswap/config/templates/apeswap.matic.template.yaml

Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Fapeswap-bsc

fix(#patch); apeswap-bsc; add BBQ to untracked tokens

---

deployment/deployment.json

**Context:**
Add Trader Joe deployment and update Radiant Capital to decentralized network in the deployment.json

chore(); decentralized network; Add trader joe and update radiant capital decentralized network in deployment.json

---

deployment/deployment.json
subgraphs/_reference_/src/prices/common/constants.ts
subgraphs/_reference_/src/prices/config/mainnet.ts
subgraphs/convex-finance/src/prices/config/mainnet.ts

Deployment: https://okgraph.xyz/?q=dhruv-chauhan/convex-finance-ethereum

fix(#patch); convex-finance; add mispriced factory pools' LP tokens to CurveFactoryPoolOverride

---

deployment/deployment.json
subgraphs/portal/package.json
subgraphs/portal/src/prices/common/constants.ts

Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Fportal-polygon

fix(#patch); portal-polygon; blacklist ESMPTOKIN token

---

deployment/deployment.json
subgraphs/_reference_/src/sdk/protocols/perpfutures/README.md
subgraphs/_reference_/src/sdk/protocols/perpfutures/account.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/pool.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/poolSnapshot.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/position.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/protocol.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/protocolSnapshot.ts
subgraphs/_reference_/src/sdk/protocols/perpfutures/tokens.ts
subgraphs/kwenta/schema.graphql

Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Fkwenta-optimism

chrore(); perpfutures-sdk; fix activeLiquidators count / upgrade kwenta to latest schema

---

deployment/deployment.json
subgraphs/hop-protocol/package-lock.json
subgraphs/hop-protocol/package.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-arbitrum/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-ethereum/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-optimism/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-polygon/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-xdai/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/src/L2/reward.ts
subgraphs/hop-protocol/protocols/hop-protocol/src/mainnet/bridge.ts
subgraphs/hop-protocol/src/sdk/util/constants.ts
subgraphs/hop-protocol/src/sdk/util/rewards.ts
subgraphs/hop-protocol/yarn.lock

Deployments,
(grafted)
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-arbitrum-graft
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-ethereum-graft
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-optimism-graft
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-polygon-graft
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-xdai-graft
(complete)
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-arbitrum
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-ethereum
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-optimism
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-polygon
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-xdai

fix(#patch); hop-protocol; Add config for Linea, update reward tokens

---

deployment/deployment.json
subgraphs/governor-alpha-bravo/abis/hifi-governance/GovernorBravoDelegate.json
subgraphs/governor-alpha-bravo/abis/hifi-governance/Hifi.json
subgraphs/governor-alpha-bravo/protocols/hifi-governance/config/deployments/hifi-governance-ethereum/configurations.json
subgraphs/governor-alpha-bravo/protocols/hifi-governance/config/templates/hifi-governance.template.yaml
subgraphs/governor-alpha-bravo/protocols/hifi-governance/src/governor-bravo-delegate.ts
subgraphs/governor-alpha-bravo/protocols/hifi-governance/src/hifi.ts

**Description**
Add governance subgraph for Hifi DAO. The subgraph is based on Governor Bravo
**Links**
https://okgraph.xyz/?q=messari%2Fhifi-governance

feat(#major); Hifi DAO; Add governance subgraph

---

deployment/deployment.json

https://okgraph.xyz/?q=QmZLVU1Y6WiHU3aWz2udzuxzWTzjDcDecPffatM5fX39Sn

chore(); friend tech; add dec network

---

deployment/deployment.json
subgraphs/eigenlayer/schema.graphql

https://okgraph.xyz/?q=messari%2Fpancakeswap-v3-swap-ethereum

chore(); fix eigenlayer / pancake versions

---

deployment/deployment.json
subgraphs/portal/package-lock.json
subgraphs/portal/protocols/portal/config/deployments/portal-ethereum/configurations.json
subgraphs/portal/src/prices/common/constants.ts

- Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Fportal-mainnet

fix(#patch); portal-ethereum; add BFL to BLACKLIST_TOKENS list

---

deployment/deployment.json

Missed updating subgraph versions for PR #2466

feat(#minor); abracadabra; update abracadabra subgraph versions

---

deployment/deployment.json
subgraphs/hop-protocol/configurations/configurations/deploy.ts
subgraphs/hop-protocol/configurations/configurations/interface.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-arbitrum/configurations.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-arbitrum/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-ethereum/configurations.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-ethereum/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-optimism/configurations.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-optimism/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-polygon-zkevm/configurations.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-polygon-zkevm/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-polygon/configurations.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-polygon/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-xdai/configurations.json
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-xdai/configurations.ts
subgraphs/hop-protocol/schema.graphql
subgraphs/hop-protocol/src/sdk/util/constants.ts

- Add config for newly added Polygon zkEVM network to bridge
- Deployments (grafted)
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-arbitrum-graft
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-ethereum-graft
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-optimism-graft
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-polygon-graft
- https://okgraph.xyz/?q=dhruv-chauhan%2Fhop-protocol-xdai-graft

fix(#patch); hop-protocol; Add config for Polygon zkEVM network

---

deployment/deployment.json
subgraphs/balancer-forks/protocols/balancer-v2/config/deployments/balancer-v2-ethereum/configurations.json

The purpose of this PR is to deploy some subgraphs to the decentralized network. This includes new subgraphs for newly supported networks like BSC and base, and some deployments for existing decentralized network protocols. 
**Note:**
- Balancer V2 had its version updated and re-deployed. Presuming current error is due to grafting
- Goldfinch somehow had its version greater on the decentralized network causing it to be OOS. The version update is just to sync these.

feat(); DAT-2087; deploy subgraphs to decentralized network 

---

subgraphs/hop-protocol/configurations/configurations/configurations.ts
subgraphs/hop-protocol/protocols/hop-protocol/config/deployments/hop-protocol-polygon-zkevm/configurations.ts
subgraphs/hop-protocol/src/sdk/util/rewards.ts

Deployment: https://thegraph.com/studio/subgraph/hop-protocol-polygon-zkevm/playground

feat(#major); hop-protocol-polygon-zkevm; fix missing configs

---

docs/RESOURCES.md

https://github.com/messari/subgraphs/issues/2495

chore(); remove broken link

---

.github/workflows/build-checker.yaml
deployment/deployment.json
package-lock.json
package.json
subgraphs/uniswap-forks-swap/configurations/configurations/configurations.ts
subgraphs/uniswap-forks-swap/configurations/configurations/deploy.ts
subgraphs/uniswap-forks-swap/package-lock.json
subgraphs/uniswap-forks-swap/package.json
subgraphs/uniswap-forks-swap/protocols/spookyswap-swap/README.md
subgraphs/uniswap-forks-swap/protocols/spookyswap-swap/config/deployments/spookyswap-swap-fantom/configurations.json
subgraphs/uniswap-forks-swap/protocols/spookyswap-swap/config/deployments/spookyswap-swap-fantom/configurations.ts
subgraphs/uniswap-forks-swap/protocols/spookyswap-swap/config/templates/spookyswap.swap.template.yaml
subgraphs/uniswap-forks-swap/protocols/spookyswap-swap/src/common/constants.ts

Adding spookyswap swap only subgraph
https://okgraph.xyz/?q=messari%2Fspookyswap-swap-fantom

feat(); spookyswap fantom; add swap only subgraph

---

deployment/deployment.json
subgraphs/aave-forks/protocols/aave-v3/config/deployments/aave-v3-bsc/configurations.json
subgraphs/aave-forks/protocols/aave-v3/config/deployments/aave-v3-gnosis/configurations.json
subgraphs/aave-forks/protocols/aave-v3/config/deployments/aave-v3-scroll/configurations.json
subgraphs/aave-forks/protocols/aave-v3/src/constants.ts
subgraphs/aave-forks/src/constants.ts

-Deployments:
- gnosis: https://okgraph.xyz/?q=dhruv-chauhan%2Faave-v3-gnosis
- bsc: https://okgraph.xyz/?q=dhruv-chauhan%2Faave-v3-bsc
- scroll: 
- To fix build failure: https://github.com/messari/subgraph-cli/pull/17

feat(#major); aave-v3; add network configs - gnosis, bsc, scroll

---

docs/ERRORS.md
subgraphs/aave-forks/src/helpers.ts
subgraphs/gmx-forks/protocols/mummy-finance/README.md
subgraphs/orbit/src/sdk/README.md

chore: fix typos

---

deployment/deployment.json
subgraphs/compound-v3/package-lock.json
subgraphs/compound-v3/package.json
subgraphs/compound-v3/protocols/compound-v3/config/deployments/compound-v3-arbitrum/configurations.json
subgraphs/compound-v3/protocols/compound-v3/config/deployments/compound-v3-base/configurations.json
subgraphs/compound-v3/protocols/compound-v3/config/deployments/compound-v3-ethereum/configurations.json
subgraphs/compound-v3/protocols/compound-v3/config/deployments/compound-v3-polygon/configurations.json
subgraphs/compound-v3/protocols/compound-v3/src/mapping.ts

- Deployment ID (studio): QmPSrf5TWCDYBo9tfM39765gAeeUMC47seCNng1aySvtCj
(https://subgraphs.messari.io/subgraph?endpoint=QmPSrf5TWCDYBo9tfM39765gAeeUMC47seCNng1aySvtCj&tab=protocol)

fix(#patch); compound-v3-base; indexing error due to empty log.topics

---

deployment/deployment.json
subgraphs/aave-forks/protocols/aave-amm/config/templates/aave.amm.template.yaml
subgraphs/aave-forks/protocols/aave-arc/config/templates/aave.arc.template.yaml
subgraphs/aave-forks/protocols/aave-rwa/config/templates/aave.rwa.template.yaml
subgraphs/aave-forks/protocols/aave-v2/config/templates/aave.v2.template.yaml
subgraphs/aave-forks/protocols/aave-v3/config/templates/aave.v3.template.yaml
subgraphs/aave-forks/protocols/geist-finance/config/templates/geist.finance.template.yaml
subgraphs/aave-forks/protocols/radiant-capital-v2/config/templates/radiant.capital.v2.template.yaml
subgraphs/aave-forks/protocols/radiant-capital/config/templates/radiant.capital.template.yaml
subgraphs/aave-forks/protocols/spark-lend/config/templates/spark.lend.template.yaml
subgraphs/aave-forks/protocols/uwu-lend/config/templates/uwu.lend.template.yaml
subgraphs/aave-forks/schema.graphql
subgraphs/aave-forks/src/mapping.ts
subgraphs/aave-forks/src/sdk/README.md
subgraphs/aave-forks/src/sdk/account.ts
subgraphs/aave-forks/src/sdk/constants.ts
subgraphs/aave-forks/src/sdk/manager.ts
subgraphs/aave-forks/src/sdk/position.ts
subgraphs/aave-forks/src/sdk/snapshots.ts
subgraphs/aave-forks/src/sdk/token.ts

- Deployments:
- aave-v3-ethereum: https://okgraph.xyz/?q=dhruv-chauhan%2Faave-v3-ethereum
- spark-lend-ethereum: https://okgraph.xyz/?q=dhruv-chauhan%2Fspark-lend-ethereum

feat(#minor); aave-forks; add usage on tx signers

---

deployment/deployment.json
subgraphs/aave-forks/src/mapping.ts

**Describe the PR**
- Fixed and simplified the aave v3 flashloan revenue logic
**Links**
- https://okgraph.xyz/?q=melotik%2Faave-v3-ethereum-1
- https://github.com/aave/aave-v3-core/blob/724a9ef43adf139437ba87dcbab63462394d4601/contracts/protocol/libraries/logic/FlashLoanLogic.sol#L242C34-L242C51

fix(#minor); aave v3 forks; fix flashloan revennue

---

docs/ISSUES.md

- Fixing broken hyperlink that 404s

Fix Broken Hyperlink in ISSUES.md

---

deployment/deployment.json

Update radiant v2 status since many of the metrics are wrong due to https://github.com/messari/subgraphs/issues/2402

Update radiant v2 status

---

monitor/Dockerfile

[DAT-2640]; Remove * to prevent cp of package-lock.json

---

deployment/deployment.json

https://thegraph.com/explorer/subgraphs/9jLaSWECnXdmwDG6zGMR39PqwhscHoiLGoX1mLtHLqWd?view=Overview&chain=arbitrum-one

chore(); belt finance; update query id

---

deployment/deployment.json
subgraphs/compound-v3/package-lock.json
subgraphs/compound-v3/protocols/compound-v3/config/templates/compound.v3.template.yaml
subgraphs/compound-v3/protocols/compound-v3/src/mapping.ts
subgraphs/compound-v3/schema.graphql
subgraphs/compound-v3/src/sdk/constants.ts
subgraphs/compound-v3/src/sdk/manager.ts
subgraphs/compound-v3/src/sdk/snapshots.ts

- Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Fcompound-v3-ethereum

feat(#minor); compound-v3; add usage on tx signers

---

deployment/deployment.json
subgraphs/makerdao/package-lock.json
subgraphs/makerdao/package.json
subgraphs/makerdao/protocols/makerdao/config/templates/makerdao.template.yaml
subgraphs/makerdao/schema.graphql
subgraphs/makerdao/src/common/getters.ts
subgraphs/makerdao/src/common/helpers.ts
subgraphs/makerdao/yarn.lock

- Deployment: https://okgraph.xyz/?q=dhruv-chauhan%2Fmakerdao-ethereum

feat(#minor); makedao; add usage on tx signers

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/subgraph_qa.md

Make Ishraq the automatic assignee for issues

Update Issue Assignee

---

deployment/deployment.json

- Update deployment.json with the subgraph ids of the decentralized network governance subgraphs

#feat(minor); Governance Subgraphs; Deployment updates

---

deployment/deployment.json
subgraphs/morpho/package-lock.json
subgraphs/morpho/package.json
subgraphs/morpho/protocols/morpho-aave-v2/config/templates/morpho.aave.v2.template.yaml
subgraphs/morpho/protocols/morpho-compound/config/templates/morpho.compound.template.yaml
subgraphs/morpho/schema.graphql
subgraphs/morpho/src/helpers.ts
subgraphs/morpho/src/mapping/common.ts
subgraphs/morpho/src/mapping/morpho-aave-v2/handleMarketCreated.ts
subgraphs/morpho/src/mapping/morpho-compound/handleMarketCreated.ts
subgraphs/morpho/src/utils/initializers.ts

- Deployment: 
- https://okgraph.xyz/?q=dhruv-chauhan%2Fmorpho-aave-v2-ethereum
- https://okgraph.xyz/?q=dhruv-chauhan%2Fmorpho-compound-ethereum

feat(#minor); morpho-optimizers; add usage on tx signers

---

subgraphs/_reference_/src/sdk/protocols/generic/account.ts
subgraphs/_reference_/src/sdk/protocols/generic/index.ts
subgraphs/_reference_/src/sdk/protocols/generic/pool.ts
subgraphs/_reference_/src/sdk/protocols/generic/poolSnapshot.ts
subgraphs/_reference_/src/sdk/protocols/generic/protocol.ts
subgraphs/_reference_/src/sdk/protocols/generic/protocolSnapshot.ts
subgraphs/_reference_/src/sdk/protocols/generic/tokens.ts

- Simplified the Generic SDK to match the latest version of the Generic Schema (`v3.0.0`).

feat(); Generic Schema SDK v3.0.0; Simplify Generic SDK 

---

subgraphs/_reference_/src/prices/common/utils.ts
subgraphs/_reference_/src/prices/config/base.ts
subgraphs/_reference_/src/prices/config/mode.ts
subgraphs/_reference_/src/prices/config/polygon_zkevm.ts
subgraphs/_reference_/src/prices/config/scroll.ts
subgraphs/_reference_/src/prices/config/zksync_era.ts

Add support for the following networks in the price lib.
- Mode
- zkSync Era
- Polygon zkEVM
- Base Mainnet
- Scroll Mainnet

feat(#minor); Price Lib; Add Pricing Support For Remaining DN Networks

---

subgraphs/_reference_/src/prices/common/utils.ts
subgraphs/_reference_/src/prices/config/linea.ts

Add support for `linea` network to the subgraph price lib.

feat(#minor); Price Lib; Add Linea network 

---

deployment/deployment.json

- Add Cygnus and Ring Few DN deployments
- Add QiDao Base
- Update DN query URLs for ENS and Euler Gov

[2024-07-04]; Add DN deployements

---

deployment/produce_decentralized_network_csv.py

**Context:**
Adding deployment statistics to the script which produces a deployment.csv.

Add deployment statistics to deployment CSV script

---

deployment/deployment.json

**Context:**
I deployed all new subgraphs to the Arbitrum DN and added the query IDs to the deployment.json. 
Added:
- Symbiotic Ethereum
- Hyperlock Finance Blast
- Amphor Ethereum
- Zircuit Staking Ethereum
- Lybra Finance Ethereum
- Kelp DAO Ethereum
- Stream Finance Ethereum
- Umami Finance Arbitrum
- Chainlink Staking Ethereum
- Liquid Collective Ethereum

feat(#minor); [2024-08-01] Monthly DN Deployments

---

deployment/deployment.json

Added: 
- POWH3D Ethereum
- Nexus Mutual Ethereum
- YieldYak Staked Avax Avalanche
- Blackwing Ethereum/Arbitrum/BSC
- Cream ETH 2 Ethereum
- Staked Celo Celo
- Hord.Fi Ethereum
- Anzen V2 Ethereum/Base/Blast
- MEV Protocol Ethereum
- Geode Avalanche
- BeethovenX SFTMX Fantom
- Stakewise V2 Ethereum/Gnosis
- Suzaku Avalanche
- DEQ Fi Ethereum
- Aspida Ethereum
- Yieldnest Ethereum/BSC
- Inception Ethereum
- Aqua Patina Ethereum

Add Query IDs for DN deployments

---

deployment/deployment.json
subgraphs/uniswap-v3-forks/configurations/configurations/configurations.ts
subgraphs/uniswap-v3-forks/configurations/configurations/deploy.ts
subgraphs/uniswap-v3-forks/package-lock.json
subgraphs/uniswap-v3-forks/package.json
subgraphs/uniswap-v3-forks/protocols/iguanadex-v3/config/deployments/iguanadex-v3-etherlink-mainnet/configurations.json
subgraphs/uniswap-v3-forks/protocols/iguanadex-v3/config/deployments/iguanadex-v3-etherlink-mainnet/configurations.ts
subgraphs/uniswap-v3-forks/protocols/iguanadex-v3/config/templates/iguanadexV3Template.yaml
subgraphs/uniswap-v3-forks/protocols/iguanadex-v3/src/common/constants.ts
subgraphs/uniswap-v3-forks/protocols/iguanadex-v3/src/core.ts
subgraphs/uniswap-v3-forks/schema.graphql
subgraphs/uniswap-v3-forks/src/common/constants.ts
subgraphs/uniswap-v3-forks/yarn.lock

Adds subgraph for Iguana Dex V3 on
- network: etherlink-mainnet
- schema: generic (uses generic SDK)
- test deployment: https://okgraph.xyz/?q=QmUwzYDGsCQqmt9FP5Yd8fhHPrm6W51GM3QSg3aMS4SnNa
QA
- TVL: 
- Volume:
- Revenue:
- Usage:

feat(#major); iguanadex-v3; add subgraph
